vmware/versatile-data-kit

- projects/vdk-core/tests/functional/cli/test_set_cli_defaults.py
- projects/vdk-core/tests/functional/run/test_run_decorate_job_input.py
- projects/vdk-core/tests/functional/run/test_run_ingest.py
- projects/vdk-core/tests/functional/run/test_run_notifications.py
- projects/vdk-core/tests/functional/run/test_run_properties.py
- projects/vdk-core/tests/functional/run/test_run_simple.py
- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
- projects/vdk-core/tests/functional/run/test_run_templates.py
- projects/vdk-core/tests/functional/run/util.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_config_help.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/test_data_job.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/version/test_version.py
- projects/vdk-core/tests/vdk/internal/test_cli_entry.py
The unit test of vdk-core are not executing at all. And also are broken
due to changes in vdk-test-utils.
> vdk-core: fix unit tests

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobTerminationStatusIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/execution/JobExecutionServiceListExecutionsIT.java
The VDK Skip plugin relies heavily on running execution status.
In some cases, the execution status in the database may be
outdated due to delay. As a result the next job execution will be skipped.
In order to avoid such cases we must return only running jobs
in Kubernetes when a filter (status=RUNNING) is passed to the API.
Testing: unit tests
> control-service: improve list executions api correctness

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
A previous change allowed for the deployment to have additional
labels specified in the values.yml file, but those labels did
not transfer over to pods managed by the deployment.
This change allows for that.
Signed-off-by: gageorgiev <gageorgiev@vmware.com>
> control-service: Allow for additional labels in deployment pod

- projects/control-service/CHANGELOG.md
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
Testing done: Tested against a local control service, configured to run against
the environment where the bug initially appeared.
> control-service: fix NullPointerException when reading job deployment status

- projects/control-service/cicd/release-pipelines-service.sh
The name of the push command was apparently changed (to cm-push) during
the last (0.10.0) release of the ChartMuseum's push plugin, which
breaks our release cicd. This commit aims to fix this by renaming the
command.
Link: https://github.com/chartmuseum/helm-push
Testing done: none
> control-service: fix helm push comand during service release

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
Previously, the additional labels used by the CS Deployment and
the pods it manages were set as a multiline string in Values.yml.
After this change, they are set as YML instead.
Testing done: set additional labels in Values.yml and ran `helm
install --dry-run`, observed labels in correct place
Signed-off-by: gageorgiev <gageorgiev@vmware.com>
> control-service: Change dep additional labels to be set using YML

- projects/vdk-core/plugins/vdk-logging-json/src/vdk/plugin/logging_json/logging_json.py
- projects/vdk-core/plugins/vdk-logging-json/tests/test_logging_json.py
Double quotes in the log message would mess up the parsing, as
JSON separates fields and values based on double quote pairs.
This change escapes the double quotes in the message string.
Testing done: verified that the formatted log with double quotes
in the message is valid JSON
Logs before:
```
{"@timestamp":"2021-10-05T14:15:00.959Z","created":"1633432500.959478","jobname":"gg-job2","level":"INFO","modulename":"vdk.internal.builtin_plugins.run.cli_run","filename":"cli_run.py","lineno":"66","funcname":"run_job","attemptid":"1633432500-7b4ee0-db01f0","message":"Data Job execution summary: {\n  "data_job_name": "gg-job2",\n  "execution_id": "1633432500-7b4ee0",\n  "start_time": "2021-10-05T11:15:00.958685",\n  "end_time": "2021-10-05T11:15:00.959378",\n  "status": "success",\n …
```
> vdk-logging-json: Escape double quotes in message

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/create.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli_impl.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/download_job.py
Some warning messages were causing issues sinc we use VDKEXception to
format the log message and the type is not string.
> vdk-control-cli: fix warning message not to crash

- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_router.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_router.py
If we do not define any method we raise AttributeError like this:
```
File
"/vdk/site-packages/vdk/internal/builtin_plugins/ingestion/ingester_router.py",
line 65, in send_object_for_ingestion
method = (method or
self._cfg.get_value("INGEST_METHOD_DEFAULT")).lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```
We have rather more user friendly error which explains what user should
do in case method is not defined. And this fixes it to raise it
intstead.
Testing Done: including new tests which cover the issue and a bit more.
> vdk-core: ingester exception if no method

- projects/vdk-core/plugins/vdk-greenplum/.plugin-ci.yml
- projects/vdk-core/plugins/vdk-greenplum/README.md
- projects/vdk-core/plugins/vdk-greenplum/requirements.txt
- projects/vdk-core/plugins/vdk-greenplum/setup.py
- projects/vdk-core/plugins/vdk-greenplum/src/vdk/plugin/greenplum/greenplum_connection.py
- projects/vdk-core/plugins/vdk-greenplum/src/vdk/plugin/greenplum/greenplum_plugin.py
- projects/vdk-core/plugins/vdk-greenplum/tests/conftest.py
- projects/vdk-core/plugins/vdk-greenplum/tests/docker-compose.yml
- projects/vdk-core/plugins/vdk-greenplum/tests/jobs/sql-job/10_create_table.sql
- projects/vdk-core/plugins/vdk-greenplum/tests/jobs/sql-job/20_populate_table.sql
- projects/vdk-core/plugins/vdk-greenplum/tests/test_vdk_greenplum_utils.py
Capability to connect to Greenplum database, and execute queries.
A vdk-greenplum plugin introduced, that starts a Greenplum instance in
docker, then runs a sample data job to persist data. Tests verify the
data has been populated, using the newly introduced vdk-core CLI
command "greenplum-query". README.md added, describing on how to use the
plugin, enlist greenplum-related vdk-core configurations, and test
locally.
Testing Done: test_vdk_greenplum_utils added
> vdk-core: Greenplum support

- projects/vdk-control-cli/src/vdk/internal/control/configuration/vdk_config.py
- projects/vdk-control-cli/tests/vdk/internal/control/configuration/test_vdk_config.py
When someone configures VDK_BASE_CONFIG_FOLDER=~/.stg.vdk for example,
the directory must exist beforehand or vdk fails. This is a small
improvement that prevents it from falling so users do not have to
manually configure it every time.
Testing Done: the unit test (incl new ones)
> vdk-control-cli: auto-create base config directory

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
why: We noticed in the logs that a running control service 
would update a data job execution with a negative value for 
memory allocation. As a user I want to know for certain the 
allocated memory resources for a data job and a negative
value is an obvious bug.
what: Changed culprit function's implementation to use BigInteger instead
of int as the calculations it was performing would easily overflow the int
value at around 2gb or more.
testing: Added unit tests that verify function is working as intended
on small and large conversion numbers.
> [control-service]:fix memoryToMB conversion overflow in KubernetesService

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_pull_img.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-test.properties
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/MockKubernetes.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/JobImageDeployerTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageDeployerTest.java
- projects/control-service/projects/pipelines_control_service/src/test/resources/application-unittest.properties
Some control-service instances need to store Data Job
images in a private container registry, so we need to
apply registry credentials when pulling Data Job images.
Add secret containing docker registry credentials to the
pipelines_control_service helm chart and set it in
cron jobs on deploy (imagePullSecrets).
Tested by created, deploying and executing a Data Job
against a control service instance configured to push/pull
images to/from a private container registry.
> control-service: Fix authentication when pulling images

- projects/control-service/CHANGELOG.md
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
This change updates the version of the builder job image used
by the Control Service when deploying data jobs.
Testing Done: CI/CD Pipelines. Artefact in docker hub:
https://hub.docker.com/layers/175175600/versatiledatakit/job-builder/1.2.1/images/sha256-bb41b45fd10d109ccdd50f728c1d36413f91fdce94b9b02b203aa6c0049ceedd?context=repo
> control-service: Update Builder Job Version in helm

- projects/control-service/CHANGELOG.md
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/main/resources/k8s-data-job-template.yaml
Currently, Kubernetes jobs used for data job executions are configured by default
to run for up to 36 hours before being terminated.
This is a long time for single job execution. After examining the potential
impact of reducing this value on existing adoptions of the Versatile Data Kit,
I have decided to modify the deadline to use a more meaningful default of 12 hours.
Testing done: deployed a new data job and verified that its activeDeadlineSeconds is
now 12 hours.
> control-service: reduce the k8s job deadline to 12 hours

- projects/control-service/CHANGELOG.md
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
As part of the process of adopting the new builder image that
is to be used when deploying data jobs, we need to update the
version of the builder used by the Control Service.
This change updates the builder job image in the helm chart's
values.yml file.
Testing Done: Builder job image that is to be used is available
at https://hub.docker.com/layers/versatiledatakit/job-builder/1.2.2/images/sha256-8dd0d55bd9120621b557d5b36282084b453ca4cd0acb578999a34c8dc32fc5bd?context=repo
> control-service: Bump builder job version in helm

- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_deploy.py
test_utils.assert_click_status works better since it's provides more
detailed error message and stack trace to root cause the error.
> vdk-control-cli: use test_utils.assert_click_status for assertions

- projects/control-service/projects/pipelines_control_service/src/main/resources/db/migration/V20213110120000__add_last_execution_info_data_job.sql
As part of preparation for the implementation of the ability to filter
and sort data jobs by their last execution status, time, and duration,
add the respective columns to the data_job table.
Testing done: Start the service and verify that the columns are created
in the data_job table.
> control-service: add last execution info to the data_job table

- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_create.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_execute.py
If you have a plugin install that sets rest api url the test is affected
and it fails. This fixes that by setting explcitly the rest api url to
be emtpy
> vdk-control-cli: fix flaky unit tests

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobDeploymentCrudIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/ToApiModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/ToModelApiConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DockerImageName.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/model/JobDeployment.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/model/JobDeploymentStatus.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DockerImageNameTest.java
VDK version is the version of the VDK library with which the data job
run. We need it to return it when querying for deployment informatin in
order to know with which version of vdk the data job is configured to
run in cloud(kubernetes) deployment. 
See details on the analysis of how we update the vdk version in https://github.com/vmware/versatile-data-kit/issues/377
GET deployment (or list of deployments) returns the configured vdk
version
Testing Done: integration tests, unit tests.
Issue: https://github.com/vmware/versatile-data-kit/issues/377
> control-service: return and udpate vdkVersion in Deployment

- projects/control-service/CHANGELOG.md
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionResultManager.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/execution/JobExecutionResultManagerTest.java
Currently, if a data job execution exceeds the allowed memory
quota, the pod of the execution is immediately killed by
Kubernetes and restarted. Which in turn usually results in a
similar failure. This causes a Platform Error to be raised, whereas
it should be classified as a User Error.
This change re-classifies such errors as User Errors.
Testing Done: Added unit test.
> control-service: Classify OOM as User Errors

- projects/control-service/projects/pipelines_control_service/build.gradle
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/GraphQLProvider.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/DataJobExecutionFilter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/DataJobExecutionOrder.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/DataJobExecutionQueryVariables.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/schema.graphqls
- projects/control-service/projects/versions-of-external-dependencies.gradle
Extended the GraphQL schema (resources/schema.graphqls) by adding
an additional query called _executions_. It will allow us to filter
and sort executions by the following fields: status, startTime, endTime.
Sample request:
```
{{ baseUrl }}/data-jobs/for-team/no-team-specified/jobs?query={
executions(filter: {
endTime_gte: "2021-10-19T10:14:47Z",
status_in: ["failed", "cancelled"]
},
order: {property: "endTime", sort: DESC}) {
content {
id
startTime
endTime
status
jobName
}
}
}
```
Еvaluated an advanced filtering approach, but it seems to be out of scope
of this issue. It will take more implementation time since we should
introduce a new query engine.
```
{{ baseUrl }}/data-jobs/for-team/no-team-specified/jobs?query={
executions(filter: [
{op: gte, property: "endTime", value: …
```
> control-service: GraphQL executions query

- projects/vdk-core/cicd/example-job/30_check_orders_table.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
- projects/vdk-core/tests/functional/run/test_run_configuration.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_log_config.py
`vdk -v LEVEL` can be used to set logging level. But during vdk run this
was overriden by default levels set when configuring loggers. So `vdk -v
LEVEL` was not really working. This fixes that.
Logs of the vdk namespaces can also be controled by separate configu
LOG_LEVEL_VDK. It is set to INFO by default. It was being set to wrong
package though.
Also it's made optional. If not set, default log level (e.g provdied by
vdk -v LEVEL) is used.
Testing Done: ran `vdk -v DEBUG run example-job` and `vdk run
example-job` and saw expected logs
> vdk-core: vdk run logging levels

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
When there's cronjob in teh kubernetes namespace that is not a data job
deployment, we fail with NPE
We should likely filter them better so data job specific logic is not
applied to non-datajob cronjobs
Testing Done: integration test (created cron job in the namespace where
integration test runs)
> control-service: fix NPE when non-datajob cron job exists

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMonitor.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/monitoring/DataJobMonitorTest.java
There is a bug when checking whether to update the termination status of
a data job. Rather than checking if the executions are different, we
are checking that they are the same.
This commit fixes the bug and also adds more logging when an update is skipped.
Testing done: new unit tests are added
> control-service: fix a bug when updating the notification status

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/ToApiModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/GraphQLDataFetchers.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/V2DataJobDeployment.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/model/DataJob.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/schema.graphqls
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/GraphQLDataFetchersTest.java
Extended the GraphQL and service models to reflect the properties that were added
as part of the implementation of the ability to sort and filter data jobs by their
last execution status, time, and duration.
Wire the two models so that the newly added properties can be queried via GraphQL.
Testing done: Run the service locally and verified that the new properties are
returned when requested.
> control-service: Update the GraphQL model with the last execution

- projects/vdk-control-cli/requirements.txt
- projects/vdk-control-cli/setup.cfg
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli_impl.py
- projects/vdk-control-cli/src/vdk/internal/control/rest_lib/rest_client_errors.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_deploy.py
Setting vdk version is someitmes necessary to enable canary releases and
A/B Testing. See https://github.com/vmware/versatile-data-kit/issues/377
Adding command to set vdk version. It is hidden for now as it's
experimental
> vdk-control-cli: add command to set vdk version

- projects/control-service/CHANGELOG.md
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobDeploymentCrudIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/common/BaseIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DeploymentModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/DeploymentModelConverterTest.java
The vdk version was not actually being set because the merge logic was
was not merging it and the old version was kept.
Testing Done: started the control service locally and tested with vdk
deploy --update --vdk-version explicitly. Added test in integration test
suite.
> control-service: fix set vdk version be to set on image

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DataJobsDeploymentController.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DeploymentModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/ToModelApiConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/model/JobDeployment.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/DeploymentModelConverterTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/TestUtils.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceTest.java
Issue: https://github.com/vmware/versatile-data-kit/issues/403
API clearly defines that a unique data job  ID is a composite of team
and job name. But we are missing that when reporting job deployment
This causes any reports relying on the correct owner team not to work
properly.
Testing Done: ran control service locally with telemetry webhook set to
https://requestbin.com and saw telemetry contains dataJobTeam
```
{
"class_name_full" :
"com.vmware.taurus.service.deploy.DeploymentProgress",
"class_name_short" : "DeploymentProgress",
"measurable_args" :
"{\"deployment\":{\"dataJobTeam\":\"ai\",\"dataJobName\":\"ai-test\",\"gitCommitSha\":\"e88267478b4cfa83ec1482acf9f902b904eff12e\",\"enabled\":true,\"mode\":\"release\"}}",
....
"@table" : "taurus_api_call",
}
```
Signed-off-by: Antoni …
> control-service: add team to job deployment

- projects/control-service/projects/pipelines_control_service/build.gradle
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/notification/DataJobNotification.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/notification/EmailNotification.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/notification/DataJobNotificationTest.java
The smtp server used for deployment notifications was hard-coded which
means it would not have worked .
Testing Done: set datajobs.notifications.smtp.host in
application-properties and saw it is setting the correct value.
> control-serivice: make smtp server configurable

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
why: A user identified a problem with a data job deployment which
was related to keytab secret creation. The data job was not executing
due to missing secret keytab. Logs weren't enough to debug the
issue, so we need to add additional logs.
what: Added logging around the secret creation logic.
testing: trivial.
Signed-off-by: mrMoZ1 <mzhivkov@vmware.com>
> control-service: Add logging for keytab secret creation

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobsService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMonitor.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/monitoring/DataJobMonitorTest.java
As part of the implementation of filtering and sorting of data jobs
by last execution status, time, and duration, save the last
execution information in the data_job table when a data job
execution completes.
> control-service: update the last execution state on job completion

- projects/vdk-heartbeat/README.md
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/config.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/simple_run_test.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/database_ingestion/05_set_properties.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/database_ingestion/10_ingest_data.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/database_ingestion/20_verify_data.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/database_ingestion/config.ini
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/database_ingestion/requirements.txt
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/vdk_heartbeat_data_job/simple/10_simple.py
The test sends object for ingestion and then verifies
whether the object has been ingested.
Testing: tested manually against ETL and Trino
> vdk-heartbeat: trino ingestion test

- projects/control-service/projects/pipelines_control_service/build.gradle
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/ToApiModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobExecutionFilterSpec.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobExecutionRepository.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/ExecutionDataFetcher.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/GraphQLDataFetchers.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/GraphQLProvider.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/GraphQLUtils.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/DataJobExecutionFilter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/DataJobExecutionOrder.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/DataJobExecutionQueryVariables.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/DataJobPage.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/RepositoryUtil.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/JobExecutionFilterSpecIT.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/ExecutionDataFetcherFindAllAndBuildResponseIT.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/GraphQLDataFetchersTest.java
- projects/control-service/projects/versions-of-external-dependencies.gradle
Extended the existing GraphQL data fetcher for executions
(com.vmware.taurus.service.graphql.ExecutionDataFetcher)
to support filtering and sorting. The filtering and sorting
work at the database level for better performance
and resource (memory, network traffic, etc.) utilization.
The queries are be built dynamically based on the filters.
Sample GraphQL query:
```
{{ baseUrl  }}/data-jobs/for-team/no-team-specified/jobs?query={
executions(pageNumber: 1, pageSize: 100, filter: {statusIn: [RUNNING, SUBMITTED]}, order: {property: "status", direction: DESC}]) {
content {
id
startTime
endTime
status
jobName
}
}
}
```
Sample GraphQL response:
```json
{
"errors": [],
"data": {
"content": [
{
"id": "tms-staging-vdk-1633680894-1634638440",
"startTime": "2021-10-19T10:14:47Z",
"endTime": null, …
```
> control-service: extend GraphQL execution data fetcher

- projects/vdk-core/src/vdk/api/plugin/plugin_input.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_base.py
With the increase in the number of use-cases for ingestion,
there arises the need for some users to do post-processing
of ingestion data (e.g, to collect ingestion telemetry, etc.).
This change aims at introducing a new interface for plugin developers
to use when they want to do further processing of payloads after the
ingestion operation is complete, or to send telemetry data based on the
ingestion operation.
Testing Done: TODO after the spec is finalised.
> [vdk-core]: Post-ingestion specification

- support/telemetry/vdk-health/Dockerfile
- support/telemetry/vdk-health/README.md
- support/telemetry/vdk-health/vdk_github_token.cfg
- support/telemetry/vdk-health/vdk_project.cfg
- support/telemetry/vdk-health/vdk_projects.json
The VDK project requires some way to monitor the health of the
repository. This change includes a Dockerfile which, when deployed,
instantiates a set of tools which collect data from Github and
present it in a Kibana dashboard.
Testing done: ran locally
Signed-off-by: gageorgiev <gageorgiev@vmware.com>
> versatile-data-kit: vdk-health dockerfile

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLJobExecutionsStatusCountIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/V2DataJobDeployment.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/schema.graphqls
why: Users requested the ability to produce reports
based on data job execution failure/success numbers.
This is a part of the graphQL epic.
what: Added new fields in the schema and required
Java class.
testing: Added unit test which tests if keys are present.
Unit test will be refactored/extended to cover the full
functionality of the feature when we implement
the last story of  #424.
> control-service: add execution status fail/success to graphql schema

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMonitor.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/monitoring/DataJobMonitorTest.java
Recently we implemented a fix to classify job executions that run OOM
as User errors. For this purpose, we observe the status of the
executing pod. When the K8s job first terminates, its pod is inspected
and the termination status is correctly set to User error. However,
during subsequent updates, the pod may disappear and this is
interpreted as Platform error.
With this commit, we prevent changes to the termination status of an
execution if the status is final (i.e. not None).
Testing done: new unit tests
> control-service: fix OOM classification as User error

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/execute.py
vdkcli execute is stable command now and no reason to be hidden
> vdk-control-cli: remove hidden from vdkcli execute

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/notification/DataJobNotification.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/notification/NotificationContent.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application-prod.properties
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/notification/DataJobNotificationTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/notification/NotificationContentTest.java
Deploy notificatoins were not working properly due to auto-wiring issue
We also enable operator teams to set cc mail for all notifications
(using helm chart) in order to have visibilility into what notificatiosn
are sent to data job users
Testing Done: unit tests, locally deployed Control service and reproduce
scenario to get deploy anotifiactions
> control-service: fix deploy notifications and add cc mails

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/config.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
- projects/vdk-heartbeat/tests/vdk/internal/test_config.py
If we want to test VDK's configuration and default options, we want
to be able to set those params values in the default vdkcli options
and run vdk-heartbeat.
Make vdkcli_oauth2_uri and control_api_url params optional and don't
pass values if they are not set in the config.ini - thus whatever is
set as default in VDK's configuration will be used.
Tested by: Run locally built vdk-heartbeat in an environment with
properly configured defaults with a config.ini looking like this:
[DEFAULT]
VDKCLI_OAUTH2_REFRESH_TOKEN=***
JOB_RUN_TEST_MODULE_NAME=vdk.internal.heartbeat.simple_run_test
JOB_RUN_TEST_CLASS_NAME=SimpleRunTest
DATAJOB_DIRECTORY_NAME=simple
VDK_COMMAND_NAME=vdk
> vdk-heartbeat: Make vdkcli_oauth2_uri and control_api_url optional

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobsRepository.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobsService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMonitor.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/JobsRepositoryIT.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/monitoring/DataJobMonitorTest.java
The recently introduced functionality to filter and sort
by last execution of data jobs has a bug where older executions
are not properly checked and as a result, the last execution
is always updated, even when the current execution is older
than the last one.
This commit fixes that.
Testing done: new unit test for this use case
> control-service: fix a bug in the GraphQL implementation

- projects/vdk-plugins/.plugin-common.yml
- projects/vdk-plugins/vdk-greenplum/README.md
- projects/vdk-plugins/vdk-impala/README.md
- projects/vdk-plugins/vdk-postgres/README.md
- projects/vdk-plugins/vdk-trino/README.md
- projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/README.md
The release CI job template in .plugin-common.yml was not fixed
to cd into the new plugins directory. This change fixes it. Also
fixed some links in plugin readmes.
Testing done: making new release of vdk-sqlite to verify job works
https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/415630020
> vdk-plugins: Fix release job template

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLExecutionsIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobExecutionFilterSpec.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/ExecutionDataFetcher.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/DataJobExecutionFilter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/model/DataJobExecutionOrder.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/schema.graphqls
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/RepositoryUtil.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/ExecutionDataFetcherFindAllAndBuildResponseIT.java
why: Users requested additional API functionality which includes
filtering and sorting by data job execution name, start and end
times. This will help operators monitor overall executions status.
Currently to achieve this we have to retrieve all jobs and their 
corresponding executions. 
what: Added new fields to graphql schema and extended
existing control-service functionality to cover requested fields.
testing: Added unit tests which cover the new functionality.
> control-service: graphQL filter by jobName, startTimeLte, endTimeLte

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/data_job.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input_error_classifier.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/job_input_error_classifier_test.py
Currently, if an exception is raised in user code (the run method in a data
job python script), the error is classified as a Platform Error, even though
it is caused by something outside of vdk control.
This happens because in the DataJobDefaultHookImplPlugin class, the exception catching
logic uses errors.find_whom_to_blame_from_exception() method, instead of
job_input_error_classifier.whom_to_blame() method. The former just checks the exception
class, while the latter actually parses the exception traceback, and tries to properly
classify the error.
This change moves error classification from errors.find_whom_to_blame_from_exception() to
job_input_error_classifier.whom_to_blame(), and improves the robustness of the latter in case
there are changes in vdk file paths which could lead to …
> vdk-core: Fix error in user code classified as Platform Error

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/log_config.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/main.py
[OpId](https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py#L72) is used to track the same operation across multiple services, CLIs,
data (ala open tracing style). It helps troubleshooting efficiently -
just search for the op id of the failed process we are troubleshooitng
and you have end to end data flow picture.
Testing Done: vdk-heartbeat -f local.ini  and verified op id is printed
in the local logs and in the logs of the Control service (and passed to
the data job execution)
> vdk-heartbeat: make sure op_id is passed everywhere

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
Remove redundant "created" timestamp we always print. It's never really
used for anything.
Rename OpId: to Id: since we print attempt id there (and not really
opId).
But attempt id is rather long "id" seems better to fit the space.
> vdk-core: simplify log line

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/config.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
We want to be able to run vdk-heartbeat against a local
control service.
If no VDKCLI_OAUTH2_REFRESH_TOKEN/VDK_HEARTBEAT_API_TOKEN
is set, run login with no params - it defaults to localhost.
Testing done: run locally built vdk-heartbeat with
and without oauth2 refresh token set.
> vdk-heartbeat: Make oauth2 refresh token optional

- projects/vdk-plugins/vdk-logging-json/src/vdk/plugin/logging_json/logging_json.py
- projects/vdk-plugins/vdk-logging-json/tests/test_logging_json.py
[OpID](https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py#L72) is used to correlate pipelines of operations going through
difference services so it needs to be available in the logs of the data job. 
> vdk-logging-json: pass op_id attribute to logs

- projects/vdk-plugins/plugin-template/README.md
- projects/vdk-plugins/plugin-template/requirements.txt
- projects/vdk-plugins/plugin-template/tests/jobs/job-using-a-plugin/10_dummy.py
- projects/vdk-plugins/plugin-template/tests/test_plugin_template.py
Add sample test relying on vdk-test-utils to show the current
recommended way to write tests for plugins.
> plugin-template: add sample tests

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/cli_run.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/data_job.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input_error_classifier.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/job_input_error_classifier_test.py
As part of https://github.com/vmware/versatile-data-kit/pull/566, a regression
was introduced which caused genuine Platform Errors to be classified as User Errors.
This change rollbacks the previous one, and fixes the regression while doing proper
user code error classification.
Testing Done: Unit tests
> vdk-core: Fix regression in job input error classifier

- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
This change aims to reduce the pulling of docker images. There's no
point of trying to pull it every time if we don't use `latest` tag.
Testing Done: integration test passed
> control-service: change default image.pullPolicy

- projects/vdk-core/src/vdk/internal/builtin_plugins/version/new_version_check_plugin.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/version/test_new_version_check_plugin.py
If VDK or some plugin has a newer version, VDK automatically
prints out a message stating this and prompting the user to
update. However, this is printed out at the start of the log,
and can be easily missed.
This change moves the printout to the end of the log.
This change also reworks the printout to collect multiple
components into one printout.
Testing done: verified printout appears at the end
if only one package needs an update, we get the following:
```
******************************************************************************************
New version for vdk-core is available.
Please update to latest version by using:
pip install --upgrade-strategy eager -U vdk-core
******************************************************************************************
```
If multiple …
> vdk-core: Rework new version printout

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/config.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/hearbeat.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
We want to be able to run vdk-heartbeat as a pre-release
step in out CI/CD pipelines. This requires running it with a
specific vdk version.
Add VDK_HEARTBEAT_DEPLOY_JOB_VDK_VERSION configuration variable
in vdk-heartbeat. If set, it updates the job deployment to use
the specified vdk version.
Testing done: run vdk-heartbeat with a specified version against
a local control service and observe that this version is used
in the execution k8s pod. Tested with config.ini:
[DEFAULT]
VDK_HEARTBEAT_DEPLOY_JOB_VDK_VERSION=0.1.374271018
JOB_RUN_TEST_MODULE_NAME=vdk.internal.heartbeat.simple_run_test
JOB_RUN_TEST_CLASS_NAME=SimpleRunTest
DATAJOB_DIRECTORY_NAME=simple
VDK_COMMAND_NAME=vdk
Signed-off-by: Yana Zhivkova yzhivkova@vmware.com
> vdk-heartbeat: Make vdk version configurable

- projects/vdk-control-cli/cicd/build.sh
- projects/vdk-heartbeat/cicd/build.sh
Python code coverage was not working correctly because it was scanning the wrong modules 
Testing Done: CI of this PR - checked that coverage was generated correctly: https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/1845803340#L327 and https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/1845803344#L200
>  fix python coverage report

- projects/vdk-core/src/vdk/internal/builtin_plugins/version/new_version_check_plugin.py
Until now, if an error occured during checking for a new version,
it would be logged at the end.
This moves it to DEBUG where it belongs.
> vdk-core: Log version check error to DEBUG

- projects/control-service/projects/model/apidefs/datajob-api/api.yaml
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobDeploymentCrudIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/common/BaseIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DeploymentModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
When enabling job vdk version was accidentally reset - see
https://github.com/vmware/versatile-data-kit/issues/573
This is caused by DeploymentModelConverter who was not copying vdk
version field correctly.
Also changed API to not set default value for vdk version. If not set,
we take latest configured value or default to True only if not
configured before.
Testing Done: integration tests (incluing new one to cover the scenario)
> control-service: vdk version was being overwritten when not set

- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/decoration_cursor.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/impl/wrapped_connection.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_connection_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/recovery_cursor.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/termination_message/writer.py
Certain log calls would include the exception without specifying a
substitution string inside in the logged message for it. This lead
to an error when that log call is executed. This change fixes that
by replacing the log message with an f-string and includes the
exception in it.
Additionally, it replaces certain log calls in the code base with
f-strings as they are the recommended way of formatting strings.
> vdk-core: Fix inclusion of exception message in log call

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/common_group/default.py
- projects/vdk-control-cli/src/vdk/internal/control/configuration/defaults_config.py
- projects/vdk-control-cli/src/vdk/internal/control/rest_lib/factory.py
vdk-control-cli no longer has option to disable or enable authentication
as if auth is needed is authomatically detected instead (https://github.com/vmware/versatile-data-kit/pull/305)
So we no longer neet `vdk set-default --authentication-disable` so I am
removing it.
> vdk-control-cli: remove unnnecessary options

- projects/vdk-plugins/vdk-server/src/vdk/plugin/server/installer.py
After the removal of the reset_default_authentication_disable() and
write_default_authentication_disable() logic from vdk-control-cli in
https://github.com/vmware/versatile-data-kit/commit/307c1c9c14530476a7f33163ed30f72d01193aed
installing vdk-server was not possible due to an ImportError.
This change removes the authentication-related imports from vdk-server's
installer, and fixes the ImportError raised when running `vdk server --install`
Testing Done: Ran `vdk server --install` and observed that vdk-server installs as
expected.
> [vdk-plugins][vdk-server]: Remove authentication imports

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLDataJobsSortContactsIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLJobExecutionsStatusCountIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/strategy/datajob/JobFieldStrategyBy.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/strategy/datajob/JobFieldStrategyByDataJobContacts.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/strategy/datajob/JobFieldStrategyByContactTest.java
why: Users requested the ability to sort DataJobs
by notifications. This is a part of the graphql epic.
what: Added the ability to sort by notifications enabled
or not. We check if one of the contacts is populated and
if it is, we threat it as a notification enabled. The DataJobs
will then get sorted by notification enabled status
testing: Added unit tests. 
> control-service: graphQl add sorting by notifications

- projects/vdk-core/tests/README.md
It was using the wrong directory name (we forgot to fix after renaming it)
> vdk-core: update testing readme

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobExecutionIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobTerminationStatusMonitoringIT.java
Splitted DataJobTerminationStatusIT into DataJobExecutionIT and
DataJobTerminationStatusMonitoringIT.
Testing Done: integration tests
> control-service: split DataJobTerminationStatusIT

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobExecutionIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobTerminationStatusMonitoringIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/common/BaseDataJobDeploymentIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/common/BaseIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLJobExecutionsStatusCountIT.java
Currently the integration tests depend on the same data job.
Sometimes it may take a little longer to complete the data job execution
between the tests. As a result the API will return 409
and the particular test will fail.
This change adds synchronization between data job executions.
Testing Done: integration tests
> control-service: improve integration tests stability

- projects/vdk-plugins/vdk-impala/tests/conftest.py
- projects/vdk-plugins/vdk-impala/tests/functional/test_impala_connection.py
The vdk-impala functional tests would require a time.sleep statement
at their start due to an issue where the Impala would return a response
with exit code 0, but the service would not yet be available, which
would cause tests to fail.
This change moves that time.sleep call to the pytest fixture function
for two reasons: it logically makes more sense for it to be there, and
this way it will only ever be invoked once, instead of at the start of
every single functional test.
> vdk-impala: Move time.sleep fix to conftest

- projects/vdk-plugins/vdk-ingest-http/src/vdk/plugin/ingest_http/ingest_http_plugin.py
- projects/vdk-plugins/vdk-ingest-http/src/vdk/plugin/ingest_http/ingest_over_http.py
- projects/vdk-plugins/vdk-ingest-http/tests/test_ingest_over_http.py
Capability for compressing the ingestion payload if exceeding a
certain configurable threshold was missing. Also, no ingestion result
was returned.
Added configurations for INGEST_OVER_HTTP_COMPRESSION_THRESHOLD_BYTES
and INGEST_OVER_HTTP_COMPRESSION_ENCODING. When payload exceeds the
threshold configured, it gets compressed in gzip format. The ingestion
result is then returned, including metadata about
uncompressed_size_in_bytes, compressed_size_in_bytes and http_status.
Testing Done: added test_ingest_over_http_compression and
test_ingest_over_http_result; verified tests locally
> vdk-ingest-http: Add support for compression and ingestion result

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/execution_environment.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/version/version.py
It is possible to have multiple pythons installed on the same machine.
Even if not it's almost certain there are multiple virtual environments
(or conda envs) and knowing exactly which on you are using can be
valueable when debugging.
Print the details about the python being used to run vdk.
Testing Done: ran `vdk version`:
```
...
Python version: 3.9.5 64bit
(/Users/aivanov/.pyenv/versions/3.9.5/envs/build-vdk-plugin-control-cli39/bin/python3.9)
```
> vdk-core: print python version with `vdk version`

- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/ExecutionDataFetcher.java
If we request jobs and their executions without filters at the execution level,
the API will return all executions from the database per each data job.
> control-service: fix graphql executions loading

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/strategy/datajob/JobFieldStrategyByLastExecutionDuration.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/strategy/datajob/JobFieldStrategyByLastExecutionStatus.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/strategy/datajob/JobFieldStrategyByLastExecutionTime.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/GraphQLDataFetchersTest.java
Тhe new filters we added are not consistent with the existing ones.
Changed the sorting from `nullLast` to `nullFirst`.
> control-service: make graphql sorting consistent

- projects/vdk-control-cli/requirements.txt
- projects/vdk-control-cli/setup.cfg
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_show.py
Bump vdk-control-service-api version to 1.0.6. The new version
changes DataJobExecution statuses.
This change will be merged after https://github.com/vmware/versatile-data-kit/pull/574.
> vdk-control-cli: bump vdk-control-service-api version

- projects/vdk-core/src/vdk/api/plugin/core_hook_spec.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/cli_run.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/data_job.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/execution_results.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/step.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/templates/template_impl.py
- projects/vdk-core/src/vdk/internal/core/errors.py
- projects/vdk-core/tests/functional/run/jobs/fail-job/1_step.py
- projects/vdk-core/tests/functional/run/test_run_errors.py
- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/test_cli_run.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/test_data_job.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/test_execution_results.py
- projects/vdk-core/tests/vdk/internal/plugin/test_plugin.py
There was some corner cases that error message was missing - if job
failed with an exception for example during initialize or finalize phases.
Also made sure job finishes with summary of job execution so it's easier
for users to see what happened.
Also if job step failed - it was printing the exception twice (at step
level and job level) which is just cluttering the logs
Tesitng Done: unit tests.
Error message looks like this: 
```
"data_job_name": "sql-job-syntax-error",
"execution_id": "63d0ccf3-258f-46e1-9d50-b246402ff926-1639474925",
"start_time": "2021-12-14T09:42:05.656806",
"end_time": "2021-12-14T09:42:05.690940",
"status": "error",
"steps_list": [
{
"name": "bad-query.sql",
"type": "sql",
"start_time": "2021-12-14T09:42:05.656809",
"end_time": "2021-12-14T09:42:05.690905", …
```
> vdk-core: provide needed error details for vdk run 

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLExecutionsLogsUrlIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionLogsUrlBuilder.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/execution/JobExecutionLogsUrlBuilderIT.java
Some of the external systems that our customers use
have different time than Control Service.
This change aims to introduce configurable offset
that will be added to both start_time and end_time varibles
during the building of logs URL for each particular execution.
Testing Done: unit and integration tests
> control-service: ability to add offset to dates in logs URL

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMonitor.java
At the moment, after the control service is being redeployed,
all K8s jobs and K8s PODs to them are retrieved in order to
synchronize potentially missed K8s events.
Usually, the process synchronizes the K8s Jobs for the last few minutes
but in case of redeploy it synchronizes all jobs
as the variable `lastWatchTime`=0.
This change sets the appropriate `lastWatchTime` default value, 
thus reducing the synchronization time.
> control-service: fix job monitoring

- projects/vdk-control-cli/src/vdk/internal/control/configuration/vdk_config.py
- projects/vdk-control-cli/src/vdk/internal/control/job/job_config.py
- projects/vdk-control-cli/src/vdk/internal/control/utils/control_utils.py
- projects/vdk-control-cli/tests/resources/test-broken-vdk-config/vdk-configuration.ini
- projects/vdk-control-cli/tests/vdk/internal/control/configuration/test_vdk_config.py
Currently, if the config.ini file of a data job contains a special unicode
character, Versatile Data Kit prints the whole traceback, which may confuse
the user as to what is happening.
This change handles the exception and prints a message with more user-friendly
details as to what might be the possible cause for the error. The complete traceback
is printed only in debug mode.
Testing Done: Added a unit test, and tested locally by deploying a data job, whose config.ini
file contained a special unicode character. Verified that no traceback appears in the terminal.
The message shown was:
```
Error: ¯\_(ツ)_/¯
what: Cannot parse the Data Job configuration file.
why: Configuration file config.ini is probably corrupted. Error: File contains no section headers.
file: …
```
> vdk-control-cli: Fix traceback shown for broken config.ini

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/download_job.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_download_job.py
Currently, if a client tries to download a data job but misspells the
team name, two exception messages are printed in the terminal similar
to the ones below:
```
Path to the data job directory [C:\some\user\directory]:
Downloading data job <data-job-name> in C:\some\user\directory/<data-job-name> ...
warning: ¯\_(ツ)_/¯
warning:
warning: what: Cannot cleanup archive: C:\some\user\directory\<data-job-name>.zip as part of deployment.
warning: why: VDK CLI did not clean up after deploying: [WinError 2] The system cannot find the file specified: 'C:\\some\\user\\directory\\<data-job-name>.zip'
warning: consequences: There is a leftover archive file next to the folder containing the data job
warning: countermeasures: Clean up the archive file manually or leave it
Usage: vdk download-job …
```
> vdk-control-cli: Hide Cannot-cleanup-archive warning

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
Currently, when an exception happens during k8s job watching,
we swallow the exception and log only the exception message.
This prevents us from pinpointing the exact location of the
exception and makes troubleshooting it harder.
This commit also logs the exceptions' stack trace.
Testing done: verified that the stack trace is logged on exception.
> control-service: improve logging during job monitoring

- projects/control-service/cicd/.gitlab-ci.yml
- projects/vdk-control-cli/.gitlab-ci.yml
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/config.py
This PR contains 3 commits 2 of them set op id to be same as $CI_PIPELINE_ID 
By setting op_id to be the Pipeline ID we can easier track a given run of vdk-heartebaet as op_id is printed in the logs, it is passed to the job logs, the job name also contains the Op ID . So one can easier see which pipeline generated which job and vice-versa
And small change in vdk-heartbeat that make sure do not accidentally create job name with too long name (as op id is included in the job name
> control-service/vdk-cli/vdk-heartbeat: set Pipeline ID as op_id for vdk-heartbeat run

- projects/vdk-core/.gitlab-ci.yml
- projects/vdk-core/cicd/release_acceptance_test_heartbeat_config.ini
We want to avoid releasing broken distributions of vdk-core as much
as possible. The newly added acceptance test would allow us to
release vdk-core only after vdk-heartbeat runs successfully with
a release candidate vdk-core version containing latest changes.
Run vdk-heartbeat on stage pre_release_test of CI/CD with
release candidate distribution and image created during
previous stages - pre_release and pre_release_image.
Testing done: testing CI/CD pipeline on pull request -
https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/434951809
with hard-coded release candidate version of distribution and image (0.0.430145938.dev3240),
which were already created during a previous pipeline - https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/430145938
Signed-off-by: …
> vdk-core: Release acceptance test job added to CI/CD

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobsService.java
We got reports that the last execution status of a data job
can get out-of-sync with the status persisted in the data_job_execution
table. This commit adds logging to the method that updates the last
execution information of a data job so that it is easier to troubleshoot.
> control-service: add logging when updating last execution

- projects/control-service/projects/pipelines_control_service/src/main/resources/db/migration/V20213111120000__create_index_idx_data_job_execution_job_name_start_time.sql
- projects/control-service/projects/pipelines_control_service/src/main/resources/db/migration/V20213112120000__create_index_idx_data_job_execution_job_name_end_time.sql
Our internal client reported performance issue when loading data jobs
and executions through GraphQL API.
The performance issue is caused by lack of indexes on the most frequently
filtered columns.
Testing Done: unit tests, integration tests, performance tests against
local CockroachDB (the query with indexes is 7 times faster)
> control-service: improve performance of executions loading

- projects/control-service/cicd/release-pipelines-service.sh
Currently if the commit sha is integer 1647200 the image.tag will be
"1.6472e+06" because of the toString function used here - https://github.com/vmware/versatile-data-kit/blob/main/projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl#L76.
Helm Issue: https://github.com/helm/helm/issues/1694
Testing Done: helm template
> control-service: fix helm image tag type

- projects/control-service/cicd/release-pipelines-service.sh
Reverts vmware/versatile-data-kit#661
`--set-string` is not supported by `helm pack`.
> Revert "control-service: fix helm image tag type"

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLExecutionsIT.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/schema.graphqls
The types of cpuRequest and cpuLimit differ from the OpenAPI definition.
https://github.com/vmware/versatile-data-kit/blob/main/projects/control-service/projects/model/apidefs/datajob-api/api.yaml#L1315
As a result, the GraphQL API returns the following error:
```json
{
"errors": [
{
"message": "Can't serialize value (/executions/content[0]/deployment/resources/cpuRequest) : Expected type 'Int' but was 'Float'.",
"path": [
"executions",
"content",
0,
"deployment",
"resources",
"cpuRequest"
],
```
Testing Done: integration tests
> control-service: fix graphql schema

- projects/control-service/projects/pipelines_control_service/build.gradle
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/RepositoryRetryOperationsConfiguration.java
- projects/control-service/projects/versions-of-external-dependencies.gradle
The following exception has been observed for some time:
```
Dec 20 14:30:43 tpcs-dep-7f94dcdcfc-c7282 	at com.vmware.taurus.datajobs.DataJobsController.jobsQuery(DataJobsController.java:234)
Dec 20 14:30:43 tpcs-dep-7f94dcdcfc-c7282 	at com.vmware.taurus.service.GraphQLJobsQueryService.executeRequest(GraphQLJobsQueryService.java:56)
Dec 20 14:30:43 tpcs-dep-7f94dcdcfc-c7282 	at graphql.GraphQL.execute(GraphQL.java:426)
Dec 20 14:30:43 tpcs-dep-7f94dcdcfc-c7282 	at graphql.GraphQL.executeAsync(GraphQL.java:493)
Dec 20 14:30:43 tpcs-dep-7f94dcdcfc-c7282 	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:529)
Dec 20 14:30:43 tpcs-dep-7f94dcdcfc-c7282 	at graphql.GraphQL.execute(GraphQL.java:598)
Dec 20 14:30:43 tpcs-dep-7f94dcdcfc-c7282 	at …
```
> control-service: fix LockAcquisitionException

- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/authenticator_factory.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/base_authenticator.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/kerberos_configuration.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/kinit_authenticator.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/minikerberos_authenticator.py
Currently, the Kerberos authentication is always using a generic
krb5.conf file built into the plugin. This commits enables specifying
the path to the krb5.conf file via configuration (`KRB5_CONF_FILENAME`).
If the configuration is not set, it defaults to the built-in file.
Testing done: manually running the `run` command with and without the
new configuration and observing that the appropriate krb5.conf file is
being used.
> vdk-kerberos-auth: provide variable to specify krb5.conf configuration

- projects/vdk-plugins/vdk-impala/tests/functional/test_impala_connection.py
The DecoratedSqLite3MemoryDbPlugin is being registered for the purposes
of testing Impala, that seems unnecessary.
Dropped DecoratedSqLite3MemoryDbPlugin in context of
`test_impala_connection.py` to simplify.
Testing Done: did run vdk-impala tests locally to verify
> vdk-impala: Cleanup of DecoratedSqLite3MemoryDbPlugin during test phase

- projects/vdk-plugins/vdk-impala/tests/docker-compose.yml
- projects/vdk-plugins/vdk-impala/tests/functional/jobs/sql-job-syntax-error/10_bad_query.sql
There were issues with syntax support of the previous Impala docker
image used for tests.
Did search and found a viable solution that runs a newer Impala version.
Testing Done: did run vdk-impala tests locally to verify,
all tests pass, including the ones on Impala templates support draft MR
https://github.com/vmware/versatile-data-kit/pull/671
> vdk-impala: Impala docker image upgrade

- projects/control-service/projects/base/src/main/java/com/vmware/taurus/security/SecurityConfiguration.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobCrudIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/doc/SwaggerConfig.java
The Swagger UI is currently available at root / by default. Since the
API is prefixed by /data-jobs, we would like for the Swagger to also be
available under same path, in a consistent fashion. This unblocks
services composition by dedicated path for accessing all features.
Did add Swagger configuration for additional controllers redirect and
resource handler. Updated an integration test to verify the path.
Updated also SecurityConfiguration swagger paths.
Testing Done: did run unit tests, and also verified swagger-ui.html is
accessible under /data-jobs locally
> pipelines-control-service: publish Swagger UI to /data-jobs path

- projects/vdk-core/src/vdk/internal/core/config.py
- projects/vdk-core/tests/vdk/internal/core/test_config.py
Variable can be added (has its type defined) by one plugin after its
value is set by 2nd plugin.   In that cases the value would not be cast
to the correct type nor validated. This moves that casting/validation at
the point of definition (when #add is called) if value is already set
for same config key.
Testing Done: see unit tests
> vdk-core: adjust defined type for configuration values

- projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/ingest_to_trino.py
- projects/vdk-plugins/vdk-trino/tests/jobs/test_ingest_to_trino_job/10_ingest_to_trino.py
- projects/vdk-plugins/vdk-trino/tests/test_ingest_to_trino.py
Fix trino ingestion to handle different data types  more gracefully.
It will make sure the the data type (passed in python) is correctly set
based on the data type in the destination table.
Handle missing values (e.g if a value for column X is missing , it will
set it to None / NULL insted of failing
Handle case insensitive fields. The columns names (or field names) passed by the user can be in any case but trino column names are case insensitive so we normalize them to match.
Testing Done: extended functional tests to cover the new scenarios. Also ran the data job in the https://github.com/vmware/versatile-data-kit/pull/616 (with ingestion using job_input.send_...) and saw it completed successfully and ingested the data correctly in my local trino.
Signed-off-by: Antoni Ivanov …
> vdk-trino: trino ingest to handle type casting and missing values

- projects/vdk-core/cicd/build.sh
- projects/vdk-core/src/vdk/api/plugin/plugin_input.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_configuration_plugin.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_base.py
As part of the effort to extend the Ingestion API to support plugin
chaining, we need to improve the interfaces that are to be used by
data engineers and plugin developers.
This change adds a new environment variable, `INGEST_PAYLOAD_POSTPROCESS_SEQUENCE`
that data engineers can use to specify a plugin/s that would deal with post-ingestion
processing tasks, such as sending telemetry, etc.
Additionally, the interfaces that plugin developers use in ingestion pre-processing
and post-processing tasks, are extended to pass payload, destination_table, target and
collection_id as read-only parameters to allow for better workflows.
Testing Done: Unit tests pass, and ran a local test ingestion data job as described in
https://github.com/vmware/versatile-data-kit/wiki/Ingesting-data-from-DB-into-Dat …
> [vdk-core] Introduce post-ingest-sequence env var

- projects/vdk-plugins/vdk-test-utils/src/vdk/plugin/test_utils/ingest_util_plugins.py
This change adds test plugins for pre-ingest processing, ingestion and post-ingest processing
operations to the vdk-test-utils plugins. These are to be in functional tests across different
components.
Testing Done: Not required, plugin implementations to be used in functional tests across
different Versatile Data Kit components.
> [vdk-plugins][vdk-test-utils] Add test pre-ingest, ingest, post-ingest plugins

- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
Info message was failing because it though the second sentence was
second paramter (remove the comma to fix that)
> vdk-core: fix error message

- projects/vdk-core/tests/functional/run/test_run_ingest.py
- projects/vdk-plugins/vdk-greenplum/src/vdk/plugin/greenplum/ingest_to_greenplum.py
- projects/vdk-plugins/vdk-ingest-file/src/vdk/plugin/ingest_file/ingestion_to_file.py
- projects/vdk-plugins/vdk-ingest-http/src/vdk/plugin/ingest_http/ingest_over_http.py
- projects/vdk-plugins/vdk-sqlite/src/vdk/plugin/sqlite/ingest_to_sqlite.py
- projects/vdk-plugins/vdk-test-utils/src/vdk/plugin/test_utils/util_plugins.py
- projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/ingest_to_trino.py
As part of https://github.com/vmware/versatile-data-kit/pull/682, the
signature of the ingest_payload() method was updated to accept a metadata
object as part of the ingestion flow.
Once the interface change is adopted in vdk-core, this would cause data jobs to
fail, due to missing keyword argument "metadata".
This change updates the signatures of the ingest_payload() methods, implemented
in the vdk-plugins that provide ingestion capabilities. This is done in order to
avoid the abovementioned error.
Testing Done: Not required, as no plugins currently process the metadata.
> [vdk-plugins] Update ingestion interfaces used in plugins

- projects/control-service/projects/helm_charts/pipelines-control-service/README.md
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMetrics.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMonitor.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/monitoring/DataJobMetricsTest.java
Currently, we are lacking monitoring of our data job watching task -
this is the task that monitors the K8s namespace for data job changes and
updates the execution and termination statuses of the data jobs along with
the metrics exposed by the control service.
We have experienced cases when this task stops running. Considering the
importance of this task it is essential that we get an early alert when
this happens. This commit introduces a new metric (counter) that exposes
the number of executions of this task. This counter can then be used in
dashboards to alert when the task stops executing for a period of time.
Testing done: new unit tests; manually starting the service to observe
the new, gradually increasing metrics.
> control-service: add counter to track data job watching task executions

- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_router.py
- projects/vdk-core/src/vdk/internal/util/utils.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_base.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_router.py
As part of https://github.com/vmware/versatile-data-kit/pull/682
and https://github.com/vmware/versatile-data-kit/pull/672 the ingestion
interfaces were extended to support ingestion plugin chaining for pre- and
post- processing operations.
This change introduces the implementation of the extended ingestion functionality.
The IngesterRouter and IngesterBase classes are extended to support the use of pre-
and post- ingestion processing plugins.
Testing Done: unit tests; functional tests to follow in a separate PR.
> [vdk-core] Implementation of new ingestion interfaces

- projects/vdk-plugins/vdk-impala/MANIFEST.in
When running templates, no data is being handled. The cause is
all template .sql steps are missing when python distribution is
bundled.
Added MANIFEST.in file including *.sql files.
Testing Done: did run python sdist, then verified the .sql files
are bundled-in.
> vdk-impala: template .sql missing from python distro

- projects/control-service/projects/base/src/main/java/com/vmware/taurus/security/SecurityConfiguration.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobCrudIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/doc/SwaggerConfig.java
Swagger UI HTML page is not completely rendered. Cause is,
the resources included in swagger-ui.html that are /webjars/**
were not redirected to /data-jobs.
Path-prefixed the webjars for auth purposes. Redirected
webjars to the new path.
Testing Done: did add an integration test to verify availability of
a webjar expected.
> pipelines-control-service: redirect Swagger webjars resources

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/role.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/role_datajobs.yaml
We are requiring permissions for accessing pods/log subresource that
seem not to be applicable for pods/log See
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources
and it fails on some kubernetes clusters (I assume newer version of
kubernets is more strict)
Testing Done: helm install relase-foo <edited-helm-chart> and saw it
passed
> control-service: fix role permissions for pod/logs

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/NOTES.txt
- projects/vdk-plugins/vdk-server/src/vdk/plugin/server/installer.py
pipelines-control-service: Swagger UI path changes docs update
Swagger UI path has been changed to /data-jobs/swagger-ui.html
Docs/user-facing messages updated to the new path.
Testing Done: no functional changes made.
> pipelines-control-service: Swagger UI path changes docs update

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/successful_run_test.py
The util was missing a simple test, that verifies the (custom or not)
data job has run once and succeeded.
Introduced `successful_run_test.py`. Elaborated on `job_controller.py`
to return the data job status on `check_job_execution_finished`.
Fixed a controller bug - in case no executions were present, the flag
was still set to `job_execution_running = False`.
Testing Done: did verify locally the filtering of latest_end_date
and retrieving the status based on execution list data.
> vdk-heartbeat: Successful data job run test mode

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_error_handler.py
- projects/vdk-plugins/vdk-impala/tests/impala_handle_metadata_exception_with_invalidate_and_retry_test.py
Currently, the impala error handling logic fails to properly handle
TableAlreadyExist exceptions, in cases where these are caused while processing
`CREATE VIEW` sql queries.
This change modifies the error handling logic to properly handle exceptions
caused while processing `CREATE VIEW` queries.
Testing Done: Added unit test.
> [plugins][vdk-impala] Improve error handling to handle view errors

- projects/vdk-control-cli/src/vdk/internal/control/job/job_config.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_datajob_config.py
Until now we required contacts be separated by ";" semi-colon. This was
error prone as a lot of users are using "," comma and we are not really
preventing them so mails were written as "a@abv.bg,b@dir.bg" as if it is
a single email. T This also meant that people were not getting
notifications.
The fix is to add "," comma as allowed delimiter as a first step.
In a subsequent change we can add a email validator (like
https://pypi.org/project/email-validator)
Testing Done: unit tests including new ones
> vdk-control-cli: Parse contacts with both comma "," as delimiter as well

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/successful_run_test.py
Recently functionality for checking if the data job finished
successfully was added. It checks if the last execution of
the data job was successful - status 'succeeded'.
Check if status is 'succeeded', not 'success'.
Testing Done: ran vdk-heartbeat locally with
successful_run_test, and it finished successfully.
> [vdk-heartbeat] Fix successful run status check

- projects/vdk-plugins/vdk-ingest-http/src/vdk/plugin/ingest_http/ingest_http_plugin.py
- projects/vdk-plugins/vdk-ingest-http/src/vdk/plugin/ingest_http/ingest_over_http.py
- projects/vdk-plugins/vdk-ingest-http/tests/test_ingest_over_http.py
Based on requests encoder/decoder default configuration, simplejson/json
is used to handle a specification compliant JSON by default. We need a
configurable allow NaN capability, so that when enabled, ingestion
payload NaN values are parsed correctly - instead raising ValueError
interrupting the ingestion.
Introduced `INGEST_OVER_HTTP_ALLOW_NAN` plugin configuration, that is
set to False by default.
Testing Done: did add
`test_ingest_over_http_json_dumps_parameters_propagation` that verifies
`INGEST_OVER_HTTP_ALLOW_NAN` configuration propagation to `json.dumps`
> vdk-ingest-http: configurable allow JSON float NaN capability

- .gitlint
- .pre-commit-config.yaml
- cicd/build.sh
- projects/vdk-control-cli/cicd/build.sh
- projects/vdk-control-cli/requirements.txt
- projects/vdk-core/cicd/build.sh
- projects/vdk-core/requirements.txt
- projects/vdk-heartbeat/requirements.txt
- projects/vdk-plugins/build-plugin.sh
- projects/vdk-plugins/plugin-template/requirements.txt
- projects/vdk-plugins/vdk-csv/requirements.txt
- projects/vdk-plugins/vdk-greenplum/requirements.txt
- projects/vdk-plugins/vdk-impala/requirements.txt
- projects/vdk-plugins/vdk-ingest-http/requirements.txt
- projects/vdk-plugins/vdk-kerberos-auth/requirements.txt
- projects/vdk-plugins/vdk-plugin-control-cli/requirements.txt
- projects/vdk-plugins/vdk-postgres/requirements.txt
- projects/vdk-plugins/vdk-server/requirements.txt
- projects/vdk-plugins/vdk-snowflake/requirements.txt
- projects/vdk-plugins/vdk-sqlite/requirements.txt
- projects/vdk-plugins/vdk-test-utils/requirements.txt
- projects/vdk-plugins/vdk-trino/requirements.txt
Following common standard for our commit messages makes it easier to
track changes, to automate releases notes. This arised recently when
creating release notes for
https://github.com/vmware/versatile-data-kit/releases/tag/0.2 and there
were some unformatted titles.
See all rules in https://jorisroovers.com/gitlint/rules/
Added to some of the standard hooks
(https://github.com/pre-commit/pre-commit-hooks) with new rules:
- id: requirements-txt-fixer
- id: detect-private-key
- id: fix-byte-order-marker
Testing Done: this commit , also tried to commit with bad title and it failed.
> versatile-data-kit: update pre-commit hook to check git messages

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/cli_run.py
Clarify better the description. It was missing an example for using
arguments
> vdk-core: clarify run descriptions on --arguments option

- README.md
As our public Slack workspace is being deprecated in favour of
a channel on the CNCF workspace, the link in the project's
README must be corrected.
> versatile-data-kit: Fix Slack channel link

- projects/vdk-plugins/vdk-kerberos-auth/requirements.txt
- projects/vdk-plugins/vdk-kerberos-auth/setup.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/minikerberos_authenticator.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/vdk_kerberos_client.py
Issues were noticed with python >3.7 with requests-kerberos configured
hostname. The minikerberos dependency was pinned to 0.1.0 - due to
functional changes introduced in later versions. We need to upgrade to
the latest, so we solve issues fixed in later dependency versions.
Unpinned minikerberos and requests-kerberos versions, using effectively:
minikerberos            0.2.17
requests-kerberos       0.14.0
Introduced VdkAioKerberosClient implementation, based on minikerberos
AIOKerberosClient, that patches two issues marked with a comment.
We will elaborate further on potentially contributing the fixes back to
minikerberos.
Testing Done: did install locally and run an authentication successfully
using a keytab and KDC server available.
> vdk-kerberos-auth: upgrade minikerberos and requests-kerberos to latest

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_context.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input.py
- projects/vdk-core/tests/functional/run/jobs/job-name-directory/1_step.py
- projects/vdk-core/tests/functional/run/test_run_job_name_directory.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/test_input_job_name_directory.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/test_substitute_query_params.py
The IJobInput get_name and get_job_directory methods were not
implemented. Yet, we need to utilize those capabilities.
Extended JobInput instantiation performed by job_context.py.
Since modifying the JobInput constructor parameters, did unify with
JobContext constructor params convention (since params matching).
Testing Done: added unit tests for name and job directory propagation;
added functional test for verifying the name and directory retrieved;
adjusted test_substitute_query_params.py to extended JobInput params.
> vdk-core: JobInput get_name and get_job_directory implementation

- projects/vdk-plugins/vdk-snowflake/.plugin-ci.yml
- projects/vdk-plugins/vdk-snowflake/setup.py
Support for Python 3.10 was disabled due to the fact that the
python-snowflake-connector had not been updated to support it.
It has been now so we can enable support for vdk-snowflake as well.
> vdk-snowflake: Enable support for Python 3.10

- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
job_path is shorter version to get the jobs path in test in vdk-core
> vdk-core: refactor test to use job_path method

- projects/vdk-core/src/vdk/api/job_input.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input.py
- projects/vdk-core/tests/functional/run/jobs/job-with-args/2_python_step.py
- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
The documented order is that get_property API is lower priority over
get_arguments API. But it was not working, properties were taking
precedence instead. This was not well explained in execute_query API as
well.
This was fixed in this change and new tests are added.
Testing Done: extended functional tests.
> vdk-core: ensure sql args are subsituted in correct priority

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli_impl.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_deploy.py
Currently we cannot create new deployment and at the same time enable it
or set other vdk version in a single operation. This means we have to do
it in two different cli calls which may create race condition (where job
deployment starts with previous configuration before new is applied)
In this change we enable passing --vdk-version and --enabled when
creating deployment
with vdk deploy --create e.g
```
vdk deploy --create --vdk-version 1.2 --disabled
```
would create a new deplloyment which uses vdk version 1.2 and is
disabled.
Testing Done: automated tests included
> vdk-control-cli: set vdk version and enabled when deploying new job

- projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/ingest_to_trino.py
- projects/vdk-plugins/vdk-trino/tests/jobs/test_ingest_to_trino_job/10_ingest_to_trino.py
- projects/vdk-plugins/vdk-trino/tests/test_ingest_to_trino.py
vdk-trino ingestion was failing if `send_object_for_ingestion` is passed
value with type bool (as it was trying to cast it as if it's stirng.
Error was
"We could not convert the value to that type. Error is bool cast accept
only True/true/False/false values."
Testing Done: unit tests covered the new case
> vdk-trino: fix ingesting value with bool type failing

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
- projects/vdk-heartbeat/tests/vdk/internal/test_job_controller.py
Currently, if for some reason the `end_time` field of the execution object
is not a string (for example, the value is `None`), the `datetime.fromisoformat()`
method throws an exception and fails the heartbeat test.
This change introduces an explicit conversion of the value to string and adds
logging for what the error is along with indication that the heartbeat will fail.
Testing Done: Unit tests added.
> vdk-heartbeat: Handle execution end_time not string

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/hearbeat.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
When vdk-heartbeat is run with a configured vdk version
(VDK_HEARTBEAT_DEPLOY_JOB_VDK_VERSION) sometimes the cron job
manages to start an execution before actually setting the
deployment vdk_version. This happens because vdk_version is
set with a separate update deployment
call (function enable_deployment_and_update_vdk_version)
after the deployment was ready.
Move setting vdk_version in the create deployment command.
Testing Done: locally tested vdk-heartbeat against demo
control service with set VDK_HEARTBEAT_DEPLOY_JOB_VDK_VERSION
and observed that all execution pods used the specified
vdk version image.
> vdk-heartbeat: Fix initial job executions with specific vdk version

- projects/vdk-plugins/vdk-server/src/vdk/plugin/server/installer.py
The check if the service is up was using bad URL (which was returning
404) so `vdk server -s` is always returning that it is down
Testing Done: installed locally vdk server (`vdk server -i`) and check
its status was correctly returned with `vdk server -s`
> vdk-server: bugfix in running status check

- projects/vdk-control-cli/requirements.txt
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/execute.py
- projects/vdk-core/setup.cfg
- projects/vdk-core/src/vdk/internal/builtin_plugins/version/new_version_check_plugin.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/version/test_new_version_check_plugin.py
Currently, Versatile Data Kit uses click version 7.X in vdk-core and
vdk-control-cli, due to an issue of flag values not being converted to
enum, but rather to string.
This change adopts click 8.X and fixes the issues with click flag values by
always using strings and string representations of enum values where comparisons
are needed.
> [vdk-core][vdk-control-cli] Adopt click version 8.0

- projects/vdk-control-cli/setup.cfg
Did notice a conflict:
```
The conflict is caused by:
vdk-control-cli 1.2.494451234 depends on click==7.*
vdk-core 0.1.494451234 depends on click==8.*
```
A follow-up to
https://github.com/vmware/versatile-data-kit/pull/769/
Updated a pinned version from 7.* to 8.*
Testing Done: ci/cd
> vdk-control-cli: Adopt click version 8

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_kubernetes_authenticator.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
what: Added new properties to the helm chart as requested here:
https://github.com/vmware/versatile-data-kit/pull/755#discussion_r820856704
The new properties expose kerberos authentication configuration properties
in the helm chart which are propagated to control-service.
why: We are introducing a new KerberosAuthProvider in control-service
and we need to expose configuration properties through the helm chart.
testing: Deployed on local minikube cluster. Made sure secret is created
and populated with correct files. Inspected control-service pods, made sure
the new env variables are present and that secrets exist.
> [helm-chart]: add kerberos auth properties to helm chart

- specs/NNNN-template/README.md
- specs/README.md
As we are implementing more complex features we need a clear and easy
process to make feature proposals.
Overall the goals of the VDK Enhancement Proposal specs are: 
- To help future (and current) contributors understand what is being done and why is it being done this way 
- To help provide a better quality product by having peer review so that potential problems and inconsistencies are caught early.
- To help contributors develop their ideas into working solutions faster and easier by following a template on what questions they need to answer. 
Here we are adding a spec template. It is heavily influenced by VMware
development best practices and [Kubernetes
KEPs](https://github.com/kubernetes/enhancements/tree/master/keps/NNNN-kep-template)
and [Python …
> vdk: add VDK enhancement proposal (VEP) spec template

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
To take advantage of the automatic jobs cleanup afforded by
the TTL Controller, we need to the the TTLAfterFinished setting
to some appropriate value. Here, we've chosen 1 hour.
Testing done: TBD
> control-service: Set TTLAfterFinished period for K8s CronJobs

- projects/vdk-plugins/vdk-kerberos-auth/README.md
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/kerberos_configuration.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/kerberos_plugin.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/minikerberos_authenticator.py
- projects/vdk-plugins/vdk-kerberos-auth/tests/conftest.py
- projects/vdk-plugins/vdk-kerberos-auth/tests/test_kerberos.py
vdk-control-cli commands also may require Kerberos authentication so
here we are adding support. Currently, we only authenticate during vdk
run (part of initialize_job). But with support for Kerberos for the
Control Service we'd need it for all operations. E.g `vdk properties`
Now authentication is always attempted as long as it's explicitly
enabled (KRB_AUTH is set to some valid value). 
There's new flag "KRB_AUTH_FAIL_FAST" (false by default) 
which would cause the plugin to fail if auth fails but otherwise only a warning would be logged. 
It's necessary because only small subsets of features would use kerberos. 
And vdk should work even if those feature do not.
Alternatives considered: 
I was considering adding a new decorator/annotation to vdk-kerberos-auth 
which "users" can use to …
> vdk-kerberos-auth: support kerberos auth for all CLI commands

- .pre-commit-config.yaml
The Black styling pre-commit hook 22.1.0 which we use has an
incompatibility with click 8.1.0 as described here -
https://github.com/psf/black/issues/2964
This issue can be seen in this pre-commit log - 
https://results.pre-commit.ci/run/github/387724608/1648974199.QWpiWQJSSm6aM3PRKPdqMg
in this PR - 
https://github.com/vmware/versatile-data-kit/pull/778
> versatile-data-kit: Fix pre-commit Black hook

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/MockKubernetes.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java
Currently, builder job is based on Kaniko and requires root privileges.
However, it runs with the default security context of a particular K8S cluster
since Control Service does not set user and group to K8S Job.
* spec.template.spec.securityContext.fsGroup: 0
* spec.template.spec.securityContext.runAsGroup: 1000
* spec.template.spec.securityContext.runAsUser: 1000
> control-service: builder job configurable security context

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/notification/EmailNotification.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/notification/EmailNotificationTest.java
This change aims to fix the NPE when null is passed to EmailNotification.concatAddresses().
> control-service: fix concatAddresses NPE

- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Converted builder security context properties to String, because "if 0"
returns false and as a result the property is not present in control
service envs.
Testing Done: helm template
> control-service: fix builder security context

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_plugin.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/dimension/scd1/README.md
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/dimension/scd2/README.md
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/snapshot/README.md
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/versioned/README.md
The "load/dimension/scd2" is simple implementation of SCD2 which is less
optimial and flexible than "load/versioned" which is the recommendd one
to use.
The "versioned" template correspond to scd2 in vdk-trino plugin for
example (vdk-trino/src/vdk/plugin/trino/templates/load/dimension/scd2) .
And there there's no scd2_simple implementation at all.
So this PR is changing the name of "load/dimension/scd2" to
"scd2_simple", It's keeping an alias (alternative) name of
"load/dimension/scd2" for backwards compatible reasons.
It's also setting as main name of load/versioned to be "scd2" (which is
the one used in vdk-trino)
Also in vdk-trino Periodic snapshot template is called
"periodic_snapshot" so renaming it to match.
Testing Done: automated tests
Signed-off-by: Antoni Ivanov …
> vdk-impala: unify names of templates betwen trino and impala

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/MockKubernetes.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java
Currently, the builder job is based on Kaniko and requires root privileges.
In some cases, Pod Security Policy can be configured based on namespace and service account.
However, Control Service does not provide the ability to set a service account to the Builder Job.
This change aims to provide an ability to set a service account through the Helm Chart.
spec.template.spec.serviceAccountName: "account_name"
Testing done: unit tests and helm template
> control-service: configurable builder job service account

- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java
The unit tests have been failed due to the wrong expected type. They
expect String but the value is NULL.
> control-service: fix job builder unit tests

- CONTRIBUTING.md
The coding stanard is not easy to find. And it's generally recommended that it's included in contributing.md
> versatile-data-kit: Update CONTRIBUTING.md with links to coding standard

- projects/vdk-plugins/airflow-provider-vdk/tests/hooks/test_vdkhook.py
- projects/vdk-plugins/airflow-provider-vdk/vdk_provider/hooks/vdk.py
This change implements a method for the VDK connection hook which
allows a user to check the status of a job execution in the VDK
control-service. It also implements a method which allows a user to
download the stored job execution logs for a particular execution.
Testing done: locally tested and verified that the correct object
and correct log string are returned, implemented 2 unit tests
> airflow-provider-vdk: Job execution status and logs method

- specs/vep-554-apache-airflow-integration/README.MD
As part of the development of the Versatile Data Kit Airflow Provider, we need to
ensure that all connections to the Control Service are properly authenticated. For
this to happen, we need to define the authentication mechanisms and flows that would
be used.
This change extends the `Security and Permissions` section of the enhancement proposal
to include more details on how authentication would be facilitated in the Airflow Provider.
Testing Done: Documentation change, no testing needed.
> VEP-554: Extend Security and Permissions section

- projects/vdk-plugins/vdk-control-api-auth/.plugin-ci.yml
- projects/vdk-plugins/vdk-control-api-auth/README.md
- projects/vdk-plugins/vdk-control-api-auth/requirements.txt
- projects/vdk-plugins/vdk-control-api-auth/setup.py
- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/control_api_auth_plugin.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_vdk_auth_plugin.py
With the increase in plugins requiring authentication arises the need
for a dedicated utility that provides such functions.
This change introduces the initial structure of a library plugin, whose
purpose is to facilitate authentication with 3-rd party services.
Testing Done: None
> vdk-plugins: Introduce vdk-control-api-auth plugin

- projects/vdk-plugins/airflow-provider-vdk/tests/sensors/test_vdksensor.py
- projects/vdk-plugins/airflow-provider-vdk/vdk_provider/sensors/vdk.py
This change lays out the initial structure for the VDK asynchronous
operator, a.k.a. the VDKSensor. The purpose of this sensor is to
routinely poke the VDK control-service and check the status of a
particular job, so that its completion/failure can trigger some
activity in an Airflow DAG, i.e. trigger another job.
> airflow-provider-vdk: VDKSensor initial structure

- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_cursor.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/connection/test_managed_cursor.py
why: Users requested clearer examples on how long given operations took: 
"- In concrete case problems was with SQL query , it would be nice if we can
print profile details (especially if query fails)"
what: Added new log statements that show how long an SQL query took.
testing: Added unit tests.
> vdk-core: print query duration

- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
- projects/vdk-core/tests/functional/ingestion/jobs/test-ingest-bad-payload-job/1_ingest_step.py
- projects/vdk-core/tests/functional/ingestion/test_payload_verification.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_base.py
Ingestion allows pre-processing payloads. If the payload
is curated during pre-processing, currently, verification
would fail.
Verify payload after pre-processing it, since this
pre-processing might be responsible for making it serializable.
Also, add VDK_ prefix to configs so that ingestion pre/post
processors are properly initialized.
Tested by: locally run ingestion job which curates json
during pre-processing
> vdk-core: Verify payload after pre-processing it

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_log_config.py
This change makes it so an cloud executions of jobs can have an
endpoint configured, where logs will be sent automatically using
SysLog.
Testing done: ran job with a configured endpoint and observed logs
in the endpoint
> vdk-core: Allow logs to be sent to an endpoint using SysLog

- examples/README.md
The examples directory in git contains generally the source code. And the examples tutorial/articles are written in a wiki currently. 
Signed-off-by: Antoni Ivanov's avatarAntoni Ivanov <aivanov@vmware.com>
> versatile-data-kit: link examples wiki in the git examples 

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
- projects/vdk-heartbeat/tests/vdk/internal/test_job_controller.py
We've noticed an occasional error occurs, applying the stack trace:
File "/opt/buildenv/lib/python3.7/site-packages/vdk/internal/heartbeat/
job_controller.py", line 383, in check_job_execution_finished
self._datetime_from_iso_format(str(e["end_time"])) for e in
execution_list
TypeError: '>' not supported between instances of 'NoneType' and
'datetime.datetime'
The error seems to reproduce in case execution end_time is not yet
populated, and `max()` is attempting to compare datetime with NoneType.
The fix includes filtering out any empty end_times, so that we rely on
statuses and end_times populated only.
A broader Exception is added for handling during datetime conversion,
like a preventive step.
Testing done: did retrieve the Execution API response, did reproduce
same TypeError error via …
> vdk-heartbeat: null datetime conversion fix

- projects/vdk-core/src/vdk/internal/builtin_plugins/version/new_version_check_plugin.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/version/test_new_version_check_plugin.py
A bug detected when using custom new-version-check-plugin
configurations:
```
config_builder.set_value(key="PACKAGE_INDEX",value="https://some.repo")
config_builder.set_value(key="PACKAGE_NAME",
value="some-package-upgraded-to-latest-locally")
config_builder.set_value("VERSION_CHECK_PLUGINS", False)
```
That results in false-positive yet package-empty
upgrade message displayed:
```
************************************************************************
New version for   is available.
Please update to latest version by using:
pip install --upgrade-strategy eager -U   --extra-index-url
https://some.repo
************************************************************************
```
Changed `_check_version` method to `_print_new_version_message`,
matching the purpose described in its pydocs. …
> vdk-core: new version check built-in plugin false positive fix

- projects/vdk-plugins/vdk-control-api-auth/README.md
- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/authentication.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_api_token_auth.py
As part of the ongoing work to extract the authentication login of
Versatile Data Kit into a stand-alone library and make it available
to all components (core and plugins) to use, we need to ensure that
the interface surface is as generic as possible.
This change introduces an`Authentication` class, which will act as
the entry point for using the library and authenticating.
Additionally, the api token authentication flow from vdk-control-cli
is also adapted and added to vdk-control-api-auth.
Testing Done: Unit tests.
> [vdk-plugins] vdk-control-api-auth: Add api-token flow

- specs/vep-554-apache-airflow-integration/README.MD
With a previous commit, the pre-commit hooks had corrupted the
markdown of the document, and some links were not properly formatted.
This change fixes the broken markdown links, so they are formatted as
expected.
Testing Done: Documentation change.
> vep-554: Fix markdown links

- .pre-commit-config.yaml
If users run pre-commit hook locally they need python. Due to
https://github.com/pre-commit/pre-commit/issues/1375 it seems the
pre-commit hooks is failing if there's no python3.7 because we've
specified in black to use it. We are loosing the version to python 3.7
so that it's eaiser to develop with any version
Testing Done: ran git commit in docker container using only python 3.9
and saw (after the change) it no longer fails.
Signed-off-by: Antoni Ivanov <aivanov@vmware.com>x
> versatile-data-kit: allow commit with any newer version of python

- projects/vdk-core/src/vdk/api/data_job.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/standalone_data_job.py
- projects/vdk-core/tests/functional/run/test_run_standalone_data_job.py
- projects/vdk-core/tests/functional/run/util.py
The PR contains a WIP implementation of a vdk-core extension that addresses #791
`StandaloneDataJob` - a context manager that:
- can be instantiated from code rather than via the VDK CLI
- can be run without needing any data job files
- gives access to an instantiated `job_input` object before it is finalized
Example usage:
```
with StandaloneDataJobFactory.create(datajob_directory) as job_input:
#... use job_input object to interact with SuperCollider
```
> vdk-core: New feature: StandaloneDataJob

- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/authentication.py
- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/autorization_code_auth.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_authorization_code_auth.py
As part of the ongoing work to build a stand-alone authentication plugin
library, which is to be used by all components of Versatile Data Kit that
rely on authentication, we need to move and generalize the existing logic
from vdk-control-cli.
This change introduces the authorization code flow as defined in
https://datatracker.ietf.org/doc/html/rfc6749#section-4.1 The implementation
of this flow for the purposes of Versatile Data Kit also relies on the use
of Proof Key for Code Exchange or pkce.
Testing Done: Unit tests.
> [vdk-plugins] vdk-control-api-auth: Add authorization code flow

- projects/vdk-plugins/vdk-control-api-auth/.plugin-ci.yml
After finalizing the bulk of the work on the stand-alone authentication
plugin library, it is necessary to release the library so it can be used
by the various components of Versatile Data Kit
This change enables the release step of the CI/CD for the vdk-control-api-auth
package.
> [vdk-plugins] vdk-control-api-auth: Enable plugin release

- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/autorization_code_auth.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_authorization_code_auth.py
When parsing the query parameters from the redirect_url in the
authorization code authentication flow, we converted the key of
the parameter to bytes, which was causing TypeErrors due to missing
encoding. This regression was not caught by the unit tests.
This change fixes the regression by using plain strings as keys
and removing any conversions to bytes.
Additionally, unit test was fixed and extended to catch possible
future regressions.
Testing Done: Unit tests
> [vdk-plugins] vdk-control-api-auth: Fix query key type

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli_impl.py
When successfully deploying a job, vdk-control-cli
prints a command which can be used to check whether
the deployment version was successfully updated.
However, the printed command included the team name
without quotes around it, which can be an issue as
team names can have empty spaces in them, which meant
the command gets parsed wrongly and fails.
Command used to look like:
```
vdk deploy --show -t team_name -n job_name
```
Now it looks like:
```
vdk deploy --show -t 'team_name' -n 'job_name'
```
> vdk-control-cli: Fix command printed on successful deploy

- projects/vdk-core/tests/vdk/internal/builtin_plugins/connection/test_connection_router.py
We have a unit test that checks the raw (or native) connection is being
saved properly - but the test was buggy since they are qual in a sense
they have the same attribute values (as there's only one "is_valid") .
But we care if it's the same instance. So we switch to "is"
Testing Done: After changing == to "is" ran the test and it failed (as
it should) and then fix the test.
> vdk-core: fix buggy (false positive) connection unit test

- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/auth_config.py
- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/auth_exception.py
- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/authentication.py
- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/autorization_code_auth.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_api_token_auth.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_authorization_code_auth.py
[vdk-plugins] vdk-control-api-auth: Redefine exceptions
Currently, we have one top-level exception class, `VDKAuthException` which
is invoked every time some error occurs during the authentication process.
This approach works in general, but a downside is that it does not allow for
more granular error handling.
Additionally, if a user wants to integrate their project with the library,
and they want to implement different behaviours based on different errors,
they would need to parse the error message, which may not be considered a
good practice.
This change introduces a new exception hierarchy, which defines child exceptions
to the top-level `VDKAuthException` and facilitates more robust error-handling,
both at the plugin level, as well as by client applications that integrate with
the …
> New VDK Auth exceptions

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/login_group/login.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/login_group/test_login.py
After the introduction of new exception types in the
`vdk-control-api-auth` plugin, more granular exception handling
is now possible.
This change adopts the new exception types in `vdk-control-cli`,
and removes unnecessary error message parsing.
Additionally, the exit status code when authentication failes was
changed from 0 to 1 to better reflect the fact that something unexpected
has happened.
Testing Done: Unit tests
> vdk-control-cli: Adopt new auth exceptions

- projects/control-service/cicd/.gitlab-ci.yml
- projects/vdk-heartbeat/README.md
The vdk-heartbeat release documentation required a merge to master, for
triggering the release process. However, the control-service CI/CD that
depends on vdk-heartbeat, does not consider new vdk-heartbeat versions.
Also, changing pipelines_control_service `version.txt` does not trigger
release nor rebuild, for example 
https://github.com/vmware/versatile-data-kit/pull/814
Added a comment to control-service `.gitlab-ci.yml` to trigger an IT
image update. Documented a workaround in `README.md` until automated.
Testing Done: will monitor the pipelines for image rebuild
> vdk-heartbeat: pipelines-control-service-integration-tests image rebuild

- projects/vdk-plugins/vdk-test-utils/tests/test_vdk_test_utils.py
I had to disable tests in order to merge PR that chagned both vdk-core
and vdk-test-utils.
Now I am enabling them back.
> vdk-test-utils: enable back tests

- projects/vdk-plugins/airflow-provider-vdk/setup.py
- projects/vdk-plugins/airflow-provider-vdk/tests/hooks/test_vdkhook.py
- projects/vdk-plugins/airflow-provider-vdk/tests/hooks/test_vdkhook_auth.py
- projects/vdk-plugins/airflow-provider-vdk/tests/operators/test_vdkoperator.py
- projects/vdk-plugins/airflow-provider-vdk/tests/sensors/test_vdksensor.py
- projects/vdk-plugins/airflow-provider-vdk/vdk_provider/hooks/vdk.py
- projects/vdk-plugins/airflow-provider-vdk/vdk_provider/operators/vdk.py
- projects/vdk-plugins/airflow-provider-vdk/vdk_provider/sensors/vdk.py
After the release of the `vdk-control-api-auth` plugin, which acts as
the de-facto authentication package for Versatile Data Kit, we no longer
need to depend on `vdk-control-cli` and all its unnecessary dependencies.
With this change, we adopt the `vdk-control-api-auth` package and its
authentication capabilities, and drop any dependency on `vdk-control-cli`.
Testing Done: Unit tests.
> [vdk-plugins] airflow-provider-vdk: Adopt auth plugin

- projects/vdk-plugins/README.md
We were not mentioning at all how you can do managed connection extensions/plugins in teh main plugin doc. 
Signed-off-by: Antoni Ivanova <aivanov@vmware.com>
> vdk-plugins: Add Managed Database Connection cycle plugin

- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
In the IngesterBase class, we currently pass `destination_table` to the
call to `_queue_payload_for_posting` in cases when the objects queue is empty.
However, at this point, the destination_table is not defined, which causes an
UnboundLocalError to be raised.
This change fixes the issue by replacing `destination_table` with `current_destination_table`
(set to None by default) which is defined before the call to `_queue_payload_for_posting`.
Testing Done: All existing tests pass
> vdk-core: Fix destination_table referenced early

- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_base.py
As part of https://github.com/vmware/versatile-data-kit/pull/864, a change was
made that fixes an issue with destination_table referenced before assignment in
case the `_objects_queue` of the `IngesterBase` class is empty. However, the change
was merged without any tests.
This change introduces a unit test that verifies that there are no regressions.
Testing Done: Unit test introduced.
> vdk-core: Add unit test for destination_table in empty queue

- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/connection_hooks.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/execution_cursor.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_cursor.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/proxy_cursor.py
- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
The current design was allowing users to access directly native cursor
unwrapped which defeat the purpose of being on data/control path of
queries as Iva correctly pointed out in earlier review.
It was necessary because user need to be able to invoke native vendor
specific methods (like get_profile of impala cursor).
But there's better approach where both users are allowed to call vendor
specific methods yet keep certain methods (like execute) curated/wrapped
by VDK. It's by introducing ProxyCursor (which is moving some
functionalith of ManagedCursor).
Testing Done: existing tests passed. I added explicit functional test to
test the proxying functionality
> vdk-core: hide native cursor from execute hook

- README.md
As suggested by Gabriel (https://github.com/vmware/versatile-data-kit/pull/877#pullrequestreview-1018547035): change the readme to change the logo based on whether the user has dark or light mode enabled, following: https://dev.to/arnavkr/using-darklight-mode-specific-images-in-github-markdown-3iln
Testing Done:  change theme and verified https://github.com/vmware/versatile-data-kit/tree/person/aivanov/images-readme looks appropriate
> versatile-data-kit: update logo for dark mode

- CONTRIBUTING.md
Update the first part of this file according to the template provided. 
Here is the template: https://github.com/vmware/.github/blob/main/CONTRIBUTING.md
> Add intro part to contributing.md from the template

- projects/vdk-plugins/airflow-provider-vdk/vdk_provider/hooks/vdk.py
In the Airflow UI, users can create new connections manually from the Admin section. When
done this way a web form is shown, where they can fill in host, port, username, password,
etc. needed to establish a new connection to third-party services.
The fields shown in the web form can be customised by overwriting the `get_ui_field_behaviour()`
method from the **BaseHook**. In the vdk airflow provider, we do some field relabeling to make
the user experience more consistent with our project.
This, however, caused some issues, as apperantly the dictionary where the changes to the connection
fields' behaviour is specified, needs to have a `hidden_fields` key/value pair.
This change introduces a `hidden_fields` key/value pair, and we use it to hide the schema field, which
is not really used by …
> [vdk-plugins] airflow-provider-vdk: Add hidden fields to VDK Connection

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/common_group/default.py
The set-default and reset-default commands do not print
any output when invoked. This PR adds a printed message
for both to ensure the user that the commands have been
executed successfully.
Testing done: tested locally
> vdk-core: Add printed output to set-default and reset-default

- projects/vdk-plugins/vdk-trino/tests/docker-compose.yml
Recent change in trino library broke our tests -
After https://github.com/trinodb/trino/issues/9129  trino would fail
`drop view if not exists` query if table with that name exists instead
of silently proceeding.
which is problem for us since our tests seem to rely on us they execute
both drop view and drop table to make sure a table or view is deleted.
So now I am pinning to old version of trino to hopefully fix the issue
as a quick workaround. Will create separate ticket to fix it in a way
that works against latest version of trino.
Testing Done: this PR CICD :)
> vdk-trino: fix broken tests

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/list.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/properties.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/show.py
`vdk show`, `vdk properties` and `vdk list -m` were considered
experimental so that's why they are hidden. But they've been used enough
in VDK installations that it is no longer true.
Testing Done: They show in `vdk --help` and `vdk list --help`
> vdk-control-cli: remove hidden flag for CLI commands

- projects/vdk-control-cli/cicd/build.sh
Change build script to always try to upgrade to latest version to ensure
that local environment is kept automatically up to date and avoid issues
where things work locally and not so well in CI
Testing Done: ./cicd/build.sh
> vdk-control-cli: use latest dependencies version during build

- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/minikerberos_authenticator.py
- projects/vdk-plugins/vdk-kerberos-auth/tests/jobs/test-job/20_async_test.py
The minikerberos authenticator relies on an async kerberos client to speed up some of its
processes. This client uses `asyncio.run()` to execute async operations. As can be seen from the source
code of asyncio, https://github.com/python/cpython/blob/3.10/Lib/asyncio/runners.py, the `run()` method
creates a new event loop and sets it as the [default loop](https://github.com/python/cpython/blob/3.10/Lib/asyncio/runners.py#L41).
When all async operations are finished, the loop it terminated and all tasks are cleaned. This is fine
in general, as long as other components don't rely on the main event loop.
If they do, however, we could end up in a situation, where the kerberos plugin closes the asyncio
main event loop, and breaks the other components that rely on the same thread.
To avoid …
> [vdk-plugins] vdk-kerberos-auth: Separate async event loop

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
Due to small bug in defining LOG_LEVEL_VDK the description was not
showin in `vdk config-help`
Testing Done: Ran `vdk config-help` and saw it shows up correctly
> vdk-core: show log_level_vdk in help

- projects/vdk-core/src/vdk/internal/builtin_plugins/termination_message/file_util.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/termination_message/writer.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/termination_message/test_writer.py
what: termination message plugin now overrides the previous message.
why: Some data jobs that make use of the [Standalone Data Job](https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-core/src/vdk/internal/builtin_plugins/run/standalone_data_job.py) end up with double termination message, e.g.,
'{"vdk_version": "0.3.572339461", "status": "Success"}{"vdk_version": "0.3.572339461", "status": "Success"}'
This confuses the Control Service, which therefore classifies the execution as Platform Error, even if the job is executed successfully.
testing: added unit tests
> vdk-core: termination message now idempotent

- projects/vdk-core/src/vdk/api/plugin/core_hook_spec.py
- projects/vdk-core/src/vdk/internal/cli_entry.py
The hook was always returning exit code 1, no matter if exception was
successfully handled or not.
Elaborated the vdk_exception hookspec API documentation on exit code
expectations. Fixed the return status to 0 in case exception was
successfully handled.
Testing Done: ci/cd
> vdk-core: vdk_exception hook exit code fix

- projects/control-service/projects/pipelines_control_service/src/main/resources/application-prod.properties
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
what: Added default values for env variable that was causing the control-service to crash on startup, because even though the authentication/authorization is disabled the variables are used in a bean (constructor) initialization and it crashes on spring boot initialization (before it enters our code). The env variable is found in some of our application.properties files, but it varies between prod, testing etc (not all have default values) and there are comments that say setting it is mandatory.
why: the vdk-server's vdk server --install command was failing.
testing: Tested locally with pip install -e option of a locally editable vdk-server plugin. Server was failing to start without the variable. After the change - server starts up normally.
Signed-off-by: Momchil Zhivkov …
> control-service: fix vdk-server startup issues

- projects/vdk-plugins/vdk-server/src/vdk/plugin/server/installer.py
what: Added a missing env variable that was causing the control-service to crash on startup, because even though the authentication/authorization is disabled the variable is used in a bean (constructor) initialization and it crashes on spring boot initialization (before it enters our code). The env variable is found in some of our application.properties files, but it varies between prod, testing etc (not all have default values) and there are comments that say setting it is mandatory.
why: the vdk-server's vdk server --install command was failing.
testing: Tested locally with pip install -e option of a locally editable vdk-server plugin. Server was failing to start before the change. After the change - server starts up normally.
> vdk-server: fix for vdk server crashing on startup

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/execution_results.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/standalone_data_job.py
- projects/vdk-core/src/vdk/internal/cli_entry.py
- projects/vdk-core/src/vdk/internal/core/errors.py
- projects/vdk-core/tests/functional/run/test_run_errors.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_router.py
There was an issue, where a particular exceptions were not propagating
to the respective except(catch) clauses. The process was suddenly
blindly exiting with code 1.
Did troubleshoot the flaw to vdk-core's error framework, where
BaseVdkError was extending ClickException without any purpose
known/documented.
That was causing all the BaseVdkError-based DomainErrors like
VdkConfigurationError, UserCodeError, PlatformServiceError, and so on,
to stop propagating to handlers. Did fix the errors framework design
flaw.
Testing Done: added the vdk_exception exit code test coverage,
that relies on proper exception propagation and handling; ci/cd
> vdk-core: BaseVdkError exception propagation flaw fix

- projects/vdk-plugins/vdk-server/src/vdk/plugin/server/installer.py
Currently, due to the fact that the control service's helm chart uses some
outdated APIs, `vdk server --install` cannot complete successfully, and throws
the below error:
```
Installing Control Service in Kind cluster...
-error: Stderr output: W0613 14:09:42.750230   43383 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
error: W0613 14:09:42.812327   43383 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
error: W0613 14:14:43.166567   43383 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
error: Error: INSTALLATION FAILED: release vdk …
```
> [vdk-plugins] vdk-server: Pin kubernetes API version

- support/gitlab-runners/values.yaml
what: We intend to increase the limits to our cicd containers.Updated values.yaml file. The script "install-runners.sh" has to be manually triggered for changes to take effect.
why: Control Service Integration Tests have been failing with OOM errors. Although this doesn't directly update the values
it servers as a reference point for future changes.
testing: n/a
> cicd: increase memory limits for cicd runner

- README.md
Add a link to Slack inviter (https://communityinviter.com/apps/cloud-native/cncf) to make it easier for people to join CNCF slack. 
Otherwise, they need to read the docs and it becomes more complex.
> versatile-data-kit: make easier slack instructions

- projects/vdk-core/src/vdk/internal/builtin_plugins/job_properties/inmemproperties.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_properties/properties_api_plugin.py
In case Control Service is not available, for demo purposes, it would be
good to be able to use some simple client so that jobs that stil use
properties would work.
To make it clear that it's not recommended for production (after all
properties are supposed to be used to store state, so in memory client
may be misleading) we write warning each  time write proerties is
called.
> vdk-core: add memory properties client

- projects/vdk-core/setup.cfg
- projects/vdk-core/src/vdk/api/plugin/connection_hook_spec.py
- projects/vdk-core/src/vdk/api/plugin/hook_markers.py
- projects/vdk-core/src/vdk/api/plugin/plugin_registry.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/execution_tracking.py
- projects/vdk-core/tests/functional/run/test_run_errors.py
- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_plugin.py
- projects/vdk-plugins/vdk-lineage/src/vdk/plugin/lineage/plugin_lineage.py
- projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_plugin.py
The 1.0 release of `pluggy` introduced a breaking change by
renaming its `callers` module to `_callers`. This has been
fixed by using the `HookCallResult` constant from
`vdk.api.plugin.plugin_registry` instead of
`pluggy.callers._Result` everywhere necessary, and amending
said constant to be either `pluggy.callers._Result` or
`pluggy._callers._Result` dynamically based on the version of
`pluggy` in the current Python env.
Also fixed a test which had `hookwrapper` set to True for some
reason inside its testing plugin.
Testing done: ran tests locally with both versions of pluggy, CICD
> vdk-core,vdk-impala,vdk-lineage,vdk-trino: Support for pluggy 1.0

- projects/vdk-plugins/vdk-impala/README.md
- projects/vdk-plugins/vdk-impala/requirements.txt
- projects/vdk-plugins/vdk-impala/setup.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_connection.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_lineage_plugin.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_plugin.py
- projects/vdk-plugins/vdk-impala/tests/conftest.py
- projects/vdk-plugins/vdk-impala/tests/functional/test_impala_lineage.py
Add support for calculating data lineage for jobs that execute SQL queries
against impala.
Lineage is calculated by examining the query plan of the executed query. The
query plan is accessible from the cursor that executed the query, hence no
additional load is present on the target query engine. As this is not very
official way to obtain the query plan there is a risk that this implentation
may break in future impala releases.However the only option was to execute
additional explain statements that would practically double the amount of
executed queries, which could be problematic for loaded environments. Lineage
is calculated only for successfully executed queries that have actually read
or written data from/to the underlying storage.
Implemented functional tests that verify the …
> vdk-impala: Add support for lineage in vdk-impala

- projects/vdk-core/src/vdk/api/plugin/plugin_input.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/impl/router.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/connection/test_connection_router.py
It is a common error where you can set db_default_type=sqlite but
because it's declared in the plugin as "SQLITE" we get error that no
such db connection type exists which is not true.
This PR changes it so that the db type check is not case sensitive
> vdk-core: make db_default_type case insensitive

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_lineage_plugin.py
- projects/vdk-plugins/vdk-impala/tests/impala_lineage_plugin_test.py
Add performance measurement logs that show how much time it takes to fetch the
query plan. This can be used to estimate potential impact on Impala for
calculating lineage. Also fixed a bug where lineage for select queries was not
generated.
Add debug logs for time taken to fetch query profile and the size of the query
profile itself.
Add support for None output table which enable lineage for select statements.
Add unit tests to to validate table name parsing behaviour.
Bug fix (non-breaking change which fixes an issue) and minor improvement.
Signed-off-by: Vladimir Petkov <petkovv@vmware.com>
> vdk-impala: Add performance logs

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/fluentdconfig_datajobs.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Currently, our helm chart supports Fluentd configuration only for the Control Service. 
This change aims to provide Fluentd configuration for Data Jobs.
Testing Done:
`helm template`:
```yaml
---
apiVersion: logs.vdp.vmware.com/v1beta1
kind: FluentdConfig
metadata:
name: pipelines-control-service-data-jobs-parser
namespace: data-jobs-ns
spec:
fluentconf: |
<filter **>
@type parser
key_name log
reserve_data true
remove_key_name_field true
<parse>
@type json
</parse>
</filter>
<match **>
@type elastic
</match>
---
```
> Fluentd integration for data jobs

- projects/vdk-plugins/vdk-ingest-http/src/vdk/plugin/ingest_http/ingest_over_http.py
Logging each payload at INFO is extremely verbose, we can have thousands
and thousands of payloads being sent. So it also slows down teh
ingestion.
> vdk-ingest-http: reduce verbosity of ingestion logs

- CONTRIBUTING.md
Remove the step that requires making extra bump of a version. It's unnecessary as we can record the version at the time of release as the one corresponding to the release.
It would have made some sense if we tagged the commit with the release but we do not do that for now , so it's just extra step
> versatile-data-kit: simplify release process

- projects/vdk-control-cli/setup.cfg
VDK supports pluggy 1.0 as well as older versions.
Testing done: cicd
> vdk-control-cli: Drop requirement pluggy to be 0.*

- README.md
People miss that they need first to join CNCF slack space. So I am making the instructions clears. 
Signed-off-by: Antoni Ivanov (aivanov@vmware.com)
> versatile-data-kit: update contact instructions

- projects/vdk-plugins/vdk-kerberos-auth/README.md
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/api/kerberos_client.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/kerberos_configuration.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/kerberos_ticket.py
We are adding support for Kerberos authentication in the Control REST
API . This is extending the support for the client to be able to make
authentication requests with kerberos.
This is part 1 adding KerberosClient "API" for the purpose of clients
using it to get Kerberos authentication header.
In a follow-up MR I will adopt it in vdk-control-cli
Testing Done: automated tests
> vdk-kerberos-auth: add KerberosClient for authenticating API calls

- projects/vdk-core/.gitlab-ci.yml
- projects/vdk-core/cicd/build.sh
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input_error_classifier.py
- projects/vdk-core/tests/functional/run/jobs/fail-job-indirect-library/1_step.py
- projects/vdk-core/tests/functional/run/jobs/fail-job-ingest-iterator/1_step.py
- projects/vdk-core/tests/functional/run/test_run_errors.py
In case the User code is indirectly responsible (yet closest to the
error in the stack trace), for example using a dependency incorrectly,
the error cause (vdk, or user code) is not recognized correctly.
See more details in https://github.com/vmware/versatile-data-kit/issues/1118 and https://github.com/vmware/versatile-data-kit/issues/580
Testing Done: added functional test covering the scenario
> vdk-core: fix error classification of vdk code

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_plugin.py
- projects/vdk-plugins/vdk-impala/tests/conftest.py
- projects/vdk-plugins/vdk-impala/tests/functional/template_regression_test.py
With the change in
https://github.com/vmware/versatile-data-kit/pull/1173 this caused the classification not to work properly.
Tests did not catch this because vdk-impala tests are not run on vdk-core release. 
I am thinking of how we can rework the classification logic to be more first class citizen. But that's a large effort than this story.
> vdk-impala: fix error classification in impala

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_log_config.py
To enable users to override logs per module, temporarily (e.g for
debugging or prototyping reasons to increase verbosity of certian
module).
The feature works similar to how spring level is specified
(-Dlogging.level.com.baeldung=TRACE)
Configruation is:
'log_level_module="my.module=INFO,my.second.module=debug"'
> vdk-core: add new configuration log_level_module

- projects/vdk-core/src/vdk/internal/builtin_plugins/termination_message/writer.py
- projects/vdk-plugins/vdk-plugin-control-cli/src/vdk/plugin/control_cli_plugin/execution_skip.py
Currently, we have an internal customer experiencing concurrent executions of the same data job. The issue is in the execution logic because of missing default values of the write_termination_message method.
Exception:
```
execution_skip.py:130  _skip_job_if_nec[id:moonshine-stage-cost-optimization-strategies-1663579200-qfxw2]- Error while checking for another data job excecution: write_termination_message() missing 2 required positional arguments: 'error_overall' and 'user_error' 
```
This change aims to fix the issue ASAP since the customer may have duplicate data because of it.
> vdk-core: added default values to write termination message method

- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_log_config.py
We want to fix intermittent failures in tests. Specifically the described in https://github.com/vmware/versatile-data-kit/issues/1177.
The underlying issue was that `test_log_plugin` was modifying the log level to warning. 
the test `test_run_dbapi_connection_no_such_db_type` relies on it being INFO to pass. 
There are two fixes to prevent this in the future
1. the log level is explicitly set at the start of the test `test_run_dbapi_connection_no_such_db_type`. 
2. in the test `test_log_plugin` we revert the start back to info at the end of it. 
Before my fix I was getting an error reasonably frequently during runs. 
After I added my fix in I ran the pipeline many more times and never encountered the error again. 
Bug fix (non-breaking change which fixes an issue) or a cosmetic …
> vdk-core: fix flakey test in test checking logs output

- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_connection_base.py
Occasionally, vdk may indicate that a query execution took 10 or 20 minutes, even though the DB back shows that the query was actually executes in seconds. This results in the DB backend issuing a timeout error and a job failure. Because it happens sporadically, it is hard to reproduce and debug locally.
This change adds a log message just before the result of a query is fetched, and should help better understand at which step the query execution hanged.
Testing done: Documentation change.
> vdk-core: Add log before query result fetch

- projects/control-service/cicd/.gitlab-ci.yml
Latest changes in Kubernetes have broken our KUBECONFIG which uses older version of API resource and we get errors like "invalid apiVersion "client.authentication.k8s.io/v1alpha1" (similar to https://github.com/aws/aws-cli/issues/6920)
I am upgrading things around to fix it.
Amazon EKS uses the `aws eks get-token` command, available in version 1.16.156 or later. Until now we used aws-iam-authenticator but it seems latest changes in Kubernetes do not work there. 
I have also regenerated the KUBECONFIG and updated in Gitlab CI Variables (using https://aws.amazon.com/premiumsupport/knowledge-center /eks-generate-kubeconfig-file-for-cluster/)
> control-service: fix integration tests

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobTerminationStatusIT.java
When the tests fails it would be nice to know what the actual value is and not just that it doesn't match.
Here we can see the error is not nearly descriptive enough
https://vmware-analytics.gitlab.io/-/versatile-data-kit/-/jobs/3130654022/artifacts/projects/control-service/projects/pipelines_control_service/build/reports/tests/integrationTest/classes/com.vmware.taurus.datajobs.it.DataJobTerminationStatusIT.html#testDataJobTerminationStatus(String,%20String,%20String)
Added extra details to the error message. 
> vdk-pipeline-control-plane: better error logging for transient error in tests

- projects/vdk-plugins/.plugin-common.yml
- projects/vdk-plugins/vdk-control-api-auth/.plugin-ci.yml
- projects/vdk-plugins/vdk-csv/.plugin-ci.yml
- projects/vdk-plugins/vdk-csv/tests/functional/test_csv_plugin.py
- projects/vdk-plugins/vdk-impala/.plugin-ci.yml
- projects/vdk-plugins/vdk-ingest-http/.plugin-ci.yml
- projects/vdk-plugins/vdk-kerberos-auth/.plugin-ci.yml
- projects/vdk-plugins/vdk-plugin-control-cli/.plugin-ci.yml
- projects/vdk-plugins/vdk-trino/.plugin-ci.yml
Changes in vdk-core can break some plugins. We need some functionality that enables us to catch such regression quicker.
The proposoed change is to introduce in .plugin-common.yml new generic "job" template `.build-plugin-on-vdk-core-release` which can be used by plugins CI.
As it should not be necessary to run all plugin tests, we can select some more important
Testing Done: CI
> vdk-plugins: run tests on release of vdk-core

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
- projects/vdk-core/tests/functional/run/test_run_job_cancel.py
- projects/vdk-core/tests/functional/run/test_run_templates.py
what: Changed the call to the errors.log_and_rethrow method for
a simple log statement and re-raising the exception when the
CancelRemainingSteps exception is raised.
why: Users reading the logs might be confused by the statement,
which assumes a platform error occurred. Recently reverted changes
to the error handling also made jobs using this feature fail with
platform errors since the log_and_rethrow method tripped the
internal logic and made the writer plugin write a platform error
termination message.
testing: Expanded unit test to cover the termination plugin when using
the skip_remaining_steps() functionality.
> vdk-core: platform error no longer logged when skipping execution steps

- projects/vdk-core/requirements.txt
- projects/vdk-plugins/.plugin-common.yml
- projects/vdk-plugins/vdk-kerberos-auth/.plugin-ci.yml
Some builds required Docker in docker (dind) so it's better to assume it's always found. 
This also changes the build-xxx-on-vdk-release to run before merge. For now.  It's better to block the PR than the CICD to be red. If it turns out they slow down things , we can reconsider . 
> vdk-plugins: set dind tempalte job for default build of plugins

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_error_handler.py
This will allow us to make it private in vdk-core. It's basically to string of the exception message. Seem overkill to have a vdk core inteface that shallow.
Teseting Done: vdk-impala tests
> vdk-impala: stop using errors.get_exception_message

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/termination_message/writer.py
- projects/vdk-core/src/vdk/internal/core/errors.py
- projects/vdk-core/tests/functional/run/jobs/simple-query-failed-handled/10_query_then_handle_exceptions.py
- projects/vdk-core/tests/functional/run/test_run_errors.py
- projects/vdk-core/tests/functional/run/test_run_notifications.py
- projects/vdk-core/tests/vdk/internal/core/test_errors.py
Re submit the change -
https://github.com/vmware/versatile-data-kit/pull/1182 - again. The only difference is that I renamed _get_eception_message to get_exception_message as not to break backwords compatability. I will merge this after
--
User code may trigger a SDK feature in a way that raises a user error. In such a use case, the error could be handled by the cautious user, in runtime. The VDK platform should be aware if user errors are handled in runtime or not, so that affects the data job termination status.
The old errors.BLAMEES (experimental data structure for keeping track of responsibles for errors priorly logged) should be refactored:
* a resolvable context abstraction introduced
* it is memory-managed (singleton, reasoning documented)
* populated by the 3 user-facing …
> vdk-core: errors occurred and the state (handled or not) context missing

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_plugin.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/00-fact-snapshot-definition.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/01-test-if-view-matches-target.sql
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/02-insert-into-target.sql
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/03-refresh.sql
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/04-compute-stats.sql
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/README.md
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/params.json
- projects/vdk-plugins/vdk-impala/tests/functional/jobs/insert_template_job/01_prepare_input_data.py
- projects/vdk-plugins/vdk-impala/tests/functional/jobs/insert_template_job/02_run_insert_template.py
- projects/vdk-plugins/vdk-impala/tests/functional/jobs/insert_template_partition_job/01_prepare_input_data.py
- projects/vdk-plugins/vdk-impala/tests/functional/jobs/insert_template_partition_job/02_run_insert_template.py
- projects/vdk-plugins/vdk-impala/tests/functional/template_regression_test.py
A new template is created that only inserts new rows into the dw tables. It is created from an already existing one that overwrites rows for a period of time specified in the view. This template is needed because we maintain large tables that the platform cannot handle when they are regularly populated and our data jobs fail.
> Insert only impala load template

- projects/vdk-plugins/quickstart-vdk/tests/test_dummy.py
The latest version of docker quickstart vdk for release tag is using python 3.9 instead of 3.7 https://hub.docker.com/r/versatiledatakit/quickstart-vdk/tags.
Which is not what master or the intgration tests expect. 
I am pushing this change to trigger a new release of the image so that the latest release tag is for a python 3.7 image.
This PR is a no-op. 
It is being used entirely to trigger a new release of main. 
I will look at the image after it is generated to make sure that it is 3.7
Bug fix
> vdk-quickstart-vdk: trigger a new release.

- projects/vdk-plugins/vdk-ingest-http/src/vdk/plugin/ingest_http/ingest_over_http.py
- projects/vdk-plugins/vdk-ingest-http/tests/test_ingest_over_http.py
Currently, the memory size of the payload to be ingested is calculated before it is converted to string. This is fine for most cases, however, it gets a bit tricky for more complex objects, due to how memory size is calculated (see https://stackoverflow.com/questions/63204377/memory-size-of-list-python for reference).
This change moves the conversion of the payload to string before the memory size is calculated, so we avoid posibility to return misleading IngestionResult data.
Testing Done: Cosmetic change, all tests pass.
> [vdk-plugins] vdk-ingest-http: Move data conversion above size calc

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobCommandProvider.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceStartJobWithArgumentsIT.java
The python site-packages directory is currently hardcoded in the data job container command. However,
this works only for data jobs based on Python 3.7.
This change aims to make the data job cronjob template agnostic for the python version by replacing the hardcoded python site-packages directory with a python command that returns it.
Tested locally against kind cluster.
> control-service: Dynamic python site-packages directory detection

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobExecutionRepository.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/JobExecutionRepositoryIT.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/execution/JobExecutionServiceSyncExecutionIT.java
what: Refactored how the watch task updates missing kubernetes job executions. It should now update the statuses directly against the database, instead of loading entities in memory, updating them (in memory) and saving to the database.
why: Users reported that when cancelling executions, the cancelled execution's status is visible as Succeeded, even tough the API returned success and the status was set to Cancelled. This is caused by the watch task which updates executions in bulk and in memory before saving them to the database.
testing: Added unit tests that cover the new repository query. 
> control-service: refactor db query to mitigate race condition

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/ingress.yaml
The current check always returns false
Change to the property we should actually be checking for 
I created a helm chart locally which looked like this
```
apiVersion: v1
kind: ConfigMap
metadata:
name: test
data:
apiVersions.txt: |
{{ .Capabilities.APIVersions.Has "networking.k8s.io/v1"  }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/ingress" }}
blah: hasC
{{- else }}
blah: noC
{{- end }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
blah2: hasC
{{- else }}
blah2: noC
{{- end }}
```
I rendered it with helm by running `helm template myhelmchart `. The underlying kubectl version was 1.23.x.
the rendered template was: 
```
apiVersion: v1
kind: ConfigMap
metadata:
name: test
data:
apiVersions.txt: |
true
blah: noC
blah2: hasC
```
This shows that it finds …
> vdk-control-service: fix ingress template

- projects/vdk-core/src/vdk/api/plugin/plugin_input.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_base.py
The ingestion functionality in vdk-core allows for the creation of pre-processor plugins that modify the passed payload. This works for most use-cases, but not when an operator of Versatile Data Kit needs to modify or otherwise ammend the dynamically set parameters like target, destination_table, etc., to comply with specific rules.
This change adds functionality to allow for the modification of dynamically set parameters like target by pre-processor plugins. Once modified, the parameters are to be placed in a dictionary, which is then to be added to the metadata using the `updated_dynamic_params` key.
Testing Done: Unit test
> vdk-core: Allow for modification of dynamic params

- projects/vdk-plugins/vdk-audit/setup.py
vdk-audit hook works only with 3.8 python or newer. We want to prevent the vdk-audit from being installed on older python version.
Setting the python_requires argument to the appropriate PEP 440 version specifier string will prevent pip from installing the project on other Python versions
Testing Done: `pip install -e ./vdk-audit` failed correctly with "ERROR: Package 'vdk-audit' requires a different Python: 3.7.9 not in '>=3.8'"
> vdk-audit: set python requires >= 3.8

- projects/control-service/CHANGELOG.md
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Currently JobUpload uploads the file in the same file system as the container process so if too many requests with big data jobs are uploaded it may crash the process/the whole container
Beyond that it's recommended by https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html#file-storage-location to avoid using web root location for staring user supplied files.
add an empty directory volume mount to the pipelines-control-service pods. 
Use this to store the files in. 
made a release of the helm chart under a different name and deployed to the vdk vdp cluster. 
Deployed a heartbeat job.
New feature (non-breaking change which adds functionality)
> vdk-control-service: add empty dir storage

- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/cicd/test-testing-pipelines-service.sh
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl
In a previous commit a helm chart but was submitted. 
This makes a small correction as repo type is no longer used 
I have added in a test step in the PR pipeline to ensure this never happens again. 
> vdk-control-service: fix helm template

- projects/control-service/projects/settings.gradle
Reverts vmware/versatile-data-kit#1306 
The pipeline is consistently failing after merging this - https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/690278941
> Revert "build(deps): bump io.freefair.lombok from 6.1.0-m3 to 6.5.1 in /projects/control-service/projects"

- projects/vdk-plugins/vdk-postgres/src/vdk/plugin/postgres/ingest_to_postgres.py
- projects/vdk-plugins/vdk-postgres/src/vdk/plugin/postgres/postgres_plugin.py
- projects/vdk-plugins/vdk-postgres/tests/jobs/test-ingest/10_ingest.py
- projects/vdk-plugins/vdk-postgres/tests/test_ingest.py
When we were preparing for DSC conference we realized that we are missing simple ingest plugin.
This is really copy pasting the greenplum ingestion. where I changed "greenplum" to "postgres"
I will add this now since we need it . But I think it's time to refactor the db plugins - https://refactoring.guru/refactoring/when
A lot of the code is basically the same with names changed. ... So I will open a PR for that.
> vdk-postgres: add ingest plugin

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_pull_pipelines_control_service_img.yaml
The secret was being created in the deployment namespace. 
With this PR we create it in the correct namespace.
Lint and also printed and investigated. 
> vdk-control-service: create the secret in the correct namespace.

- projects/vdk-plugins/vdk-logging-format/setup.py
Amended path to readme file in setup.py to be consisten with
other plugins.
> vdk-logging-format: Fix path to readme in setup.py

- projects/vdk-control-cli/requirements.txt
what: Added py dependency in requirements.txt
why: Pipeline was failing with missing module. E.g. https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/3323662821
testing: cicd pipeline
> vdk-control-cli: fix cicd

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli.py
what: Updated existing user facing documentation with a command that doesn't fail when
copy/pasted directly in a terminal.
why: Documentation of deploy command says that deploying multiple jobs in a single command is done by:
```
echo "Job1
job2
job3" | xargs -I {JOB} vdk deploy -t job-team -n {JOB} –p <PARENT_DIR_TO_JOBS>/{JOB}
```
But this command fails with:
`Error: Got unexpected extra arguments (–p <PARENT_DIR_TO_JOBS>/{JOB})`
testing: Tested locally to copy/paste the newly produced output and verified command now
works as intended.
> vdk-control-cli: update doc for deployment of multiple jobs w/single command

- projects/vdk-plugins/vdk-trino/README.md
There was a typo in the documentation. That's fixed now.
> vdk-trino: Fix typo in the documentation

- projects/control-service/cicd/deploy-testing-pipelines-service.sh
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
Within my previous commit I wanted to cleanup the tests where we create namespaces on the fly if namespace is null or empty. 
That code still did need to be removed and more of my PR was correct however when namespace is empty or null then we should take the default namespace from the kubeconfig file instead of throwing an error.
remove the assertion and add in debug logging to helm chart deployment to make this easier to debug. 
all pipelines.
> control-service: namespace can be null

- projects/control-service/projects/versions-of-external-dependencies.gradle
Reverts vmware/versatile-data-kit#1350 as the mockito upgrade seems to be unsuccessful - it failed with https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/3383814328  Specidic error was "java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
" - [see details here](https://vmware-analytics.gitlab.io/-/versatile-data-kit/-/jobs/3383814328/artifacts/projects/control-service/projects/pipelines_control_service/build/reports/tests/test/classes/com.vmware.taurus.service.upload.JobUploadTest.html#initializationError)
I am not sure how the same test passed in the pre-merge testing but it's better to be save
> Revert "build(deps): bump mockito-core from 3.11.2 to 4.9.0 

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_pull_base_img.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Within this PR we add support in a builder image for using extra info from k8s through secrets in the namespace. 
In this PR we create the actual secret in the namespace if the info required to create it is present.
Basic linting and looking at a printed out chart. 
closes https://github.com/vmware/versatile-data-kit/issues/1333 
> control-service: builder base image in helm

- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/cicd/release-pipelines-service.sh
I am seeing an issue where helm charts are being released and they point to a pipelines-control-service image that doesn't exist because they have dropped some numbers from the git hash id. 
The bug can be seen here: https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/3408315682
the image it creates doesn’t have the full commit id.
if you search for `image.tag=`  in the logs you can see that it set the commit to something shorter than the commit id
I also think that adding the quotes when declaring the variable might fix this: https://github.com/vmware/versatile-data-kit/issues/1252
I did test locally but am not able to reproduce either issue locally and I think it is related to the shell version they are using on gitlab. 
Add quotes around the commit id and log the commit id at …
> control-service: release helm chart with correct image tag

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/ExecutionDataFetcher.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/ExecutionDataFetcherTest.java
- projects/control-service/projects/versions-of-external-dependencies.gradle
Dependabot is trying to upgrade to the latest version of spring (https://github.com/vmware/versatile-data-kit/pull/1305) but it is running in to compile issues.
These compile issues are related to us using very old graphql libraries.  
In this PR I upgrade the very old graphql libraries so that the spring upgrade can happen in the other PR.  
There is one method declaration change in the newer functions so I had to make that change in the codebase too. 
Unit and integration tests.
> control-service: latest graphql version

- support/gitlab-runners/README.md
- support/gitlab-runners/values.yaml
Currently our gitlab runenrs allowed max 5 concurrent runs, but we have resources for far more and the contribution has increased so 5 are not enough.
Testing Done: none, already deployed following README guidelines.
> vdk-gitlab-runners: increase concurrent pipelines

- support/gitlab-runners/install-runners.sh
I noticed that sometimes gitlab jobs would stuck in pending despite not seeing any pods running (each Gitlab job starts 1 pod, upto 15 (our current limit) of concurrent Gitlab jobs running)
After I restarted the gitlab runner deployment they'd start (kubectl rollout restart deployment).
I am not sure why. But as a first step I am upgrading the gitlab runner to latest version. 0.22 is pretty old anyway
Testing Done: deployed it directly (as per readme) and start gitlab job and saw it works
> vdk-gitlab: upgrade the gitlab runner to latest version

- examples/ingest-and-anonymize-plugin/plugins/vdk-poc-anonymize/README.md
The sample README used in a tutorial may be misleading that it's a real plugin (since it looks like a README of a real plugin). This may confuse people and try to use it. So we are clarifying it here to avoid mistakes.
This was flagged by VMware security team as a potential dependecy confusion attack.
> examples: clarify README sample anonymize plugin

- projects/vdk-core/.gitlab-ci.yml
- projects/vdk-core/cicd/build.sh
- projects/vdk-core/setup.cfg
- projects/vdk-plugins/vdk-test-utils/src/vdk/plugin/test_utils/util_plugins.py
With the GA release of Python 3.11 a month ago it's time to officially support it.
That means we need to start testing against Python 3.11. See release notes at https://docs.python.org/3/whatsnew/3.11.html
This change is adding tests (and changes related to make the tests run) for 3.11 for vdk-core.
Subsequent changes will add that for all other components that support multiple versions of python
While troubleshooting fixed the path to tests.xml so that it shows properly in the test tab - https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/712924440/test_report  and to be able to download the XML test report
Part 1 of https://github.com/vmware/versatile-data-kit/issues/1397
Testing Done: this PR pipeline.
> vdk-core: Support for 3.11

- projects/control-service/cicd/.gitlab-ci.yml
In case of change in versions-of-external-dependencies.gradle we are directly making a new release without triggering release acceptance test which may result in broken release. It's better to make sure the release is tested. 
Also removed job-builder changes from trigger deployment and release test for now as generally default job-builder version is pinned so when changed it would trigger new test. We need to devise a way to test all differnt job-builders anyhow. 
Finally refactored slighlty the yaml anchors to re-use previously defined ones.
Testing Done: this PR
> control-service: run release  test on dependency version change

- examples/ingest-and-anonymize-plugin/plugins/vdk-poc-anonymize/README.md
- projects/vdk-control-cli/src/vdk/internal/control/configuration/vdk_config.py
- projects/vdk-control-cli/src/vdk/internal/control/rest_lib/factory.py
Users are looking to be able to determine where requests originated from when browsing the data.
We are going to let cli users explicitly set the user-agent header. 
sent requests to vdk aas and made sure they have the correct user agent in super collider. 
The results of this test can only be validated by VMware employees which isn't ideal for an open source project. https://sql.supercollider.vmware.com/stg/history/index.html?sql=select%20*%20from%20history_staging.taurus_httptrace%20where%20request_headers_user_agent%20like%20%27%25paul%25%27%20limit%2010&ddlOutputType=table&version=1#
Closes: https://github.com/vmware/versatile-data-kit/issues/1404
> vdk-control-cli: allow cli users to explicitly set the user agent tag

- projects/vdk-plugins/vdk-notebook/.plugin-ci.yml
- projects/vdk-plugins/vdk-notebook/README.md
- projects/vdk-plugins/vdk-notebook/requirements.txt
- projects/vdk-plugins/vdk-notebook/setup.py
- projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/notebook_plugin.py
- projects/vdk-plugins/vdk-notebook/tests/test_plugin.py
What:
Adding a new plugin which will support running data jobs which consists of .ipynb files. it is linked to https://github.com/vmware/versatile-data-kit/issues/1275
This is the default plugin created by the plugin template. 
Modifications and tests are yet to be done.
Why:
You can see [the Jupyter Integration VEP](https://github.com/vmware/versatile-data-kit/blob/main/specs/vep-994-jupyter-notebook-integration/README.md).
> vdk-jupyter: create notebook-plugin

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DeploymentModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMetrics.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/monitoring/DataJobMetricsTest.java
Currently, when a data job is deleted, we reset its termination status, so as to avoid issues with monitoring services reporting incorrect status. This, however, is not done in case a data job is disabled, even though the job is no longer active and its termination status should not matter.
This change modifies the DeplymentService, so that if a data job is disabled, the termination status is reset.
Testing Done: Added test.
> control-service: Reset termination status when job is disabled

- projects/vdk-core/requirements.txt
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/impl/router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_connection_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input.py
- projects/vdk-core/tests/functional/run/jobs/pandas-job/10_pandas_step.py
- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/connection/test_connection_router.py
Currently job_input.get_managed_connection() return the current managed connection which may not be opened if it's called for a first time. THis may lead to subtle bugs e.g
```
pandas.to_sql(sql, con = job_input.get_managed_connection())
```
will return error if job_input.execute_query has not be run before. But will succeed if it's not . That's clearly error prone and also it's unnecessary to force users to called
job_input.get_managed_connection().connect() explicitly).
Testing Done: functional test
> vdk-core: get_managed_connection should return opened connection

- projects/vdk-plugins/vdk-jobs-troubleshooting/src/vdk/plugin/jobs_troubleshoot/api/troubleshoot_utility.py
- projects/vdk-plugins/vdk-jobs-troubleshooting/src/vdk/plugin/jobs_troubleshoot/jobs_troubleshoot_plugin.py
- projects/vdk-plugins/vdk-jobs-troubleshooting/src/vdk/plugin/jobs_troubleshoot/troubleshoot_configuration.py
This change introduces the base utility class which is to be used by all troubleshooting utilities.
Additionally, the plugin configuration is moved to a separate method to be easier to extend.
Testing Done: Documentation change.
> vdk-jobs-trobleshooting: Introduce plugin API and configuration

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLJobTeamAndNameFilterMatcherIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/strategy/FieldStrategy.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/strategy/datajob/JobFieldStrategyByName.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/strategy/datajob/JobFieldStrategyByTeam.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/GraphQLDataFetchersTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/GraphQLJobTeamFetcherIT.java
what: Added wildcard matching e.g *-search-* in graphQl filters for job name and team name and exact matching of search strings.
why: Current implementation uses Java String's .contains() method which doesn't have the ability to return exact matches. Users of the control-service API ran into usability issues when multiple results were returned, without the ability to filter for exact matches.
testing: added tests.
> control-service: graphql wildcard matching filter for team and job names

- projects/vdk-plugins/vdk-jobs-troubleshooting/src/vdk/plugin/jobs_troubleshoot/troubleshoot_configuration.py
- projects/vdk-plugins/vdk-jobs-troubleshooting/src/vdk/plugin/jobs_troubleshoot/troubleshoot_utilities/healthcheck_server.py
- projects/vdk-plugins/vdk-jobs-troubleshooting/tests/functional/jobs/request-thread-dump/request-thread-dump.py
- projects/vdk-plugins/vdk-jobs-troubleshooting/tests/functional/test_thread_dump.py
Why?
Stop the plugin from crashing a data job run if the configuration is not complete or the target port is alredy used.
What?
Changed default value of TROUBLESHOOT_UTILITIES_TO_USE Added find free port logic to server start.
Added try/except logic to prevent the plugin from crashing the job run.
How has this been tested?
Added another test case in the functional test.
What type of change are you making?
Bug fix
> vdk-jobs-troubleshooting: Improve robustness of the plugin

- projects/vdk-plugins/vdk-jobs-troubleshooting/src/vdk/plugin/jobs_troubleshoot/jobs_troubleshoot_plugin.py
- projects/vdk-plugins/vdk-jobs-troubleshooting/src/vdk/plugin/jobs_troubleshoot/troubleshoot_utilities/healthcheck_server.py
Why?
Data jobs sometime don't finish/quite as expected when the troubleshooting server is started
What?
Change the HTTP server of the troubleshoot utilities to run as a deamon thread
Type of change
Bug fix
> vdk-jobs-troubleshooting: Run troubleshooting server as deamon thread

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/upload/FileFormatDetector.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/upload/FileUtils.java
Why?
Fix potential resource leak fixes uncovered by coverity scaner
What?
Switch to try-with-resource blocks
What type of change are you making?
Bug fix
Signed-off-by: Dako Dakov ddakov@vmware.com
> vdk-control-service: potential resource leak fixes

- projects/control-service/projects/base/src/main/java/com/vmware/taurus/service/diag/HttpTracer.java
- projects/control-service/projects/base/src/main/java/com/vmware/taurus/service/diag/methodintercept/DiagnosticsPublisher.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobsService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/KerberosCredentialsRepository.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionResultManager.java
Why?
Fix null dereference uncovered by coverity scaner
What?
Multiple changes mostly related to json conversions.
What type of change are you making?
Bug fix
Signed-off-by: Dako Dakov ddakov@vmware.com
> vdk-control-service: fix null dereferences

- projects/control-service/projects/job-builder-secure/Dockerfile
Why?
Fix docker image vulnerabilities uncovered by `docker scan job-builder-secure`
```
+------------------+----------+--------+----------+---------------+---------+---------+
|     VULN ID      | PACKAGE  |  TYPE  | SEVERITY | FIX AVAILABLE | CVSS V2 | CVSS V3 |
+------------------+----------+--------+----------+---------------+---------+---------+
| CVE-2022-42915   | libcurl  | apk    | CRITICAL | 7.83.1-r4     |     0.0 |     9.8 |
+------------------+----------+--------+----------+---------------+---------+---------+
| CVE-2021-3177    | python3  | apk    | CRITICAL | 3.8.7-r2      |     7.5 |     9.8 |
+------------------+----------+--------+----------+---------------+---------+---------+
| CVE-2021-29921   | python3  | apk    | CRITICAL | 3.9.5-r0      |     7.5 |     9.8 | …
```
> job-builder: address docker image vulnerabilities

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/common/MiniKdcCredentialsRepository.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/JobCredentialsService.java
In my previous PR I merged code which deletes an empty keytab file, so that we keep only the filename. 
This is the desired behaviour for the test kdc server as it expects no file to be at the file location. 
However the production path expects there to be an empty file there. 
Push the delete logic into the test impl so that we aren't modifying the production code path. 
entire deployment pipeline
Should more of the pipeline run on branches as it would have caught this issue?
> control-service: only delete file in test path

- CONTRIBUTING.md
In time it has proven that maintaining a separate Changelog file is not an efficient way of documenting changes. It's very rarely updated. And often the quality is not high as most users I have shown it to do not understand it. We also have a lot of components and it's hard to track changes across all component's distinct changelog files. Unofficially we had not really be using/udpating changelogs for some time. 
This PR is abolishing this practice officially by removing it from contributing guide. 
Nowaday once a month we make a [release](https://github.com/vmware/versatile-data-kit/releases) instead and [document the changes there as release notes](https://github.com/vmware/versatile-data-kit/blob/main/CONTRIBUTING.md#how-to-make-a-new-vdk-release).
After merging this, I will review …
> vdk: update changelog instructions

- projects/control-service/cicd/.gitlab-ci.yml
- projects/vdk-control-cli/.gitlab-ci.yml
- projects/vdk-core/.gitlab-ci.yml
- projects/vdk-heartbeat/.gitlab-ci.yml
We want to support scheduled jobs in the near future. 
As a first step we should clean up what is there already. 
This involves. 
1. rewriting `only` conditions as `rules`. which are more extensible in the future. 
2. upgrading helm. 
I will babysit the pipelines after this is merged to identify any anomalies.
> vdk-cicd: cleanup cicd rules

- projects/control-service/cicd/.gitlab-ci.yml
- projects/vdk-control-cli/.gitlab-ci.yml
- projects/vdk-core/.gitlab-ci.yml
- projects/vdk-heartbeat/.gitlab-ci.yml
- projects/vdk-plugins/.plugin-common.yml
- projects/vdk-plugins/airflow-provider-vdk/.airflow-ci.yml
- projects/vdk-plugins/quickstart-vdk/.plugin-ci.yml
We want to be able to run scheduled jobs. 
But as part of the scheduled jobs we want to skip `publish_artifact` jobs and also `release` jobs.
This change should not have any impact on the pipeline and I will start running the scheduled jobs once we see the pipeline is still green for merge triggered builds. 
In the future I might extract the rule into a shared abstract job. But that will be a later PR
Add a guard on all `publish_artifact` jobs and also `release` jobs so that they won't run if it is triggered by a scheduled operation. 
I also upgraded helm if we are testing everything we should try upgrade that too. The hope here is that it fixes https://github.com/vmware/versatile-data-kit/issues/1252. 
Not much, mostly visual inspection. 
closes …
> vdk-cicd: during a scheduled run publish_artifacts and release shouldn't run

- README.md
Our mailing list posted in https://github.com/vmware/versatile-data-kit#contacts is being used for project development/maintainer purposes (Gitlab CICD failure notifications,  expiring tokens, etc) so I will update the doc to reflect this. Also joining it is 3 step process and is not that easy (you need to click, then send an email and finally someone from the team manually need to add you to teh group)
We need mailing list for users that only a click but that is separate issue. 
Here I am updating it to make clear its usage. 
The mailing list was missing "mailto:" so it was not opening mail but trying to redirect browser and this is fixed also.
Signed-off-by: Antoni Ivnaov <aivanov@vmware.com>
> versatile-data-kit: update readme with mail list

- projects/control-service/cicd/.gitlab-ci.yml
The pipeline which runs after the merge on the main branch is not very efficient. More details can be found here - #1593 
1. control_service_build_image and control_service_integration_test jobs are disabled as they are executed in the PR pipeline.
2. Disabled unit tests for the control_service_publish_image job
Local execution of Gradle commands
Signed-off-by: Miroslav Ivanov [miroslavi@vmware.com](mailto:miroslavi@vmware.com)
> control-service: Remove duplicated CICD job runs

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceStartNewCronJobExecutionTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
Alot of tests which are written on the KubernetesService should actually be written on the DataJobsControlService as the tests themselves are focused on Cron job functionality which should only happens on the data jobs. 
For more info regarding this please look here: https://github.com/vmware/versatile-data-kit/issues/1600
Within this PR I have modified a lot of tests to use declare the controlService with var instead of ControlService, so we can change it for DataJobsControlService very easily in an upcoming PR. 
This is a stand alone PR to make reviewing easier.
> control-service: cleanup tests to ease testing on control service

- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceCancelRunningCronJobTest.java
Very similar to https://github.com/vmware/versatile-data-kit/pull/1604
Alot of tests which are written on the KubernetesService should actually be written on the DataJobsControlService as the tests themselves are focused on Cron job functionality which should only happens on the data jobs. 
For more info regarding this please look here: https://github.com/vmware/versatile-data-kit/issues/1600
Within this PR I have modified a lot of tests to use declare the controlService with var instead of ControlService, so we can change it for DataJobsControlService very easily in an upcoming PR. 
This is a stand alone PR to make reviewing easier.
> control-service: cleanup tests to ease testing on control service (v2)

- projects/frontend/data-pipelines/README.md
- projects/frontend/data-pipelines/projects/gui/README.md
- projects/frontend/data-pipelines/projects/gui/projects/data-pipelines/README.md
Before merging the frontend code we want to make sure the readmes are clearly explaining the project/where to find everything and how to buid everything. 
1. Copied the readmes from the private repo. 
2. Removed references to CSP auth and replaced it with TODOs to be tackled once we can authenticate with a different oauth provider. 
3. removed references to extensibility.
> vdk-frontend: include readmes for the data-pipelines folders

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLJobTeamAndNameFilterMatcherIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/strategy/datajob/JobFieldStrategyByName.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/strategy/datajob/JobFieldStrategyByTeam.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/GraphQLJobTeamFetcherIT.java
what: reverted some of the changes introduced in https://github.com/vmware/versatile-data-kit/pull/1459 . Reverted code and removed relevant tests.
why: users of the control-service have had a hard time adjusting to the changes, and we agreed to roll them out in a more controlled manner, one by one for each filter/search field individually.
testing: n/a since the change reverts to old functionality, existing tests already cover it.
> control-service: graphql revert part of the wildcard filter matching

- projects/vdk-plugins/vdk-notebook/README.md
What:
Introduced some changes on the vdk-notebook README
Why:
It didn't have a proper example and some information needed to be changed.
> vdk-jupyter: vdk-notebook README improvements

- projects/control-service/projects/job-base-image-secure/publish-job-base.sh
There is an unused parameter to the docker build command called "arguments" which breaks the command when it is empty.
https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/3790587531
Signed-off-by: Miroslav Ivanov [miroslavi@vmware.com](mailto:miroslavi@vmware.com)
> job-base-image-secure: remove unused parameter from publication script

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobInitContainerOOMIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobMainContainerOOMIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionResultManager.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMonitor.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/execution/JobExecutionResultManagerTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/execution/JobExecutionServiceUpdateExecutionIT.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/monitoring/DataJobMonitorTest.java
Currently, if the init container fails with OOM
the control service will mark the job as successful execution.
Changed the CS logic to the following:
if the init container fails with OOM
the control service will mark the job as Platform Error.
Integration test
> control-service: handle init container OOM

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobDeploymentCrudIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/v1-k8s-data-job-template.yaml
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/resources/v1-k8s-data-job-template.yaml
Currently there is no backwards compatibility support when a user switches to the V1 Kubernetes Cronjob API (from the currently default V1beta1). This results in situations, where if there are deployed data jobs which use the v1beta1 API, and a switch is made to the V1 API, these jobs are suddenly shown as `NOT DEPLOYED`, and cannot be properly managed.
This change adds backwards compatibility support in the Kubernetes Service, to allow for a switch to V1 Cronjob API in clusters, where V1beta1 API cronjobs are deployed.
Testing Done: Unit and Integration tests (new and existing).
> control-service: Cronjob API backwards compatibility

- .gitignore
- .pre-commit-config.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/configmap_datajob_template_file.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/fluentdconfig.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/fluentdconfig_datajobs.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/ingress.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/prometheusrules.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/role.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/role_datajobs.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/rolebindings.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/rolebindings_datajobs.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_jdbc.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_kubernetes_authenticator.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_pull_base_img.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_pull_builder_img.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_pull_img.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_pull_pipelines_control_service_img.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_pull_vdk_sdk_img.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secrets.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/service.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/serviceaccount.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/servicemonitor.yaml
Update helm template license headers to use template-style comments Ignore helm templates in pre-commit yaml license hook Create new pre-commit license hook to add template-style comments to helm templates
Regular yaml comments at the top of files break parsing for helm charts This breaks control-service deployments
Tested installing the charts on a local k8s cluster using helm
Ran `helm upgrade --install --debug --wait --timeout 10m0s cicd-control-service .` on the chart, which gave me the same output as the failing pipeline. Edited the comments until the apiVersion error disappeared.
```
Error: UPGRADE FAILED: error validating "": error validating data: apiVersion not set
```
https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/3813924321
> control-service: Update helm template license headers

- projects/control-service/projects/pipelines_control_service/src/main/resources/k8s-data-job-template.yaml
- projects/control-service/projects/pipelines_control_service/src/main/resources/v1-k8s-data-job-template.yaml
Kubernetes, service accounts are used by pods to authenticate with the Kubernetes API server and access resources in the cluster. Each pod is assigned a service account, and by default, the service account token is mounted in the pod's file system and used for authentication.
However, not all pods need to access the Kubernetes API server or cluster resources, and in some cases, including the service account token can pose a security risk. For example, if a pod is compromised or runs untrusted code (which data job generally do), an attacker could use the service account token to escalate privileges and access sensitive resources in the cluster.
To mitigate this risk, Kubernetes provides the
`automountServiceAccountToken` property, which can be used to disable the automatic mounting of the …
> control-service: don't include needless service token

- projects/vdk-plugins/vdk-trino/.plugin-ci.yml
- projects/vdk-plugins/vdk-trino/requirements.txt
- projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_utils.py
- projects/vdk-plugins/vdk-trino/tests/conftest.py
- projects/vdk-plugins/vdk-trino/tests/docker-compose.yml
- projects/vdk-plugins/vdk-trino/tests/test_vdk_templates.py
This change is fixing vdk-trino tests which are failing regularly in the nightly builds . See
https://github.com/vmware/versatile-data-kit/issues/1559
The tests were failing intermittently for two main reasons 
* Docker failures which are being fixed by adopting testcontainers  (in favour of pytest-docker)
* Hidden dependencies between  test cases (because different test use same schema and tables on shared db instance)
Until now we used pytest-docker to start service container, this is switching it to testcontainers-python.
There are multiple advantages of using it.
* Supposedly Testcontainers is built with performance in mind and uses a variety of techniques to minimize container startup time and resource usage like image reuse, container reuse, asynchronous operations.
* It is far more …
> vdk-trino: stabilize vdk-trino tests

- .github/workflows/dependabot.yml
The auto-merge fails due
`Error: Input required and not supplied: github-token` See https://github.com/vmware/versatile-data-kit/actions/runs/4295507705/jobs/7486018753
Applying the fix suggested:
https://github.com/actions/checkout/issues/298#issuecomment-820748989
Testing done: ci/cd
> versatile-data-kit: dependabot auto-merge fix

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package.json
What:
Removed the py-to-ts-interfacesfrom from build.
Created an issue about adding it again to the build - https://github.com/vmware/versatile-data-kit/issues/1690
Why: It causes problems with the build and requires some hacky code to be build.
> vdk-jupyter: remove py-to-ts-interfaces because of build problems

- projects/frontend/cicd/.gitlab-ci.yml
- projects/frontend/cicd/build_data_pipelines.sh
- projects/frontend/cicd/install_data_pipelines.sh
- projects/frontend/data-pipelines/README.md
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/pages/executions/execution-duration-chart/execution-duration-chart.component.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/pages/executions/time-period-filter/time-period-filter.component.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/services/data-jobs.api.service.spec.ts
We need to build and run unit tests of data-pipelines library and ui application that uses it. The component is dependent on shared-components library.
Added Bash scripts to
(1) link if any shared-components rebuild was made and is about to be published, or otherwise default to latest already published one 
(2) build the data-pipelines library and link @vdk/data-pipelines 
(3) build the UI application
(4) lint the subprojects to verify format
(5) run the unit tests
One bash script is meant to be used to satisfy build prerequisites, the other one to rebuild and relink continuously, needed during development.
The proposed implementation triggers a data-pipelines rebuild (+test), upon any shared-components change, as well as data-pipelines changes. 
A README.md link fix to the VEP.
Testing …
> frontend: data-pipelines build and test running CI/CD

- projects/vdk-heartbeat/tests/vdk/internal/test_trino_database_test.py
https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/3876278808 was failing with
```
FAILED tests/vdk/internal/test_trino_database_test.py::test_create_table
- TypeError: '>' not supported between instances of 'MagicMock' and
'int'
FAILED tests/vdk/internal/test_trino_database_test.py::test_delete_table
- TypeError: '>' not supported between instances of 'MagicMock' and
'int'
FAILED
tests/vdk/internal/test_trino_database_test.py::test_insert_table_row -
TypeError: '>' not supported between instances of 'MagicMock' and 'int'
FAILED tests/vdk/internal/test_trino_database_test.py::test_select_data
- TypeError: '>' not supported between instances of 'MagicMock' and
'int'
```
Trying to fix this.
Testing Done: this CI.
> vdk-heartbeat: fix test failures

- .github/workflows/dependabot.autoapprove.yml
- .github/workflows/dependabot.automerge.yml
Dependabot is creating PR. This is helping to automate them by
1. Automatically approving them
2. Automatically trying to merge them (only if all tests have passed)
3. Automatically updating them with latest changes
Testing Done: created a fork and tested the flow there.
using custom labels (as a proxy for dependabot)
> versatile-data-kit: automate merging of dependabot PRs

- support/gitlab-runners/values.yaml
To resolve VDK Frontend e2e tests blocked by a host hard requirement, we need to add localhost.vmware.com alias entry to /etc/hosts file of the containers. See:
https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/3886157064
Patching the gitlab runners config.
Testing done: upon approval before merge, I intend to update the gitlab runners and verify.
> versatile-data-kit: add hosts entry to gitlab runners

- projects/frontend/cicd/install_shared.sh
- projects/frontend/data-pipelines/gui/.npmrc
- projects/frontend/shared-components/gui/.npmrc
Change shebang in build_shared.sh to !/bin/bash -e
This points to the correct execution shell for build scripts and passes the -e flag, which makes the script fail on the first error exit code
> frontend: Fix shebang in build_shared.sh

- projects/vdk-plugins/vdk-meta-jobs/src/vdk/plugin/meta_jobs/meta_dag.py
What: 
make the log that is logged when _start_job() is called with number of concurrent running jobs = limit more descriptive
Why:
to simplify debugging in the future
> vdk-meta-jobs: make _start_job() limit hit log more descriptive

- projects/control-service/cicd/.gitlab-ci.yml
We are seeing job builds fail.
For full details see here:
https://cloud-native.slack.com/archives/C033PSLKCPR/p1680003501501429
we were failing to connect to the daemon in an old version of docker in docker.
Upgrading to the latest version fixes all the issues.  
CICD
> Fix CICD build for control service

- specs/vep-1243-vdk-meta-jobs/README.md
What: 
Add some configurable variable references in the VEP - META_JOBS_MAX_CONCURRENT_RUNNING_JOBS and some missing hyperlinks to others.
Signed-off-by: Yoan Salambashev <ysalambashev@vmware.com>
> vdk-meta-jobs: add some configurable variable references in the VEP

- support/gitlab-runners/values.yaml
Frontend tests are being killed/evicited by Kubernetes Noticeable are following errors from kubectl get events in cicd namespace:
```
41m         Warning   Evicted
pod/runner-xpbjijbb-project-28359933-concurrent-3qnpql
The node was low on resource: ephemeral-storage.
Container build was using 32Ki, which exceeds its request of 0.
Container helper was using 16Ki, which exceeds its request of 0.
49m         Warning   Evicted
pod/test-prom-node-exporter-9cpmq
The node had condition: [DiskPressure].
```
I am asetting some limits and requests in
to try to fix it.
> vdk-cicd: set ephemeral storage request/limits

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/version_group/version.py
- projects/vdk-control-cli/src/vdk/internal/control/configuration/vdk_config.py
- projects/vdk-control-cli/src/vdk/internal/control/utils/version_utils.py
There is a circular import issue between the
vdk.internal.control.configuration.vdk_config and
vdk.internal.control.command_groups.version_group.version modules. Specifically, vdk_config is importing version and version is importing cli_utils, which is importing vdk_config. This creates a cycle that cannot be resolved, which is causing the ImportError under certain circumstances.
To fix this issue, I need to refactor the code to remove the circular import. I moved the methods for determining verison in version utils which is used by both vdk_config and version_group.version modules.
> vdk-control-cli: fix circular import dependecy

- .gitignore
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli_impl.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/execute.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/list.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/properties.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/show.py
- projects/vdk-control-cli/src/vdk/internal/control/utils/cli_utils.py
- projects/vdk-control-cli/src/vdk/internal/control/utils/output_printer.py
- projects/vdk-control-cli/tests/vdk/internal/control/utils/test_output_printer.py
Currently, if a command needs to print similar types of data in multiple places
or formats, the developer would have to duplicate the printing code for each location or format. This would lead to a lot of redundant code, which is difficult to maintain and prone to errors. This is making the code more "DRY".
Also, users and devs are limited to a fixed set of output formats provided by the application. This could be restricting if the devs needs to print data in a format that is not supported by the application. E.g I wanted to add `rich` or `streamlit` type potentially.
By introducing support for customizable output formats with the Printer class and related functions, users can define their own output formats and register them with the application using the printer decorator. This allows …
> vdk-control-cli: refactor output printing with printer class

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli_impl.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/execute.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/list.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/properties.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/show.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/version_group/version.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_deploy.py
Adopting the new output_printer to print all outputs of all commands that were introduced in https://github.com/vmware/versatile-data-kit/pull/1819
Some commands required small refactoring - to make some fields private.
Testing Done: existing tests to verify no regressions
> vdk-control-cli: use common output printer

- projects/control-service/projects/job-base-image/publish-job-base.sh
Why:
As part of the initiative to add support for multiple Python versions, we need to provide the ability to specify Python 3.11.
What:
Added step for producing a base job image for Python 3.11.
Testing done:
Manually executed the script.
> control-service: Add support for Python 3.11

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package.json
What: 
Removed react-test-renderer package from package.json
Why:
It was unused and was causing some problems because of react version mismatch
> vdk-jupyter: remove react-test-renderer package from package.json

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/SupportedPythonVersions.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application-prod.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/SupportedPythonVersionsTest.java
Currently, the job base image used in job builders is set in the `deploymentDataJobBaseImage` application property. This is set once at Control Service deploy and requires re-deploy of the service to be changed.
As part of the initiative to support multiple python versions for data job deployments, a new application property, `supportedPythonVersions`, was introduced in https://github.com/vmware/versatile-data-kit/commit/967898fddec3e0515f1e5817bc2211cebc1b2d92. Additionally, a new API property, `python_version` was introduced in https://github.com/vmware/versatile-data-kit/commit/5086fa3d2fde0bb9db38e3ca1928764c95cf3900 to allow users to set which python version to be used for job deployments.
With all this done, this change updates the JobImageBuilder to use the above-mentioned …
> control service: Dynamically set job base image in builder

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/ToApiModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/model/DataJobExecution.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/db/migration/V20230410140000__add_column_job_python_version_to_data_job_execution_table.sql
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/execution/JobExecutionServiceUpdateExecutionIT.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/execution/JobExecutionServiceUtil.java
As part of the initiative to add support for multiple Python versions,  we need to extend the Execution API to return python_version for each individual execution.
Added job_python_version column to the data_job_execution table and job_python_version field to all DTOs related to the Execution API.
Unit tests. IT test will be added later since the feature for adding support for multiple Python versions is not ready for e2e testing.
> control-service: Add python_version to Execution API

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/index.ts
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/jobData.ts
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/vdkTags.ts
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/style/base.css
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/style/images/versatile-data-kit-logo.svg
- projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/notebook.py
What:
Added new design for the cells that are tagged with vdk
The new design includes different background colour of the vdk cells (light blue and dark blue), vdk logo and vdk cell numbering.
Here are the designs in light and dark mode: 
Why: Up until now, we marked the cells for vdk with Jupyter tags, but they are not really user friendly - it is really easy to forget to mark something or mark something by mistake and never realise that you did it since it is really hard to track tags. With these changes it becomes really easy to see which cells are tagged and which are not which makes the UI more user-friendly and error-proof.
Tests: manual tests with dark and light mode 
> vdk-jupyter: add UI vdk cell marks

- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/frontend/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/frontend/secret_pull_pipelines_control_service_img.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/frontend/service.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/ingress.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Within the introduction of the frontend docker image we want it to appear when ppl visit the host url.
In this PR we introduce:
1. a new deployment and service to support running the frontend. 
2. an ingress rule to send requests from the root of the host to the frontend and an ingress rule to send any requests for /data-jobs to the control-service. 
3. Support for reading the frontend docker image from a private repo which is something we need within VMWare. 
4. Update the control-service to the a newer version
5. add support for basic configuration of the frontend service e.g. how much cpu the deployment is given. 
What is not in this PR:
1. passing configuration to the frontend via properties or volumeMounts.
Locally
> control-service: add the frontend to helm

- projects/frontend/cicd/.gitlab-ci.yml
- projects/frontend/cicd/publish_image_dockerhub.sh
- projects/frontend/data-pipelines/gui/Dockerfile
- projects/frontend/data-pipelines/gui/config/nginx.conf
- specs/vep-1507-vdk-operations-ui/README.md
Stacked on top of https://github.com/vmware/versatile-data-kit/pull/1862
Part of the wider effort to add the UI to quickstart-vdk
Build and publish a docker image for the UI as part
of the release step in the CI/CD pipeline. Image tags
follow the same versioning schema as the data-pipelines
package in the npm registry
Ran the gitlab script locally
https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4148986837
New feature (non-breaking change which adds functionality)
Signed-off-by: Dilyan Marinov <mdilyan@vmware.com>
> frontend: publish docker image for ui

- .github/workflows/autoupdate.yml
An older hardcoded ubuntu was used.
Ubuntu updated to latest, in sync with the rest of the workflows.
Testing done: verified no version limitations regarding public docs.
> vdk-github-workflows: ubuntu latest update

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
As part of the initiative to support multiple python versions in data job deployments, new configurations were introduced in the form of `datajobs.deployment.supportedPythonVersions` and `datajobs.deployment.defaultPythonVersion` configuration properties.
To facilitate proper production setup of the Control Service with the new functionality, the configuration needs to be exposed in the helm chart.
This change updates the values.yaml and deployment.yaml files of the Control Service helm chart to expose the supportedPythonVersions and defaultPythonVersion configurations and set them as environment variables.
Testing Done: CI/CD and local run of `helm lint` on the chart.
> control-service: Expose supported python versions in helm

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli_impl.py
at newer versions of pydantic parameters must be declared by name. 
On the later version of the api client it will be important to have this change. 
tests in cicd
> vdk-control-cli: use explicit parameter names

- projects/control-service/projects/model/apidefs/datajob-api/api.yaml
This is a very subtle bug in the api declaration for the properties api.
Within the server we want to support clients sending a Map<String, Object> for properties. 
https://github.com/vmware/versatile-data-kit/blob/b2a40491d65c138411ec36d0646a870a893aed03/projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/properties/controller/DataJobsPropertiesController.java#L36
Within the declaration for this endpoint we have written it as 
```yaml
type: object
additialProperties: 
type: object
```
This is actually wrong.
Within the open api docs we can see that an object has the following definition: 
`An object is a collection of property/value pairs. The properties keyword is used to define the object properties – you need to list the property names and …
> control-service: fix api declaration

- projects/control-service/projects/model/apidefs/build.gradle
- projects/control-service/projects/model/apidefs/datajob-api/config-python.json
The newest python api client is broken and the last working one is very old. 
In this PR I use the python-nextgen generator instead of the python generator. The behaviour is much more correct and predictable. 
There are two bugs in the generated code. 
For both these I have created tickets in the openapi generator github project.
I have added string replace workarounds in the gradle step to fix these bugs before we publish the pip package. 
next steps(will be tackled in the next few weeks not days): https://github.com/vmware/versatile-data-kit/issues/1982 
closes: https://github.com/vmware/versatile-data-kit/issues/1979
Locally. 
There is actually a draft branch where I import this new version into the cli project and run tests against it to confirm everything is green: …
> control-service: new python client.

- projects/control-service/projects/base/src/main/java/com/vmware/taurus/security/SecurityConfiguration.java
- projects/control-service/projects/base/src/main/java/com/vmware/taurus/service/diag/telemetry/Telemetry.java
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/SupportedPythonVersions.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/SupportedPythonVersionsTest.java
Currently, there are two groups of configurations to set the vdk and job base images used in data job deployments. The old way, through the `datajobs.deployment.dataJobBaseImage` and `datajobs.vdk.image`, and the new way, through the support for multiple python versions in data job deployments.
The two groups of configurations are in conflict, as the old configuration options take precedence and cleanly migrating to the support for multiple python versions is practically impossible.
This change removes the default values for the `datajobs.deployment.supportedPythonVersions` and `datajobs.deployment.defaultPythonVersion` properties, and updates the service logic so that when these properties are set in an environment, they take precedence over the old configuration.
> control-service: Rework supported python version logic

- projects/vdk-plugins/vdk-dag/README.md
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/dag.py
Deprecation warnings were accidentally left in when renaming the plugin.
Testing done: trivial
> vdk-dag: Drop deprecation warnings

- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/SupportedPythonVersions.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/SupportedPythonVersionsTest.java
Currently, there are some backwards-compatibility issues with Control Service deployments that do not integrate support for multiple python versions and move to introduce it. The issues surface, when service administrators decite to add multiple supported python versions in their private values.yaml configuration files. The new configurations are ignored and it is not possible to cleanly migrate to support multiple python versions, as only the old configurations through `datajobs.vdk.image` and `datajobs.deployment.dataJobBaseImage` are recognised.
This change relaxes the service behaviour, so that if the `datajobs.deployment.supportedPythonVersions` and `datajobs.deployment.defaultPythonVersion` configuration options are set, they would take precedence over the old configurations. …
> control-service: Fix backwards-compatibility issues

- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/dag_plugin.py
- projects/vdk-plugins/vdk-dag/tests/test_dag.py
A bug was introduced during renaming the plugin where the config var was named differently than what is expected. This wasn't caught by our testing due to how the CliRunner runs plugin hooks.
Testing done: manual
> vdk-dag: Fix config bug

- projects/frontend/data-pipelines/gui/e2e/integration/explore/data-jobs/data-jobs.spec.js
- projects/frontend/data-pipelines/gui/e2e/integration/explore/data-jobs/details/data-job-details.spec.js
- projects/frontend/data-pipelines/gui/e2e/integration/explore/data-jobs/executions/data-job-executions.spec.js
- projects/frontend/data-pipelines/gui/e2e/integration/manage/data-jobs/data-jobs.spec.js
- projects/frontend/data-pipelines/gui/e2e/integration/manage/data-jobs/details/data-job-details.spec.js
- projects/frontend/data-pipelines/gui/e2e/plugins/helpers/job-helpers.plugins.js
- projects/frontend/data-pipelines/gui/e2e/plugins/index.js
- projects/frontend/data-pipelines/gui/e2e/support/pages/base/data-pipelines/data-pipelines-base.po.js
Fixing failing e2e tests where root cause was many jobs in the list and introduced filtering by jobName before search happens.
Improved logging for delete Data Jobs, when this deletion happens in before suite step.
> frontend: Fix for e2e tests

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/MockKubernetes.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceTest.java
Obviously deleting unused methods is a good idea. 
However in this case it is even more important. 
There are tests asserting that create or update are not called. 
But they are checking the wrong methods and so before this PR those assertions are meanigless. 
unit tests
> control-service: delete unused method

- examples/gdp-execution-id-example/10_sql_step.sql
- examples/gdp-execution-id-example/20_python_step.py
- examples/gdp-execution-id-example/README.md
- examples/gdp-execution-id-example/config.ini
- examples/gdp-execution-id-example/requirements.txt
- projects/vdk-plugins/vdk-gdp-execution-id/README.md
I sketched a vdk-gdp-execution-id data job example to 
check locally using quickstart-vdk.
This is a stacked PR to import fix:
https://github.com/vmware/versatile-data-kit/pull/1961
Added the data job to examples directory.
Testing done: verified locally
> vdk-gdp-execution-id: example added

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/info_group/info.py
- projects/vdk-control-cli/src/vdk/internal/control/main.py
- projects/vdk-control-cli/src/vdk/internal/control/rest_lib/factory.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/info_group/test_info.py
vdk-control-cli: add vdk info command
Add the vdk info command to show CS version and supported
python versions.
> add vdk info command

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_error_classifier.py
- projects/vdk-plugins/vdk-impala/tests/test_error_classifier.py
what: added a new error to be classified as user exception in the vdk-impala plugin
why: a use case came up where the following excerpt of an exception was classified as platform error:
`File "/vdk/site-packages/impala/hiveserver2.py", line 1397, in fetch
resp = self._rpc('FetchResults', req, False)
File "/vdk/site-packages/impala/hiveserver2.py", line 1085, in _rpc
err_if_rpc_not_ok(response)
File "/vdk/site-packages/impala/hiveserver2.py", line 781, in err_if_rpc_not_ok
raise HiveServer2Error(resp.status.errorMessage)
impala.error.HiveServer2Error: UDF ERROR: Decimal expression overflowed
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/vdk/site-packages/vdk/internal/builtin_plugins/run/data_job.py", line 73, in run_step …
> vdk-impala: add udf hive2server user error classification

- projects/control-service/projects/model/apidefs/datajob-api/api.yaml
org.openapi.generator was not configured with quickstart-vdk server.
Adding url and description for quickstart-vdk default local setup.
Tesing done: cicd
> control-service: Swagger UI quickstart-vdk server config

- projects/control-service/projects/model/apidefs/build.gradle
- projects/control-service/projects/model/apidefs/datajob-api/config-python.json
We were using a version of the python client generator that had a few bugs in it. I opened tickets and they have fixed the bugs
Upgrade the gradle plugin version and remove the hacks in the gradle codebase to workaround the existing issues.
I made a release of it locally and ran the vdk-control-cli tests using the newest python client library.
> control-service: upgrade python client

- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
The explore page and widgets are not relevant to users outside of VMWare This also fixes the bug where the frontend does not load on running quickstart-vdk due to missing configuration
Ignore the explore page and widgets in the control service helm chart
Configuration tested locally
Helm chart tested in CI
Bug fix (non-breaking change which fixes an issue) or a cosmetic change/minor improvement
> quickstart-vdk: ignore explore page and widgets in frontend

- projects/vdk-plugins/airflow-provider-vdk/tests/hooks/test_vdkhook.py
- projects/vdk-plugins/airflow-provider-vdk/tests/sensors/test_vdksensor.py
on the newest python api client we are getting failing test because we check more of the properties in the mock response. 
Return a dummy response. 
The dummy response which has the required properties. 
ran tests locally
> vdk-airflow: fix failing tests

- projects/vdk-control-cli/requirements.txt
- projects/vdk-control-cli/setup.cfg
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/download_job.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/download_key.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/execute.py
We were using a version of the python client generator that had a few bugs in it. I opened tickets and they have fixed the bugs. in this PR https://github.com/vmware/versatile-data-kit/pull/2076 I released the new version. 
Make a few small changes to make it compatible with the latest version
ran tests locally
> vdk-control-cli: upgrade python client

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package.json
What:
Pinned rendermime-interfaces to 3.6.3.
Also removed "@cfaester/enzyme-adapter-react-18": "^0.6.0" which is not used and caused not frequent build errors.
Why:
Because jupyterlab 4 is released some days ago, and it bumps the latest version of rendermime-interface to 3.8.0, which is not compatible with lumino 1.x
This caused Build issues: 
> vdk-jupyter: pin npm packages to previous version

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/common/DataJobDeploymentExtension.java
At the moment if a test fails to setup correctly it is almost impossible to figure out why it failed when investigating even 5 minutes later. 
With this PR I add a new assertion. instead of checking if a cron job for a data job is deployed I first check that the builder job completed successfully. 
If the builder fails, I include the logs in the stacktrace which means it is very easy to understand the root cause at a later date. 
Locally 
```
error building image: GET https://registry.hub.docker.com/v2/versatiledatakit/data-job-base-python-3.9/manifests/latest: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
org.awaitility.core.TerminalFailureException: AWS_REGION= …
```
> control-service: better error message

- specs/vep-1243-vdk-dag/README.md
What: Update VEP with information about the recently added functionality of execution type propagation - if the DAG job is executed manually, then its execution type is "manual" and consequently, all its orcehstrated jobs' type would be set to "manual". Same applies for "scheduled" executions.
Testing Done: Just update the VEP
Signed-off-by: Yoan Salambashev <ysalambashev@vmware.com>
> vdk-dag: update VEP about the execution type propagation

- README.md
Add getting started section for quickstart-vdk and ui. Section gives an overview on how to get started with just vdk-core and quickstart-vdk. It's meant as a brief overview and links to more in-depth guides, e.g. wiki and videos
README.md is the front page of the vdk project and it lacks a good getting started section. The current getting started section just links to the wiki.
n/a
docs
> docs: add getting started section for quickstart-vdk and ui

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package.json
What:
Pinned lumino/widgets to 1.33.0
Why:
Jupyterlab 4 is released some days ago, and it bumps the latest
version of rendermime-interface to 3.8.0, which is not compatible with
lumino 1.x
Because of that. we pinned render mime-interface to 3.6.3 which is best compatible with lumino 1.x and causes problems with lumina 2.x, I pinned the lumina to the lates stable 1.x version
This caused Build issues: 
27](https://github.com/vmware/versatile-data-kit/assets/87015481/9407ae37-519b-4224-b16c-776d62bd2374)
> vdk-jupyter: pin lumino/widgets package to version 1

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/hearbeat.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/heartbeat_base_test.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/heartbeat_test.py
A recent test run in CI broke with an error related to the staticmethod decorator https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4325250349
The latest heartbeat changes were tested on python3.11 They turned out not to be compatible with python 3.7
Remove the @staticmethod decorator from the test instantiation method (we're not using this method outside the runner)
Rename config memeber field of test classes to _config
Locally, in virtual environment using python 3.7
Bugfix
> vdk-heartbeat: fix python3.7 issue

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/common/DataJobDeploymentExtension.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-private-builder.properties
at the moment when the test fails we only know the status code and we have no idea of the details. 
Now we include the response body in the error message if there is an exception
locally
> control-service: print response body on error

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/common/JobExecutionUtil.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-private-builder.properties
When the job fails we want to see the error in the failure stacktrace. 
If the result is not 200 we include the response body in the error
Locally
> control-service: include details in error message

- projects/control-service/cicd/deploy-testing-pipelines-service.sh
- projects/control-service/cicd/testing-pipelines-service-values.yaml
This change increases the CPU and memory resource limits and requests for the test deployment of the Control Service .
The previous configuration with CPU and memory limits of 2000m and 500Mi respectively, and equal requests, has been changed. 
The new configuration sets the CPU limit to 2000m (2 cores), the memory limit to 4000Mi (approximately 4 GB), the CPU request to 1000m (1 core), and the memory request to 1000Mi (approximately 1 GB).
This change aims to improve the performance and stability of the test environment
> control-service: increase CICD deployment resources

- projects/control-service/cicd/deploy-testing-pipelines-service.sh
At present, we employ an authorization webhook in our CICD repository, directing to https://httpbin.org/post, which is designed to consistently return a 200 status. However, we've observed a high degree of instability in this arrangement, as documented in https://github.com/vmware/versatile-data-kit/issues/2081.
While it's advantageous to exercise this pathway during the VDK heartbeat process, it isn't essential. This coverage is sufficiently provided through our integration and unit tests, thereby reducing the necessity of the authorization webhook's stability.
> control-service: disable authorization on test/cicd deployment

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/schema/plugin.json
What:
Added a separator to the vdk menu:
Now:
Then:
Why: to group related menu items together
> vdk-jupyter: add separator to the VDK menu

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/TestJobDeployTempCredsIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-test.properties
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/AWSCredentialsService.java
what: added a couple of checks to the integration test to make sure authentication credentials are present.
why: better debugging of the test should it fail.
testing: n/a
> control-service: update ecr credentials integration test

- projects/control-service/cicd/.gitlab-ci.yml
we want faster feedback when a test fails and we want to use less resources in the cicd cluster
integration tests kill themselves if they have a single failure
locally
> control-service: fail tests fast

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/common/JobExecutionUtil.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-private-builder.properties
when the system is under load jobs often take a little over 5 minutes. 
Because we fail fast we won't waste needless time if the job goes into a failed state. 
Wait longer to get into a successful state 
CICD pipeline
> control-service: allow more time to reach a complete state

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/TestJobImageBuilderDynamicVdkImageIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-test.properties
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/SupportedPythonVersions.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application-prod.properties
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/SupportedPythonVersionsTest.java
As part of the initiative to support multiple python versions for data job deployments, we introduced new configurations through the `datajobs.deployment.supportedPythonVersions` and `datajobs.deployment.defaultPythonVersion` properties. This new configuration renders the old configurations through `datajobs.vdk.image` and `datajobs.deployment.dataJobBaseImage` essentially useless, as these are no longer used.
This change cleans up the old configurations and related code and tests, so that only the new configurations remain. A more descriptive list of the changes is as follows:
* The `DOCKER_VDK_BASE_IMAGE` and `DATAJOBS_DEPLOYMENT_DATAJOBBASEIMAGE` environment variables are removed, as they are not needed anymore.
* The templates associated with the above-mentioned env vars, …
> control-service: Clean up old data job configurations

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobDeploymentCrudIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-private-builder.properties
1. When the job fails we want to know the reason and not just the status
2. We are now using github to pull public images from to avoid docker hub throttling. In doing this the private image test was no longer using a private image. Now it is using a private image again. 
1. If the status code is not 200 log the response body
2. pull a private image
> control-service: better error logging and pull private image in private test

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/run-job-component.spec.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/RunJob.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/style/base.css
What:
Added more colouring to the cell 
See the numbering on the left side:
Now:
Then: 
Why: we received feedback form users that it would be more user-friendly to have that part of the cell coloured on fail, too
> vdk-jupyter: UI failing cell marks enhancement

- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-private-builder.properties
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/execution/JobExecutionServiceStartExecutionIT.java
We are seeing errors when the UI when using the latest version of control service
Write a test to check null values for startedby are supported. Also support null startedBy
Locally
> control-service: handle null started by value

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/handlers.py
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/vdk_ui.py
What: currently the server is broken in the use case when a user uses the extension with no rest_api_url set as env variable
With this changes we only look for the rest_api_url in specific cases for download, create, etc and for run and local development we do not look for it
Also we remove the use of rest_api_url in the handlers and move all of it to vdk_ui
Why: broken server
This is what the users get currently:
> vdk-jupyter: fix broken server in one use case

- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/cicd/deploy-testing-pipelines-service.sh
- projects/control-service/cicd/tag_image_dockerhub.sh
- projects/control-service/projects/pipelines_control_service/build.gradle
Re-deploying the helm chart from a CI pipeline that is not related to control service, e.g. frontend, requires a way to track control service docker images other than commit hashes.
Introduce latest and stable tags for control service docker images. Each docker image is tagged with latest in the publish_artifacts stage. Once the image is deployed in the test environment and tests have run, it is tagged with stable.
Ran new and changed scripts locally.
CI https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/882279167
Breaking change to CI
> control-service: introduce latest and stable tags for docker images

- projects/vdk-plugins/vdk-plugin-control-cli/src/vdk/plugin/control_cli_plugin/execution_skip.py
If you look at this ticket(https://github.com/vmware/versatile-data-kit/issues/2176) we can see that the error the customer is reporting is 
```
execution_skip.py:129  _skip_job_if_nec[id:gdp-execution-id-example-1685547120-ftlwb]- Error while checking for another data job excecution: unsupported operand type(s) for +: 'NoneType' and 'str' 
```
However its impossible to tell which line or varialbe is actually to blame. 
We need a full stacktrace
Print the full stacktrace when there is an error.
> vdk-plugin-control-cli: better error logging

- projects/frontend/data-pipelines/gui/projects/ui/src/app/app-config.service.ts
- projects/frontend/data-pipelines/gui/projects/ui/src/app/app.component.ts
- projects/frontend/data-pipelines/gui/projects/ui/src/app/getting-started/getting-started.component.ts
Missing configs cause the UI to fail on startup
Add null checks for the ignoreComponents and
ignoreRoutes configs
Locally
Feature, non-breaking
> frontend: add null checks for optional configs

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package-lock.json
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package.json
What:
Pinned typescript to an older version.
Why:
Some of the jupyterlab packages are not compatible with the newer versions.
> vdk-jupyter: pin tsc to specific version

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/frontend/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/frontend/cicd/.gitlab-ci.yml
- projects/frontend/cicd/ping_frontend_heartbeat_config.ini
- projects/frontend/cicd/publish_image_dockerhub.sh
Stacked on top of https://github.com/vmware/versatile-data-kit/pull/2138
The frontend is now part of quickstart-vdk.
On changes to the docker image, the helm chart needs to be redeployed. We need to make sure that the frontend is operational once the helm chart is deployed.
Trigger deployment of test control service on frontend changes merged into main
Ping the frontend in the test environment using heartbeat once control service is deployed
Tag the frontend image as stable if the test is successful
[Test pipeline](https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/894015566)
feature, non-breaking
> frontend: ping frontend on docker image release

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/job_config.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_job_config.py
Currently, there is code duplication between the vdk-core's JobConfig and vdk-control-cli's JobConfig. This is not sustainable, as when a change in one component is made, this change would need to be ported to the other component.
This change updates the vdk-core's JobConfig, as vdk-core is the main component of the Versatile Data Kit SDK. In a separate PR, the JobConfig of vdk-control-cli will be removed to remove the code duplication.
> vdk-core: Update JobConfig to match vdk-control-cli JobConfig

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/create.py
- projects/vdk-control-cli/src/vdk/internal/control/configuration/vdk_config.py
- projects/vdk-control-cli/tests/resources/sample_job_module/1_new_module_step.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_create.py
The purpose of this change is the following: some extensions to VDK might use vdk-control-cli as a dependency to create new jobs of a certain type through the JobCreate class. Currently, there is a way to specify what job is created, which is the VDK_CONTROL_SAMPLE_JOB_DIRECTORY, however this config variable is aimed at users which want to create a job template which is specific to their environment, and must be in the form of a path in their file system. An extension cannot use this to create a new sample job. This change allows for this by extending the JobCreate class' create method with a new parameter which can be passed when the method is called. This parameter must be a Python module which is to be included in the extension's source code and must contain the necessary job files …
> vdk-control-cli: Allow extensions to specify a sample job

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesServiceConfiguration.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/ControlKubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/DataJobsKubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceCancelRunningCronJobTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceIsRunningJobTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceStartJobWithArgumentsIT.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceStartNewCronJobExecutionTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
The KubernetesService is by far the biggest class in control-plane. 
It has much too much responsibilities. 
It is responsible for initialing the class that it will use. 
For example it is responsible for creating the k8s client. 
This is against the spring model where each component should be setup with all the components it needs. 
But also it makes it hard to test, because we can't pass in mock clients. 
In this PR I create the client outside of the kuberentesService and autowire it into the service. 
I also do this for the batch clients. 
In a previous PR(https://github.com/vmware/versatile-data-kit/pull/2207#discussion_r1221372123) it was pointed out that there is a bug in the kubernetesService where 500s from the cluster are misclassified as the job not existing. 
To write a test …
> control-service: make kubernetes service easy  to test.

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/PrivateBuilderDockerRepoIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
The KubernetesService class is massive. 
It is important to keep it clean and remove unneeded functions. 
delete functions that are not needed. 
CICD
> control-service: remove unneeded methods

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
We were creating a mock just to tell it to call the real methods. 
This is pointless. 
Use a real instance instead.
It results in less code. 
We are testing the product closer to how it will actually be used and it is easier for debugging. 
Locally
> control-service: use real class when testing instead of mock

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/job_config.py
Currently, the JobConfig class accepts only pathlib.Path as data_job_path. This, however, causes unnecesary warnings when a string is passed as job path.
This change updates the type annotation of the init to support both pathlib.Path and string as data_job_path.
> vdk-core: Accept string as job_path in JobConfig

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesServiceConfiguration.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/ControlKubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/DataJobsKubernetesService.java
BUG FIX: in a recent PR I made a change which points the data jobs deployer to the contrl namespace. 
I need to merge the fix asap. 
I will add a test shortly.  But I want to merge without a test to fix this ASAP. 
> control-service: data jobs points to correct namespace

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/job_config.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_job_config.py
When the logic from vdk-control-cli's JobConfig class was synced with the vdk-core's JobConfig, the `._get_contacts()` method logic was not properly ported, and this caused issues with config.ini files, where email addresses are not separated with `;`.
This change fixes the introduced bug. Additionally, the job config tests from the vdk-control-cli are  refactored and moved to the vdk-core.
Testing Done: New unit tests.
> [Bug fix] vdk-core: Fix _get_contacts in JobConfig

- .github/pr-title-checker-config.json
- .github/workflows/pr-title-checker.yml
In order to make sure we have a consistently applied component name in commit title I am adding this one. We do have pre-commit hook that checks this but it's not checking the PR title which is actually the one used to merge into main.
> versatile-data-kit: add pr title checker

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
As part of the initiative to support multiple python versions for data job deployments, a new configuration property, `python_version` was introduced. This configuration, however, was not initially added to the output of the `vdk config-help` command.
This change adds the `python_version` configuration to the JobConfigIniPlugin, as it is related to the config.ini file setup.
Testing Done:
Tested locally by running `vdk config-help` and verifying that the configuration is present in the output.
> vdk-core: Add python_version configuration to config-help

- projects/frontend/cicd/.gitlab-ci.yml
Building shared-components and data-pipelines simultaneously in CI causes the UI docker image to break.
More info https://jira.eng.vmware.com/browse/TAUR-6084
Disable the CI job that tags UI docker images as stable. quickstart-vdk uses the stable tag. Disabling tagging until the issue is solved makes sure that quickstart-vdk will not break because of changes we introduce in the meantime
n/a
Temporary bug mitigation
> frontend: disable stable tagging for ui docker images

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesServiceConfiguration.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/ControlKubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/DataJobsKubernetesService.java
to infer namespace if not set which is breaking the CICD since it tests
this logic.
Testing Done: locally ran the control service and saw correct values,
temporarily enabled deploy testing pipeline scripts on the branch and
saw it deployed the testing control service and the post deployment
test(vdk-heartbeat) succeeds (see https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/904026915)
> control-service: infer correct namespace if not set

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobMonitorCron.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
The Control Service has some pretty spammy logs that are making it
harder to pick the important things.
For example
```
?[30m2023-06-19 06:38:27,637?[0;39m ?[39mDEBUG?[0;39m [OpId:]
?[34mthread-3  ?[0;39m ?[33mc.v.t.s.locks.CustomLockProvider?[0;39m
Releasing lock watchJobs_schedulerLock
?[30m2023-06-19 06:38:27,637?[0;39m ?[39mDEBUG?[0;39m [OpId:]
?[34mthread-3  ?[0;39m ?[33mc.v.t.s.locks.CustomLockProvider?[0;39m Lock
watchJobs_schedulerLock is released
```
Those are not really needed in most cases . They still might be useful
if troubleshooting some issue with the locks so I am disabling them in
applicaiton.properties configuraiton (which can be overriden if needed)
```
?[30m2023-06-19 06:38:27,634?[0;39m ?[34mINFO ?[0;39m [OpId:]
?[34mthread-3  ?[0;39m …
```
> control-service: remove spammy logs 

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/DataJobsKubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/MockKubernetes.java
At the moment the KubernetesService class as much to much responsibilities. 
It is extended by DataJobsKubernetesService and controlKubernetesService class.
However it includes the logic that is unique to those individual classes also. 
For example only the datajobsKS creates or deploys cron jobs.
So in this PR I move those external facing functions to the dataJobsclass and fix the tests. 
I have not move alot of the more private functions to the datajobs class yet because alot of other tests need to be changed to achieve this as they are being tested using reflection and I want to keep the PRs small. 
Locally. 
> control-service: move cron jobs methods to the data jobs class

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
what: Added the location to temporary directory for data jobs as an env variable in the JobDepoyer class.
why: As discusses in this comment - https://github.com/vmware/versatile-data-kit/pull/2206#discussion_r1223049666
testing- n/a trivial change.
> control-service: add tmp dir path to image deployer's env variables

- projects/vdk-core/src/vdk/internal/builtin_plugins/debug/debug.py
The new version of pluggy's _result cannot be automagically converted to a dictionary which causes issues.
Added a custom string converter.
> vdk-core: adapt to recent pluggy changes

- projects/vdk-core/src/vdk/api/job_input.py
- projects/vdk-core/src/vdk/api/plugin/plugin_input.py
Incremental change for adding the secrets capability.
Since we have a somewhat circular dependecy with the vdk-test-utils plugin more changes - full secerts implementation and tests will follow in the next MR.
> vdk-core: add vdk sdk secrets api - part I

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/pyproject.toml
What:
pinned jupyterlab version to 3.6.3 in pyproject.toml
Why: not being pinned was cause of some installation issues since the npm package dependencies are pinned
> vdk-jupyter: pin jupyterlab to 3.6.3 in pyproject.toml

- projects/vdk-plugins/vdk-test-utils/src/vdk/plugin/test_utils/util_funcs.py
- projects/vdk-plugins/vdk-test-utils/src/vdk/plugin/test_utils/util_plugins.py
Incremental change for adding the secrets capability.
Adopt secrets interface in test utils.
Actual tests and full implementation will follow in next MR.
> vdk-test-utils: add vdk sdk secrets api - part 2

- projects/vdk-core/src/vdk/api/job_input.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/builtin_hook_impl.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/base_secrets_impl.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/cached_secrets.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/datajobs_service_secrets.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/inmemsecrets.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/secrets_api_plugin.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/secrets_config.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/secrets_router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/secretsnotavailable.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_context.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input.py
- projects/vdk-core/tests/functional/run/jobs/fail-job-secrets/1_step.py
- projects/vdk-core/tests/functional/run/jobs/secrets-job/10_copy_message.py
- projects/vdk-core/tests/functional/run/test_run_errors.py
- projects/vdk-core/tests/functional/run/test_run_secrets.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/job_secrets/test_cached_secrets.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/job_secrets/test_datajob_service_secrets.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/job_secrets/test_secrets_router.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/test_input_job_name_directory.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/test_substitute_query_params.py
- projects/vdk-plugins/.plugin-common.yml
- projects/vdk-plugins/build-plugin.sh
Incremental change for adding the secrets capability.
Add secrets implementation and tests in vdk-core.
> vdk-core: add vdk sdk secrets api - part III

- .github/dependabot.yml
Some libraries tend to have patch releases very often - like com.amazonaws:aws-java-sdk-sts latest patch upgrade is from 1.12.494 to 1.12.495
This is unnecessary. It's better to upgrade just on minor version automatically
> versatile-data-kit: ignore patch updates in dependabot

- projects/frontend/cicd/.gitlab-ci.yml
- projects/frontend/cicd/get_latest_shared_rc_version.sh
- projects/frontend/cicd/get_next_shared_rc_version_number.sh
- projects/frontend/cicd/install_data_pipelines.sh
- projects/frontend/cicd/publish_package_npm.sh
Linking shared-components to data-pipelines using npm fails to produce a working UI docker image. This is a CI-only issue.
Introduce rc-versions for @versatiledatakit/shared
On a successful build of shared, and rc-version is pushed to npm registry
The data-pipelines build pulls the latest rc-version when running, instead of linking to the local installation of shared
Versioning schema follows semver
{major}.{minor}.{patch}-rc.{rc-number}
The rc-number is incremented based on the latest rc-number for the pipeline-id. This helps avoid conflicts between different pipelines running builds for shared
Regular shared versions are tagged with latest in npm registry
Rc versions are tagged with rc, so they don't get pulled accidentally when running npm install
Ran a build in CI and tested that the …
> frontend: use versatiledatakit/shared rc-builds for data-pipelines

- projects/vdk-control-cli/requirements.txt
- projects/vdk-control-cli/setup.cfg
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/secrets.py
- projects/vdk-control-cli/src/vdk/internal/control/main.py
- projects/vdk-control-cli/src/vdk/internal/control/rest_lib/factory.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_secrets.py
Incremental change for adding "secrets" command to the cli.
Also adopting the latest version of the control service client api.
I'm aware of the code duplication and I'll refactor once I get this running end-to-end.
> vdk-control-cli: add vdk secrets command

- .gitlint
- .pre-commit-config.yaml
As part of discusison between contributors we decided we are going to remove the git lint precommit hook as it hurts more than it helps.
We also use PR description as a commit mesage on main so those are more important than the commit message in the working branch.
> versatile-data-kit: remove gitlint pre-commit hook

- projects/frontend/data-pipelines/gui/e2e/integration/explore/data-jobs/data-jobs.spec.js
- projects/frontend/data-pipelines/gui/e2e/integration/manage/data-jobs/data-jobs.spec.js
- projects/frontend/data-pipelines/gui/e2e/support/pages/base/data-pipelines/data-pipelines-base.po.js
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/base-grid/data-jobs-base-grid.component.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/data-job-page.component.html
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-explore/components/grid/data-jobs-explore-grid.component.html
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-explore/components/grid/data-jobs-explore-grid.component.spec.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-manage/components/grid/data-jobs-manage-grid.component.html
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-manage/components/grid/data-jobs-manage-grid.component.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/model/grid-config.model.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/shared/components/data-grid/column-filter/column-filter.component.ts
Changed navigation in Data Jobs list from `navigateToUrl` to `locationToURL`, because telemetry events PageView are sent when Angular router navigation occurs. We want to stop sending telemetry PageView events on every filter apply.
Fix for Browser pop states while User is in Data Jobs list and going backward/forward and state from URL is propagated to the component.
Removed icon **new** from Executions tab in Data Job view.
Fix for some e2e tests.
More info about `navigateToUrl` and `locationToURL`:
- `navigateToUrl` initiates Browser navigation through Angular `Router` service which on the other hand triggers router change and component resolving through Angular Router mechanism that at the end fires `NavigationEnd` event and sends telemetry event PageView
- `locationToURL` initiates …
> frontend: Fix navigation in Data Jobs

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/dimension/scd1/00-dimension-scd1-definition.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/00-fact-snapshot-definition.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/snapshot/00-fact-snapshot-definition.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/versioned/00-versioned-definition.py
- projects/vdk-plugins/vdk-impala/tests/functional/template_regression_test.py
A week ago pydantic released 2.0 version which is a breaking version .
https://docs.pydantic.dev/dev-v2/migration Fortunately pydantic has also released a tool bump-pydantic which automatically upgraded the code. That's very useful.
Also in tests use `cli_assert(not res.exception, res)` instead of assert to print more details about the job failure.
> vdk-impala: upgrade code to support pydantic 2.0

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
When upgrading the vdk helm chart, helm will not pull the latest image when using a meta tag (latest, stable, etc.). Helm treats tags as first-class citizens and doesn't look at the image sha. If the tag hasn't changed, then, from helm's POV, the chart hasn't changed either. This blocks us from using latests/stable tags for our test environment deployment. It also means quickstart-vdk will not use the latest images if it's upgraded.
This is default helm behavior:
https://github.com/helm/helm/issues/5696
Note that `--recreate-pods` is no longer a thing.
https://github.com/helm/helm/issues/8271
Add timestamp labels to the control-service deployment.yaml This way, the helm chart will always be different, which means it will always be re-deployed.
Labels are already added to the frontend …
> control-service: add timestamps to helm chart

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/job_config.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_job_config.py
This change disables the checks for config.ini files when creating instances of JobConfig. This is needed because if someone tries to execute a local vdk run help (`vdk run --help`) depending on their distribution's plugins, this may result in errors.
> vdk-core: [Hot Fix] Stop throwing exceptions if config.ini not present

- projects/vdk-plugins/vdk-impala/README.md
Why:
Enhance vdk-impala README.md
More details explained in #1361
What:
-Describe what quality checks are
-Provide example use
Signed-off-by: Stefan Buldeev sbuldeev@vmware.com
> vdk-impala: Update README.md for vdk-impala

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/jupyter_sample_job/10_notebook.ipynb
This change adds a specific notebook step to the Jupyter sample job which contains the necessary initialization cell.
Testing done: local
> vdk-jupyter: Sample job notebook step

- projects/vdk-plugins/vdk-smarter/.plugin-ci.yml
- projects/vdk-plugins/vdk-smarter/README.md
- projects/vdk-plugins/vdk-smarter/requirements.txt
- projects/vdk-plugins/vdk-smarter/setup.py
- projects/vdk-plugins/vdk-smarter/src/vdk/plugin/smarter/openai_plugin_entry.py
- projects/vdk-plugins/vdk-smarter/tests/jobs/sql-job/10_create_table.sql
- projects/vdk-plugins/vdk-smarter/tests/jobs/sql-job/20_populate_table.sql
- projects/vdk-plugins/vdk-smarter/tests/test_sql_review.py
Very simple plugin that reviews every query and scores it using OpenAI models. The purpose is to provide easy visibility into queries and their quality for the user. Though technically they could potentially use chatGPT themselves or static code analysis, that is less likely and and harder for them
A) because some queries are generated dynamically
B) Many queries could be part of a job and take (development) time to check. 
C) the prompt engineering is something that takes time as well and tuning as well. The prompts could be tuned by community pretty well over time.
Inside an enterprise, this enables central data team to establish best practices around SQL with proper review model themselves as well.
This is a POC (a Pre-Alpha development status as defined in …
> vdk-smarter: introduce simple open ai plugin

- projects/vdk-core/cicd/Dockerfile-vdk-base
- projects/vdk-core/cicd/deploy-base-vdk-image.sh
Currently, all vdk-related docker images (mainly quickstart-vdk) are built with python3.7, because the python base image is hard-coded into the Dockerfile (Dockerfile-vdk-base). This causes issues if images for different python versions are to be built.
This change adds more flexibility, by updating the Dockerfile to accept build argument with the python image that is to be used for building the vdk image. It also updates the shell script that builds and releases the vdk images to read a new environment variable, VDK_BASE_PYTHON_IMAGE, which indicates which python version is to be used.
Testing Done: Locally executed the script and verified that the passed python base image propagates to the Dockerfile.
> vdk-core: Allow different python versions for vdk docker images

- projects/vdk-plugins/vdk-impala/requirements.txt
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/versioned/00-versioned-definition.py
Ensure vdk-impala works with pydantic 1.0 as this is still used and libraries do not support the new version.
In hindsight, I should have pinned to 1.0 only. But I did not and it's a good idea to support the new version otherwise at some point it will cause conflicts and problems as other libraries adopt 2.0 of pydantic
Testing Done: installed locally pydantic 1.0 . The Gitlab CI is testing with 2
- `pip install pydantic==1.*`
- ../build-plugin.sh (from vdk-impala dir) 
- verified the test exited successfully. 
I toyed with the idea of adding a test for pydanitc 1.0 but it would require some refactoring of hte plugin framework to allow that and it's not that urgent as the changes are fairly small.
> vdk-impala: support also pydantic 1.0

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/serverRequests.ts
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/handlers.py
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/vdk_ui.py
What:
1.removed some unneeded code
2. fixed some issues with deployment from jupyter
3. fixed server fail on not present config.ini 
Why: 
1. there was an error in the server that was failing when config.ini is not present, I put that in try catch 
2. the deploy was failing because of enabled flag
> vdk-jupyter:  fix server error in jupyter ui and remove unneeded code

- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/base-grid/data-jobs-base-grid.component.ts
- projects/frontend/shared-components/gui/projects/shared/src/lib/core/navigation/services/navigation.service.ts
- projects/frontend/shared-components/gui/projects/shared/src/lib/core/system-events/event/models/event.codes.ts
- projects/frontend/shared-components/gui/projects/shared/src/lib/core/system-events/public-api.ts
- projects/frontend/shared-components/gui/projects/shared/src/lib/core/url-state-manager/url-state.manager.ts
* Fix router event handling in DataJobsBaseGridComponent
* Distinguish between Browser popped state and changed Team
* fix will affect only case when there is external Team selector dependency like `DataPipelinesConfig['manageConfig'].selectedTeamNameObservable`
* Added new SystemEvent with id `"SE_Location_Change"` bound to constant `SE_LOCATION_CHANGE` that is publicly exposed through `"@versatiledatakit/shared"`
* with the new core SystemEvent there is provided interface for its payload
* event is fired whenever method locationToURL in URLStateManager is invoked and condition allows location change
* Small refactor: introduced interface for SystemEvent payload about event with id `"SE_Navigate"`
Tested with Supercollider in local dev environment and everything works as expected.
Test …
> frontend: Fix router event handling in base class

- projects/frontend/cicd/.gitlab-ci.yml
https://github.com/vmware/versatile-data-kit/issues/2332
This issue has been resolved, so we can re-enable stable tagging for the frontend. The change lets us use our CI/CD pipeline to deliver updates to the frontend and quickstart-vdk with sufficient release confidence.
Enable stable tagging for the frontend docker image. This lets us deliver updates for the
frontend as part of quickstart-vdk.
Note: The stable tag is pulled each time quickstart-vdk is restarted and the helm chart it uses re-deployed
The stable tagging job ran as part of the CI before, we just didn't have sufficient testing around
the frontend image, so we disabled it. We use the same script for tagging with latest, so
it should be fine.
> frontend: enable stable tagging

- projects/frontend/cicd/.gitlab-ci.yml
Since the e2e tests have been moved to the pre_release_test stage, the pipeline might fail under certain conditions, e.g. changes to CI-related files
https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/927407847
Trigger e2e tests on all shared and data-pipelines locations. The behavior should be the same as for the build stage
CI
Bugfix
> frontend: remove e2e tests restrictions

- projects/vdk-core/src/vdk/internal/builtin_plugins/notification/notification_base.py
Currently, when a target email address is checked if exists, we set a dummy sender `"whatever"`. This works in cases, where the smtp server does not enforce validation checks on the sender. It does not, however, work in cases when the smtp server uses TLS (like Office365).
In such cases, the check of the target email address fails with Status `503: Bad sequence of commands`, because the `.mail("whatever")` method call sets the **FROM** field to *mail FROM:<whatever>*, and this causes the smtp server to return `501 5.1.7 Invalid address`.
This change replces `"whatever"` with the actual sender address used to send the email notifications (set through the `VDK_NOTIFICATION_SENDER`) environment variable.
Testing Done:
Create a sample email script to first better understand the error, and …
> vdk-core: Set sender when checking if email exists

- .gitlab-ci.yml
- cicd/.gitlab-ci-lib.yml
- cicd/docker_parse.sh
- cicd/docker_push_vdk.sh
- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/projects/job-base-image-secure/publish-job-base-image.sh
- projects/control-service/projects/job-base-image/publish-job-base.sh
To avoid issues with docker limits sometimes it may be beneficial to use
ghcr.io instead for example in our CICD or in vdk-server .
This change publishes some images to both docker.io and ghcr.io
The GitLab CI configuration is changed to include a shared library for common CI/CD tasks. 
Two new scripts have been added for parsing and pushing Docker images. 
These scripts are now being used in the build process to push images to multiple registries in.
Testing Done: Temporarily changed the pipeline to push images on PR and verified images are pushed to both correctly. See it in https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/927292918
> control-service: push to multiple registries

- projects/vdk-plugins/vdk-plugin-control-cli/src/vdk/plugin/control_cli_plugin/control_service_secrets_client.py
- projects/vdk-plugins/vdk-plugin-control-cli/src/vdk/plugin/control_cli_plugin/secrets_plugin.py
- projects/vdk-plugins/vdk-plugin-control-cli/src/vdk/plugin/control_cli_plugin/vdk_plugin_control_cli.py
- projects/vdk-plugins/vdk-plugin-control-cli/tests/jobs/secrets-job/10_secrets_step.py
- projects/vdk-plugins/vdk-plugin-control-cli/tests/jobs/secrets-job/config.ini
- projects/vdk-plugins/vdk-plugin-control-cli/tests/test_secrets_plugin.py
add the secrets command to the pluging-control-cli
> vdk-plugin-control-cli: add secrets command

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/02-handle-quality-checks.py
- projects/vdk-plugins/vdk-impala/tests/functional/template_regression_test.py
Why:
Currently when the insert template is used with quality checks it only appends data to the staging table without truncating it at any moment. This will most probably lead to duplicated data on the following run, because old source data will be already in the staging table before appending the new one.
More details explained in
#1361
What:
-Adding truncate statement before the data is being inserted in the staging table to ensure that no leftover data from previous runs is left.
Signed-off-by: Stefan Buldeev sbuldeev@vmware.com
> vdk-impala: Truncate table before inserting data

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/alertmanager.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_alertmanager.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
what: added alertmanager.yaml to helm chart templates, added configurable properties in values.yaml that correspond to the alertmanager.yaml template.
why: users of control-service can configure Prometheus alert manager through a helm chart instead of manually in the k8s cluster. More information on configuration properties: https://docs.openshift.com/container-platform/4.10/rest_api/monitoring_apis/alertmanagerconfig-monitoring-coreos-com-v1alpha1.html#specification
testing: helm chart validations.
cd into the 'versatile-data-kit/projects/control-service/projects/helm_charts' folder and run the following commands (make sure prometheus-operator is installed on minikube cluster and you have updated the charts, and enabled alertmanager from values.yaml before doing so):
`minikube start` …
> control-service: add helm template for alertmanager

- examples/online-exhibition/README.md
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/properties.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_properties.py
Remove the set-secret option for the properties command as we now have separate secrets command for handling sensitive data.
Update example/documentation.
Update tests.
> vdk-control-cli: remove set-secret for properties

- projects/vdk-plugins/vdk-jupyter/.plugin-ci.yml
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/README.md
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/pyproject.toml
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/setup.py
We need to publish the image to a pip registry so others can consume it and setup is easy and doesn't require cloning the source code
Most plugins are installed using the same command. which is declared in a common gitlab file. 
For building this plugin I didn't think it made sense to reuse that code as building jupyter is a little more complicated. 
So the release is totally new code. 
I published to the registry and installed locally. 
Commands: 
```
pip install -U vdk_jupyterlab_extension
jupyter lab
```
Make sure the UI has the correct panels
> vdk-jupyter: publish image to pip registry

- projects/control-service/projects/base/build.gradle
- projects/control-service/projects/base/src/test/resources/application.properties
- projects/control-service/projects/helm_charts/pipelines-control-service/example-vdk-options.ini
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/VdkOptionsReaderTest.java
- projects/control-service/projects/pipelines_control_service/src/test/resources/vdk_options/test_vdk_options.ini
- projects/control-service/projects/versions-of-external-dependencies.gradle
We no longer use influx , removing leftovers.
Closes https://github.com/vmware/versatile-data-kit/issues/1452
> control-service: remove unused dependency influxdb

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
what: added configurable mail.smtp.host property in the helm charts
why: since this was quite an old property it was previously hardcoded in the control-service application.properties and I missed updating it when we introduced authenticated email functionality.
testing: helm chart validations
> control-service: add configurable smtp host property

- projects/frontend/cicd/.gitlab-ci.yml
- projects/frontend/cicd/publish_image_docker.sh
Continuation of https://github.com/vmware/versatile-data-kit/pull/2381
> frontend: push docker images to both repos

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_vault.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Add Vault configuration entries to the Control Service helm chart.
> control-service: Add helm chart entries for Vault Configuation

- .gitlab-ci.yml
- cicd/notify.sh
In order to set up CI on-call for vdk, visible and reliable notifications are required.
The notifications should alert on pipeline failure and provide the necessary information for troubleshooting.
Call an incoming webhook for a custom slack application on pipeline failure. This sends a message to the corresponding channel.
Ran in pipeline and sent notification to debug channel.
Note that the env variable for the notification hook will have to be changed after this is merged.
https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/914912201
> support: slack notification on pipeline failure

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/secrets/service/vault/TestVaultJobSecretsServiceIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/secrets/service/vault/VaultTestSetup.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/vault/VaultConfiguration.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- specs/vep-1493-vault-integration/README.md
Switch to using Approle for Vault Authentication rather than Tokens.
Approle authentication is more suitable for long running applications,
like the Control Service. 
https://developer.hashicorp.com/vault/docs/auth/approle 
https://developer.hashicorp.com/vault/tutorials/auth-methods/approle
Update service code, VEP, Tests and helm charts.
> control-service: switch to Approle Vault authentication

- CONTRIBUTING.md
For new contributors it could be confusing all those projects and plugins if they just need/want to contribut to a single peace.
Although VDK is a mono repo it is not that clear without some documentation. Hence adding some documentation
> versatile-data-kit: clarify structure of VDK repo

- projects/vdk-plugins/.plugin-common.yml
- projects/vdk-plugins/build-plugin.sh
- projects/vdk-plugins/vdk-greenplum/.plugin-ci.yml
- projects/vdk-plugins/vdk-greenplum/requirements.txt
- projects/vdk-plugins/vdk-greenplum/setup.py
- projects/vdk-plugins/vdk-impala/.plugin-ci.yml
- projects/vdk-plugins/vdk-impala/requirements.txt
- projects/vdk-plugins/vdk-kerberos-auth/.plugin-ci.yml
- projects/vdk-plugins/vdk-kerberos-auth/requirements.txt
- projects/vdk-plugins/vdk-postgres/.plugin-ci.yml
- projects/vdk-plugins/vdk-postgres/requirements.txt
- projects/vdk-plugins/vdk-postgres/setup.py
- projects/vdk-plugins/vdk-trino/requirements.txt
There were overall 3 issues that needed to be fixed in the build of those   plugins: 
The first one is 2.0 major release of pytest-docker (https://pypi.org/project/pytest-docker/#history) which we use for starting docker container in some plugin tests . This impacted us because 
1. pytest-docker change default command from `docker-compose` to `docker compose` (no dash) 
2. But the library we use (docker-compose) installs only `docker-compose` command (with a dash)
--
The other problematic library is the installation of docker-compose itself :). 
docker-compose depends on PyYaml and PyYAML is having the following issue: https://github.com/yaml/pyyaml/issues/724 (in short a recent release of Cython 3.0 broke PyYAML)
As a workaround, we can pin `PyYAML==5.3.1` And also remove eager …
> vdk-plugins: fix build of multiple plugins

- projects/vdk-core/src/vdk/internal/builtin_plugins/notification/notification.py
- projects/vdk-core/tests/functional/run/test_run_notifications.py
Currently, when a data job is executed and notifications are enabled, the resulting email does not contain the data job name and instead says `None`. Example:
```
[success][data job run] None
Dear Versatile Data Kit user,
Last run of your data job *None* has succeeded.
You can find full logs of the job execution here.
The sender mailbox is not monitored, please do not reply to this email.
Best,
```
This change fixes this behaviour by setting the Notification Plugin to attach to the
finalize_job hook, get the job name from the JobContext provided by the hook, and
save as an instance variable. The name of the job is then passed to the vdk_exit hook,
which is responsible for sending the notifications.
Testing Done: Locally executed a test data job and verified that the email notification …
> [bug fix] vdk-core: Add job name to state

- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Prevent integer translation to a fraction in helm chart.
> control-service: prevent integer translation in helm chart

- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/projects/job-base-image-secure/Dockerfile-data-job-base
- projects/control-service/projects/job-base-image-secure/publish-job-base-image.sh
- projects/control-service/projects/job-builder-secure/Dockerfile.python.vdk
Why
Right now, the base image is lacking many libraries necessary for installing Python libraries, such as `gcc`.
What
After installing Python libraries, most of these extra libraries are not required anymore, so we deleted them once the installation was done. Also, move all commands in a single Docker layer in order to reduce the image size (~150 MB uncompressed). This helped make the image smaller, and we also installed the Oracle library only when needed for jobs that had it listed in their requirements.txt file.
Removed the docker-slim since it does not fit in the new building strategy. We will improve the image cleanup step in the future.
Testing Done:
Built images locally.
Command:
```
docker buildx build -f versatile-data-kit/projects/control-service/projects/job-builder-secure/Dock …
```
> control-service: install necessary dependencies to job builder secure

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/vault/VaultConfiguration.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
Remove the default value of the vault integration token, to reduce confusion when configuring vault.
> control-service: remove default vault token

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
what: Fixed a typo in the deployment helm chart - wrong camel case in deployment.yaml - https://github.com/vmware/versatile-data-kit/blob/ffdee8bac07e3718299eb10e024c7319179b3b93/projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml#L951
why: The typo was preventing users from adopting the read only root filesystem through the helm charts.
testing: n/a
> control-service: fix typo in helm chart read only root filesystem property

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package-lock.json
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package.json
What: 
Pinned the word-wrap package to version 1.2.4.
Why: 
All versions of the package(<1.2.4) word-wrap are vulnerable to Regular Expression Denial of Service (ReDoS) due to the usage of an insecure regular expression within the result variable.
> vdk-jupyter: pin word wrap package to newer version because of security issue

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli.py
- projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli_impl.py
- projects/vdk-control-cli/src/vdk/internal/control/utils/output_printer.py
- projects/vdk-control-cli/tests/vdk/internal/control/utils/test_output_printer.py
What:Introduced an enhanced feature, the MemoryPrinter, it conserves text for future use, instead of instant printing. Along with this, adapted the JobDeploy class to receive a printer object instead of an OutputFormat enum.
Why:
The inclusion of MemoryPrinter caters to use cases where an output needs to be stored for later representation, such as in a Jupyter UI. This modification in the JobDeploy class enables the printer object's use beyond JobDeploy: the printer can be initialised first, utilised within JobDeploy, and then accessed again to retrieve the stored output. This stops the need for accessing private fields within JobDeploy and promotes better coding practices.
> vdk-control-cli: pass the printer class in JobDeploy creation and add additional memory printer

- specs/vep-2448-vdk-run-logs-simplified-and-readable/README.md
Part of the run logs improvement initiative https://github.com/vmware/versatile-data-kit/issues/2408
https://github.com/vmware/versatile-data-kit/issues/2451
https://github.com/vmware/versatile-data-kit/issues/2448
Create VEP document and fill out Summary, Motivation and Goals sections
n/a
docs
> specs: VEP-2448: VDK Run Logs: Simplified And Readable

- projects/frontend/data-pipelines/gui/e2e/plugins/helpers/job-helpers.plugins.js
Fix bug in Cypress custom plugin that provides executions for Data Jobs e2e tests.
Array was used as integer in one calculation, and because of it there were some unexpected results in some scenarios.
Applied fix uses Array length for calculate the number of left executions that should be executed serial.
> frontend: Fix bug in Cypress plugin

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/upload/JobUploadValidator.java
Why
We have received a lot of complaints from your internal customers.
What
Exclude .pyc files from the data job validation process.
> control-service: exclude pyc files from dj validation

- projects/frontend/cicd/.gitlab-ci.yml
`frontend_publish_ui_image` extends `.images:dind:docker-push-to-vdk-repos` but since both provide `before_script` the`frontend_publish_ui_image` overwrites the one provided by `.images:dind:docker-push-to-vdk-repos` (which adds the docker_push_vdk.sh script to the PATH) 
This caused failures in the pipeline like this https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/947073454
The fix is to remove  before_script from the `frontend_publish_ui_image` job and move all to `script` 
Testing Done: https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/947441104
> frontend:  fix pushing images

- .gitlab-ci.yml
- projects/vdk-control-cli/.gitlab-ci.yml
- projects/vdk-core/.gitlab-ci.yml
- projects/vdk-heartbeat/.gitlab-ci.yml
- projects/vdk-plugins/vdk-control-api-auth/.plugin-ci.yml
- projects/vdk-plugins/vdk-csv/.plugin-ci.yml
- projects/vdk-plugins/vdk-dag/.plugin-ci.yml
- projects/vdk-plugins/vdk-gdp-execution-id/.plugin-ci.yml
- projects/vdk-plugins/vdk-ingest-file/.plugin-ci.yml
- projects/vdk-plugins/vdk-ingest-http/.plugin-ci.yml
- projects/vdk-plugins/vdk-ipython/.plugin-ci.yml
- projects/vdk-plugins/vdk-jobs-troubleshooting/.plugin-ci.yml
- projects/vdk-plugins/vdk-lineage-model/.plugin-ci.yml
- projects/vdk-plugins/vdk-lineage/.plugin-ci.yml
- projects/vdk-plugins/vdk-logging-format/.plugin-ci.yml
- projects/vdk-plugins/vdk-meta-jobs/.plugin-ci.yml
- projects/vdk-plugins/vdk-notebook/.plugin-ci.yml
- projects/vdk-plugins/vdk-plugin-control-cli/.plugin-ci.yml
- projects/vdk-plugins/vdk-properties-fs/.plugin-ci.yml
- projects/vdk-plugins/vdk-server/.plugin-ci.yml
- projects/vdk-plugins/vdk-smarter/.plugin-ci.yml
- projects/vdk-plugins/vdk-snowflake/.plugin-ci.yml
- projects/vdk-plugins/vdk-sqlite/.plugin-ci.yml
- projects/vdk-plugins/vdk-test-utils/.plugin-ci.yml
- projects/vdk-plugins/vdk-trino/.plugin-ci.yml
In GitLab CI, you can specify certain settings globally, affecting the entire CI/CD pipeline. These are called "global keys. There is a global key that defines a specific Docker image (image:)
Now, the problem arises when we define the same global key in multiple YAML files within the repository. Since global keys are not scoped to specific files, they can clash and cause conflicts. When GitLab processes the CI configuration, it reads all the YAML files and applies the settings in the order they are imported.
If the same global key appears in different files, the last occurrence of that key in the import order will overwrite the previous ones. This behavior can lead to unintended consequences. For example, we might encounter unexpected Docker images being used for certain jobs.
To prevent …
> versatile-data-kit: remove global image from Gitlab CI

- projects/vdk-plugins/vdk-jupyter/cicd/build.sh
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/README.md
Add build.sh for streamlined first-time development setup of vdk-jupyterlab-extension
> vdk-jupyter: introduce cicd/build.sh

- specs/NNNN-template/README.md
Improving VEP recommendations to make sure we include expected deliverables as part of the VEP
> specs: try to make it clear what deliverables should be

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_configuration.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_error_handler.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_plugin.py
Currently, the retries and backoff seconds are hard-coded in the ImpalaErrorHandler, which is not ideal, as there might be users who want to have specific values for these properties.
This change adds two new configuration variables, `IMPALA_RETRIES_ON_ERROR` and `IMPALA_ERROR_BACKOFF_SECONDS`, which are to be used for configuring how many times a failed query is to be retried, and how big the backoff should be.
> [vdk-plugin] vdk-impala: Make error retries and backoff configurable

- projects/vdk-plugins/vdk-sqlite/src/vdk/plugin/sqlite/ingest_to_sqlite.py
- projects/vdk-plugins/vdk-sqlite/tests/test_sqlite_plugin.py
Trying to create columns with whitespace in the name and inserting data in them using vdk-sqlite resulted in error.
This was most evident in examples like csv-ingestion
https://github.com/vmware/versatile-data-kit/wiki/Ingesting-local-CSV-file-into-Database
- Add double quotes around column names with whitespace in them when the table is created.
- Replace named placeholders in insert query with question marks
- Convert payload from dicts to lists to pass it to above query
- Check if payload headers match column names before it's passed
Unit tests
Bugfix
> vdk-sqlite: support whitespace in column names

- projects/control-service/projects/job-base-image-secure/Dockerfile-data-job-base
Fix for the following error during data job building:
```
File "/usr/local/lib/python3.9/ctypes/__init__.py", line 8, in <module>
from _ctypes import Union, Structure, Array
ImportError: libffi.so.8: cannot open shared object file: No such file or directory
[end of output]
```
> control-service: add libffi to secure base job image

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/job_config.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_job_config.py
Currently, the vdk-core's JobConfig does not require the presense of a config file in a data job's repository. This works in general, but not for the vdk-control-cli's use-cases, where the presense of the config file is mandatory.
This change adds a `should_fail_missing_config` flag to JobConfig, which can be used when the presense of the config file is necessary. If the flag is set to `True`, and the config file is missing in the data job's folder, a VdkConfigurationError will be raised.
Testing Done: Added test
> vdk-core: Add flag to JobConfig in case config file is required

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_error_handler.py
- projects/vdk-plugins/vdk-impala/tests/impala_error_handler_test.py
- projects/vdk-plugins/vdk-impala/tests/impala_handle_hdfs_error_test.py
Currently, if a data job executes a query, which fails due to metadata issue, the ImpalaErrorHandler
logic tries to refresh or invalidate the metadata, and re-try the query. If the job has only read
access to the table, an authorization error is raised and the job failes with User Error. This should
not happen, as the refresh/invalidate operation is initiated by vdk, not the user.
This change updates the error handler logic by adding try/except blocks around refresh/invalidate
metadata operations, so that errors that arise from these operations do not cause job failures.
Testing Done: Added test
> vdk-impala: Handle errors on refresh/invalidate metadata

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/secrets/service/vault/TestVaultJobSecretsServiceIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/vault/VaultJobSecretsService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/secrets/vault/VaultJobSecretsServiceTest.java
Fix a bug which prevents the delete-all-secrets cli command to work.
> control-service: allow delete-all-secrets command

- projects/control-service/projects/job-builder-secure/Dockerfile.python.vdk
Why
Currently, the base secure image does not contain the required libraries for `pyodbc` Python package.
What
Installed required native dependencies.
Testing Done
Locally through the following command:
```
docker buildx build -f versatile-data-kit/projects/control-service/projects/job-builder-secure/Dockerfile.python.vdk -t test-image-tag . --build-arg job_githash=localhsh1 --build-arg base_image=registry.hub.docker.com/versatiledatakit/data-job-base-python-3.8-secure:latest --build-arg job_name="data_job_name" --progress=plain
```
> control-service: support for pyodbc

- projects/vdk-core/requirements.txt
- projects/vdk-core/src/vdk/internal/builtin_plugins/builtin_hook_impl.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/query_command_plugin.py
- projects/vdk-core/tests/functional/cli/test_query_command_plugin.py
Add vdk sql-query command which will use the same database as the rest of the SQL interfaces (SQL steps, job_input methods)
This will replace the per-db commends like vdk impala-query, vdk sqlite-query which are just problematic.
This would enable to generalize a lot of the tutorials/examples we have which currently give impression they can be used only wiht "sqlite" (sqlite-query) or trino. Which is primary driver for doing the change now.
The command would be used in functional tests where you want to query the default db without needing ot create a job for that.
The command for now is hidden (hidden feature) since there are a few TODOs that would be resolved in subsequent PRs.
> vdk-core: add vdk sql-query command

- projects/vdk-plugins/vdk-control-api-auth/requirements.txt
- projects/vdk-plugins/vdk-control-api-auth/setup.py
- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/authentication.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_get_auth_user.py
Add to Authentication library a method to get_authenticated_username.
The purpose of this method is ot be used during debugging , in logging and in telemetry use cases.
> vdk-control-api-auth: add get_authenticated_username

- projects/vdk-plugins/vdk-audit/src/vdk/plugin/audit/audit_plugin.py
- projects/vdk-plugins/vdk-audit/tests/functional/jobs/os-remove-command-job/10_os_remove_command_job.py
- projects/vdk-plugins/vdk-audit/tests/functional/test_audit_plugin.py
The logic in the `_audit()` method filters the forbidden events and detects if an executed event is allowed or not. However, the way it matches the events is by partial string match (the `event in not_permitted_event` part). This means that if a forbidden event is, e.g., `os.removexattr` and the event that is passed to the method is `os.remove`, there will be a match, because `os.remove` is a sub-string of `os.removexattr`.
With this change, the `_audit()` method switches to exact string match when filtering for forbidden events, in order to avoid situations where unexpected events are matched.
Testing done: Added test
> vdk-audit: [bug fix] Fix incorrectly detected event

- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/cicd/deploy-testing-pipelines-service.sh
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/frontend/configmap.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/frontend/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/frontend/secret_pull_pipelines_control_service_img.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/frontend/service.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
See Issue #2539
To test this (and future helm changes) more robustly I am adding a new job to which would run on MR and would run the same script to deploy the helm chart in kubernets but as dry run .
> control-service: Ability to disable VDK UI in Helm

- projects/vdk-control-cli/src/vdk/internal/control/job/sample_job/config.ini
This change adds the `python_version` property to the config.ini file of the sample data job that is returned when a user executes `vdk create -n <job-name> -t <team-name>`. The property is commented out, as it is used only if a user wants to set a python version different from the default one.
Testing Done: Executed `vdk create -n my-test-job -t my-team` locally, and verified that the python_version property is present in the generated data job's config.ini file.
> vdk-control-cli: Add python_version to sample config.ini

- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/build.gradle
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/authorization/provider/AuthorizationProvider.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/authorization/webhook/AuthorizationWebHookProvider.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/webhook/PostCreateWebHookProvider.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/webhook/PostDeleteWebHookProvider.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/webhook/WebHookService.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/authorization/webhook/AuthorizationWebHookProviderTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/webhook/BaseWebHookProviderTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/webhook/PostCreateWebHookProviderTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/webhook/PostDeleteWebHookProviderTest.java
Currently, the Control Service lacks the capability to authenticate against the WebHook API. A specific customer of ours requires authentication for the WebHook API utilizing the same access token passed by the client to the Control Service APIs.
Incorporated logic to forward the oAuth2 access token to the WebHook API.
Unit and integration tests.
> control-service: enable WebHook authentication

- projects/frontend/data-pipelines/gui/e2e/support/pages/manage/data-jobs/executions/data-job-executions.po.js
`find('[data-cy=data-pipelines-job-executions-type-container]')` causes the test to fail if it doesn't find any job executions. It should be returning an empty list instead.
Introduce logic that returns an empty list
Ran e2e tests locally
Ran e2e tests in CI
Bug fix
- Fix one bug in e2e tests for Data Job Executions
> frontend: Fix for e2e test

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/dimension/scd1/02-handle-quality-checks.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/02-handle-quality-checks.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/snapshot/02-handle-quality-checks.py
Why:
We were facing issues for large sized tables sporadically when using the processing templates with specified quality checks.
The issues appear when we try to move the data from the staging table (where the quality checks were already performed) into the target table. The absence of "COMPUTE STATS" statement against the staging table was causing failures when trying to select data from it due to hitting query limits. Before submitting this PR here are the checks that have been done in order to take that decision:
-A job that was processing a large table with quality checks defined was ran 45 times from which only 17 were successful and other were failures due to the issue mentioned above. After that a "Compute stats" statement was added against the staging table before trying to …
> vdk-impala: Introduce COMPUTE STATS statements

- projects/vdk-plugins/.plugin-common.yml
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/base_authenticator.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/minikerberos_authenticator.py
- projects/vdk-plugins/vdk-kerberos-auth/tests/test_kerberos.py
This change adds _run_coroutine function to ensure proper execution of a get_tgt coroutine, even if called within an already running event loop in asyncio (which in principal is not allowed)
This is happening when the plugin is invoked within a jupyter notebook which runs within a async event loop started by tornado server. And this causes following errors:
```
Traceback (most recent call last):
File
"/opt/conda/lib/python3.7/site-packages/vdk/plugin/kerberos/minikerberos_authenticator.py",
line 90, in _kinit
loop.run_until_complete(get_tgt())
File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 563, in
run_until_complete
self._check_runnung()
File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 526, in
_check_runnung
'Cannot run the event loop while another loop is …
```
> vdk-kerberos-auth: enable auth to work inside a running asyncio event loop

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/pyproject.toml
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/__init__.py
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/config.py
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/handlers.py
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/oauth2.py
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/tests/test_oauth2.py
This is adding the server part of Oauth2 authentication process.
It adds 1 more APIs: `/login`
When called it without "code" query paramter, it will start the authentication proces as per OAuth2 standard .
We are using only native app workflow with PKCE (RFC 7636) because we cannot really secure the server side so we cannot reliably use client secret.
When called with "code" query paramter it will finish the process and exchange the code for access token (and refresh token) and safe it in VDK storage.
This change add integration with jupyter configuration. This way the extension can be configured more natively using jupyter configuration mechanism.
So now configuration can be set in any of the ways juptyer server supports - https://jupyter-server.readthedocs.io/en/latest/users/configuratio …
> vdk-jupyter: add oauth2 authentication implementation

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/resquests.spec.ts
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/show-dialog.spec.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/CreateJob.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/DeployJob.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/DownloadJob.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/RunJob.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/serverRequests.ts
What: Added run result message to the deployment result dialog ( if run before deployment is selected) 
Current dialog: 
Why: It used to not contain the successful run message which left the suers with confusion around whether really the run was successful 
> vdk-jupyter: add run result to the deployment result dialog

- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/auth_config.py
- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/authentication.py
- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/base_auth.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_api_token_auth.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_authorization_code_auth.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_core_auth.py
- projects/vdk-plugins/vdk-control-api-auth/tests/test_get_auth_user.py
This is refactoring the credentials cache storage system to make it more reusable . Particulary I want to reuse it to get corrected authenticated user in telemetry later.
- We are providing explcit interface for credentials cache intead of using Union of classes
- Implement SingletonInMemoryCredentials cache to enable different parts of the program to easily access and reuse the same credentials.
- Added method read_cached_access_token_only and use it in get_authenticated_username() to make it easier to record user using vdk even if his token has expired.
- Default credentials_cache to LocalFolderCredentialsCache which is more commonly used.
- Deprecate cache_locally in favour of explicitly passing the credential cache instance, this is better design pattern.
> vdk-control-api-auth: vdk credentials cache refactoring

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/standalone_data_job.py
- projects/vdk-core/tests/functional/run/test_run_standalone_data_job.py
Standalone Data Job ignores directory provided steps and doesn't run them (at least not currently).
But if a plugin adds more steps , this logic does not work and it runs the steps adde by the plugin. In our case vdk-notebook add new notebook steps and they are run . This causes when a new notebook is created and job_input is intiailzied , during initializaiton it tries to run all steps in the notebook.
This fixes this issue by adding explicit function after initialize_job that replaces all steps with noop step.
> vdk-core: make sure standalone data job doesn't run steps

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/oauth2.py
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/tests/test_oauth2.py
InMemAuthConfiguration was removed in previous change but those imports were in another plugin leftovers causing failures now.
> vdk-jupyter: remove unnecessary imports that cause errors

- projects/vdk-plugins/vdk-control-api-auth/src/vdk/plugin/control_api_auth/base_auth.py
In case user cannot refresh their access token currently we simply show error "KeyError: 'access_token'" with some stack trace which makes it practically impossible for the user to know what to do.
```
Traceback (most recent call last):
File
"/opt/conda/lib/python3.7/site-packages/vdk/internal/cli_entry.py", line
140, in vdk_main
program_name=program_name,
File "/opt/conda/lib/python3.7/site-packages/pluggy/_hooks.py", line
433, in __call__
return self._hookexec(self.name, self._hookimpls, kwargs,
firstresult)
........
File
"/opt/conda/lib/python3.7/site-packages/vdk/plugin/control_api_auth/base_auth.py",
line 167, in __exchange_refresh_for_access_token
self.update_access_token(json_data[AuthRequestValues.ACCESS_TOKEN_KEY.value])
KeyError: 'access_token'
```
This changes that to …
> vdk-control-api-auth: add better error message for refresh token failure

- projects/vdk-core/src/vdk/api/plugin/plugin_registry.py
- projects/vdk-plugins/build-plugin.sh
Plugy realease of 1.3 on 25th of August introduced a changing renaming pluggy._callers._Result to pluggy.Result.
It can be found in the list of changes between 1.2 and 1.3 : https://github.com/pytest-dev/pluggy/compare/1.2.0...1.3.0
As we rely on that as a type for the Result object , it breaks vdk.
This changing is adopting the pluggy change
> vdk-core: adopt pluggy 1.3

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/ConvertJobToNotebook.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/ui-tests/tests/convert-job.spec.ts
Try to split out in one more section the notes after the conversion.
Also make them collapssable so they do not appear as so much text and user can click to see more info if they want.
You can see how it looks here: 
And with the text expanded:
> vdk-jupyter: optimize ConvertToJobNotebook notes

- .gitignore
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/initVDKConfigCell.ts
It's better not to provide link to git repo source code. Links to source code are not best documentation. But also job_input could be changed through plugins in which case it won't be accurate.
Notebook `help(xxx)` is much more suitable.
Remove the unnecesary warning. it's not critical and even if by mistake they mark the current cell , they'd quickly find out t problem when using vdk run
I also made the cell non-editable. During user testing, users were trying to edit it and this may cause potential issues as it's not expected
output of help(job_input) looks like that:
> vdk-jupyter: improve init message

- README.md
I am adding a "poster image" or placeholder image to all the videos (which really is the first frame of the video so simply edit each video through canva to add first 0.1 seconds with still image. 
I also edited a bit the getting started and ingestion videos while I was doing that.
For easier review, you can inspect the new readme at https://github.com/vmware/versatile-data-kit/tree/person/aivanov/readme 
This is how it renders for me: 
I tried 2 options since i didn't like the first 
Option 1: https://github.com/vmware/versatile-data-kit/assets/2536458/0d683633-a254-47c6-8792-1312c9f4fa36
Option 2: https://github.com/vmware/versatile-data-kit/assets/2536458/6da9e963-17da-4a58-abcc-dc13738800d9
> versatile-data-kit: add poster image to all the videos

- projects/vdk-plugins/vdk-ipython/src/vdk/plugin/ipython.py
- projects/vdk-plugins/vdk-ipython/tests/test_plugin.py
If job name is not explcitly provided we should infer it correctly from the path name.
Also I extended ipython test coverage to cover most of the other untested job input methods
> vdk-ipython: infer correctly job name and add more tests

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/pyproject.toml
Adding extra requirements with some pretty good jupyter lab extensions that would go well with VDK Data Jobs.
They are optional and installed only if user install Jupyter with
```
pip install vdk-jupyterlab-extension[opinionated]
```
I've tested the first three and they work pretty well. Left TODOs for some that I've started testing but did not work well or not had enough time but we can consider in the future. 
**The first one adds execution time on each cell** 
**The second one adds nice table with filtering and sorting capabilities** 
**The third one allows to see declared variables and inspect them:**
> vdk-jupyter: add opionated jupyter extension as extra

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/StatusButton.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/style/vdkDialogs.css
Common usability issue with starting operations is that when you click the operation (e.g Run) nothing happens.
This is fairly cheap temporary fix to at least show the status dialog and ask the user to explicitly close it.
Longer term solution should be planned where we will not only show that operaiton is runnign, but show how long time it reemians, where it is currently (e.g what is in case of vdk run), show logs (if user wants to) and so on. But that's a bigger story.
https://github.com/vmware/versatile-data-kit/assets/2536458/7c35a01c-7e51-42be-b4ae-270ca475910b
> vdk-jupyter: show status on starting new operation

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/execution_environment.py
In order to have better visibiltiy into where vdk is running ExecutionEnvironment now track host and cpu/memory/disk information.
> vdk-core: provide more info about the machine vdk is running on

- projects/vdk-plugins/vdk-ipython/README.md
- projects/vdk-plugins/vdk-ipython/requirements.txt
- projects/vdk-plugins/vdk-ipython/setup.py
- projects/vdk-plugins/vdk-ipython/src/vdk/plugin/ipython/__init__.py
- projects/vdk-plugins/vdk-ipython/src/vdk/plugin/ipython/common.py
- projects/vdk-plugins/vdk-ipython/src/vdk/plugin/ipython/job.py
- projects/vdk-plugins/vdk-ipython/src/vdk/plugin/ipython/sql.py
- projects/vdk-plugins/vdk-ipython/tests/conftest.py
- projects/vdk-plugins/vdk-ipython/tests/test_job_control.py
- projects/vdk-plugins/vdk-ipython/tests/test_plugin.py
- projects/vdk-plugins/vdk-ipython/tests/test_sql.py
To provide a seamless user experience for data professionals using VDK
Notebooks for SQL queries. The feature allows them to execute SQL
queries (and VDK SQL steps in the future) right within the notebook, visualize the
results in an interactive grid, and resuse managed SQL connections
through VDK. 
Leveraged the ipyaggrid package to display SQL query results in a
user-friendly, interactive grid. Also added auto-initialization for VDK
job and managed its connections for SQL execution. Opted for ipyaggrid
over other options like qgrid due to its flexibility and feature set.
Other evaluated were  `itables` (not as rich), `beakers` (could not get
it to work), `qgrid` (could not get it to work)
Ipyaggrid is optional because it's not clear if every notebook installation would support (and …
> vdk-ipython: add support for %%vdksql magic command

- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_router.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/job_input_error_classifier_test.py
As part of the VDK Run Logs initiative, we should increase test coverage for the job_input_error_classifier
Add unit test for error caused by external library used by vdk internal components
Add unit test for error caused by passing custom iterator to job_input
Add unit test for error caused by passing custom iterator using external libraries to job_input
Tests that do not pass have been commented and appropriate ticket opened to address them
https://github.com/vmware/versatile-data-kit/issues/2620
Misc: Flip the assertion parameters passed, because they were the wrong way around.
Ran unit tests locally
New feature (non-breaking change which adds functionality)
> vdk-core: add more unit tests to for job_input_error_classfier

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/schema/plugin.json
What: added separator between run and login in the VDK menu
Why: these two operations are not in the same class and should not be in the same area
> vdk-jupyter: VDK menu fix

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_log_config.py
what:
Data jobs won't fail if logging fails to initialize.
why:
If logging level is set to cloud and the configuration connects to an external service logging service such as log insight which happens to be unavailable to whole cloud cluster of data jobs will experience an outage. Instead of failing the data job, execution should now proceed with local logging on DEBUG level.
testing:
added unit test.
> vdk-core: change jobs behavior when logging unavailable

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
- projects/vdk-core/src/vdk/internal/cli_entry.py
When we log the stack trace, we're logging exceptions that we've already logged during execution. This increases the logs length by about 30%.
Add flag that disables/enables logging the stack trace on exit code 1
Ran vdk locally with a failing data job
> vdk-core: add log stacktrace flag

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package-lock.json
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package.json
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/create-job-component.spec.ts
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/download-job-component.spec.ts
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/CreateJob.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/DownloadJob.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/VdkTextInput.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/style/vdkDialogs.css
What: Updated "Create" and "Download" functionalities to default to the Jupyter root directory.
And also added tool tip that gives more information about the input itself. The information only shows up when we hover the question mark element next to the input label.
Why: Initial implementations utilised the current working Jupyter directory. However, usability tests indicated that this approach was causing confusion. To enhance user experience, the default has been changed to the root directory.
> vdk-jupyter: change  Create and Download default path 

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/config.py
- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
Currently, it is not possible to set a specific python version, with which a test data job to be deployed. As a result the heartbeat can be executed only against the default python version specified in the Control Service configuration.
This change adds the ability to set a specific python version in the ini file for a test case.
Testing Done: Executed vdk-heartbeat with a simple test config.ini and verified that the test data job was deployed with thhe correct python version.
> vdk-heartbeat: Add python version configuration

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/pyproject.toml
Latest release of traitlets (5.10) is breaking jupyter server - https://github.com/jupyter/notebook/issues/7048  which is causing jupyter server to fail to start
So we are pinning temporarily to 5.9 to fix that.
> vdk-jupyter: pin traitlets to 5.9

- projects/control-service/projects/job-base-image-secure/Dockerfile-data-job-base
- projects/control-service/projects/job-builder-secure/Dockerfile.python.vdk
what:
Adding amazon rds ca certificates to secure job image
why:
Data job users require ca certificates to connect to amazon databases
testing:
building images locally and inspecting certificate output:
List truncated because of 100+ certificates
`38.45 subject=C = US, O = "Amazon Web Services, Inc.", OU = Amazon RDS, ST = WA, CN = Amazon RDS eu-west-1 Root CA RSA4096 G1, L = Seattle
38.46 subject=C = US, O = "Amazon Web Services, Inc.", OU = Amazon RDS, ST = WA, CN = Amazon RDS eu-central-1 Root CA RSA4096 G1, L = Seattle
38.46 subject=C = US, O = "Amazon Web Services, Inc.", OU = Amazon RDS, ST = WA, CN = Amazon RDS eu-north-1 Root CA RSA2048 G1, L = Seattle
`
> control-service: add amazon rds ca certificates to data job image

- projects/vdk-plugins/vdk-jupyter/cicd/build.sh
It seems we are mostly using npm in CI and local setup shoudl resemble CI if possible
> vdk-jupyter: use npm in build.sh

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/RunJob.tsx
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/VdkTextInput.tsx
What:
Refined RunJobDialog and VDKTextInput components. Ensured the arguments input uses VDKTextInput and streamlined RunJobDialog state management.
Why:
The old approach had sizing inconsistencies between the arguments and path inputs. Converting arguments input to VDKTextInput clears its association with VDK data, enhancing visibility and cohesion. Additionally, removing the unnecessary inputWidth state from RunJobDialog makes the code leaner and more manageable.
> vdk-jupyter: fix arguments input size

- projects/vdk-core/src/vdk/api/plugin/plugin_utils.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/config/job_config.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/connection_hooks.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/impl/router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_connection_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_cursor.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_utils.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_properties/datajobs_service_properties.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_properties/properties_router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/datajobs_service_secrets.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/secrets_router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/cli_run.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/data_job.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/execution_results.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input_error_classifier.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/templates/template_impl.py
- projects/vdk-core/src/vdk/internal/core/errors.py
- projects/vdk-core/src/vdk/internal/util/utils.py
- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/job_input_error_classifier_test.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/test_cli_run.py
- projects/vdk-core/tests/vdk/internal/core/test_errors.py
- projects/vdk-plugins/vdk-csv/tests/functional/test_csv_plugin.py
As part of the run logs initiative, we should add classification attributes to exceptions that are handled in vdk. These attributes are used for easier error classification and will help us enrich the vdk exception class family, so we can pass more info to our users.
This is not possible without separating the error logging and error reporting mechanisms, so some refactoring was required.
The main changes are in `errors.py`. All other changes (tests, other modules) are a result of changes in `errors.py`. The changes for specific plugins are out of scope for this PR due to compatibility issues.
Base vdk exceptions now have two new attributes - `to_be_fixed_by` and `type` (names subject to change). These help the error classification functions determine who to blame when an exception is …
> vdk-core: separate error logging, error reporting and error classification

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/ConvertJobToNotebook.tsx
What:
Fixed the conversion operation to add additional cell which runs the run function coming from .py step. 
Before:
After: 
Why:
To execute the python code in the function vdk-notebook requires it to be called (unlike how vdk generally works with .py steps).
The reason the bug was not caught is that it is only tested in the e2e tests and they are not yet added to the ci/cd.
> vdk-jupyter: fix conversion

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/service/deploy/DataJobDeploymentCrudITV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DeploymentModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DataJobsSynchronizer.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentNotificationHelper.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentProgress.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentServiceV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployerV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/DataJobsKubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DeploymentMonitor.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/repository/JobDeploymentRepository.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentNotificationHelperTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageDeployerTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/monitoring/DeploymentMonitorIT.java
Why
As part of the VEP-2272, we have to introduce a process to synchronize the data jobs from the database to the Kubernetes.
What
The initial implementation of the Data Jobs Synchronizer provides methods for synchronizing jobs between the database and Kubernetes. It introduces new classes suffixed with 'V2' to improve the separation of the old and new approaches.
Please take note that this is just the first phase of implementation. The following enhancements are planned for future PRs:
- We will annotate the method DataJobsSynchronizer.synchronizeDataJobs() with @Scheduled.
- Improved exception handling will be integrated.
- An additional deployment table will be introduced to effectively manage the desired and actual deployment state.
- More tests will be included in subsequent updates. …
> control-service: data jobs synchronizer initial implementation

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/ConvertJobToNotebook.tsx
> vdk-jupyter: Update ConvertJobToNotebook doc

- projects/vdk-plugins/vdk-dag/tests/test_dag.py
Tests started failing after https://github.com/vmware/versatile-data-kit/pull/2666 Most likely due to not wrapping errors in UserCodeError anymore
Pass the dag name to the dag validation test fixture
Expect just one request in the dag, as we do a GET request to fetch the job info before doing validation
Ran test suite locally
Bugfix
> vdk-dag: fix failing validation tests

- projects/vdk-control-cli/src/vdk/internal/control/command_groups/login_group/login.py
- projects/vdk-control-cli/src/vdk/internal/control/rest_lib/factory.py
- projects/vdk-plugins/airflow-provider-vdk/vdk_provider/hooks/vdk.py
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/remote_data_job.py
cache_locally was deprecated in favour of credentials_cache
Since the credentials_cache default is LocalFolderCredentialsCache we can leave the default 
This is really 3 changes in single PR - but the change would be merged in 3 separate commits for each plugin
Testing Done: existing tests passed, showing no regression
> vdk-dag, vdk-control-cli, airflow-provider-vdk: step using deprecated field

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/vdk_ui.py
Use the newly provided JOB_RUN_SUMMARY_FILE_PATH and JobSummaryParser to get information about job summary which can be shown in Notebook UI.
This passes the path explicitly to vdk run as environment variable making sure not hidden depencies would break things in the future.
> vdk-jupyter: print summary output to temp dir

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/convert_job.py
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/tests/test_convert_job_directory_processor.py
We are using `re.search(r"def run\(job_input", content)` which is very bad practice. Never use regex unless you have a official contract or specification that promises the regex will work.
The regex breaks in so many cases :
- put some space anywhere `def run<space>(job_input)` ,
- def run is defined on multiple lines
- coments .
- def run ins in string literal and not really a method
- and probably much more I cannot think of.
In general rule, I really think it's bad idea to do parsing (regex is type of parsing) without implement strict contract and specification.
The solution to the problem here  simple fortunately. It is to use Python's ast (Abstract Syntax Tree) module to parse Python code.
> vdk-jupyter: fix bug in detecting run functions

- projects/vdk-control-cli/requirements.txt
A test is failing due to changes in the werkzeug API.
https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/5203253935
```
Traceback (most recent call last):
File "/Users/mdilyan/Projects/versatile-data-kit/projects/vdk-control-cli/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
execute(self.server.app)
File "/Users/mdilyan/Projects/versatile-data-kit/projects/vdk-control-cli/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
application_iter = app(environ, start_response)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/mdilyan/Projects/versatile-data-kit/projects/vdk-control-cli/venv/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 189, in application
resp = f(*args[:-2] + (request,))
^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
> vdk-control-cli: pin werkzeug to version 2.3.8 or less

- projects/control-service/projects/pipelines_control_service/src/test/resources/filter-job/requirements.txt
https://github.com/vmware/versatile-data-kit/security/dependabot/23 
It alserts on using old version of urllib3. So updating it.
> control-service: resolve dependabot alert

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DeploymentModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentServiceV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployerV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/model/DesiredDataJobDeployment.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DeploymentMonitor.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/repository/DesiredJobDeploymentRepository.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/db/migration/V20231002143000__add_column_status_to_desired_data_job_deployment_table.sql
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/JobsServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceV2TestIT.java
Why
As part of VEP-2272, we need to introduce a process for synchronizing data jobs from the database to Kubernetes. In the event of a data job deployment failure (due to user or platform errors), the current implementation attempts to deploy the data job during every synchronization cycle.
What
We have added a data job deployment status field to the desired_data_job_deployment table. This status is used to determine whether the deployment failed in the previous cycle and should be skipped in the current one. The failed deployment status can be reset by invocation of updateDeployment API event without a job code change (it will be implemented as part of https://github.com/vmware/versatile-data-kit/pull/2731/files).
This is just the third phase of implementation. The following enhancements …
> control-service: data job synchronizer error handling

- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/exception.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_utils.py
- projects/vdk-core/src/vdk/internal/core/errors.py
- projects/vdk-core/tests/functional/ingestion/test_ingest_chain.py
- projects/vdk-core/tests/functional/ingestion/test_payload_verification.py
- projects/vdk-core/tests/functional/run/jobs/fail-job-ingest-iterator/1_step.py
- projects/vdk-core/tests/functional/run/test_run_errors.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_base.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_router.py
- projects/vdk-core/tests/vdk/internal/core/test_errors.py
Replacing generic exception names like DomainError, UserCodeError, , and PlatformServiceError with more domain-specific exceptions (in this case the domain being ingestion) can offer differnet benefits
See https://github.com/vmware/versatile-data-kit/issues/2682
VdkConfigurationError is not changed as it's pretty clear for now. I am wondering if it still might not be better ot have IngsetionConfigurationException but could not decide and omit it from this change.
TODO: I still need to test with "real" like job that fails in some of those ways and see what is the difference in logs and in how the exception can be handled
> vdk-core: create ingestion exceptions

- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/job_input_error_classifier_test.py
In https://github.com/vmware/versatile-data-kit/issues/2620 the described use scenario is when user using
`send_tabular_data_for_ingeston(rows=BrokenIterator())`
The user-provided broken iterator is called within plaform code and the question is: is it recognized as  an user error?
It is correct. There was a test already covering that scenario [test_run_user_error_fail_job_ingest_iterator](https://github.com/vmware/versatile-data-kit/blob/634febe37cab75ffc36cd88ef186b7c910b8e03c/projects/vdk-core/tests/functional/run/test_run_errors.py#L77)
The test ErrorClassifierTest are not needed because the logic that classifies that type of error as user error is not done by stack trace but by handling the exception directly [here](https://github.com/vmware/versatile-data-kit/blob/634febe37cab75ffc36 …
> vdk-core: tests passing custom iterator to ingestion methods

- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_router.py
There would some code duplication in ingester router which even cause send_object_for_ingestion and send_tabular_data to handle method different which was subtle issue.
Refactor to remove the code duplication and reduce the number of lines as a whole.
> vdk-core: remove code duplication in ingestion router

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_error_handler.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_helper.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/template_arguments_validator.py
- projects/vdk-plugins/vdk-impala/tests/functional/template_regression_test.py
As part of https://github.com/vmware/versatile-data-kit/issues/2680
I have Removed the log_and_throw and log_and_rethrow patterns from  vdk-impala.
Also renamed ResolvableBy to ErrorType and ResolvableByActual to ResolvableBy in most places (it is not removed in some places because it requires vdk-core modifications, those changes will be introduced in later PRs)
> vdk-impala: introduce new error handling

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DataJobsSynchronizer.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DataJobsSynchronizerTest.java
Why
DataJobsSynchronizer does not catch ApiException.
What
We handled ApiException in DataJobsSynchronizer.
Testing done:
Unit tests.
> control-service: Enhance Exception Handling for DataJobsSynchronizer

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DataJobsSynchronizer.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentServiceV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/model/DesiredDataJobDeployment.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DeploymentMonitor.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/repository/DesiredJobDeploymentRepository.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/db/migration/V20231005163000__add_column_is_user_initiated_to_desired_data_job_deployment_table.sql
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceV2TestIT.java
Currently, the new deployment mechanism sends notifications every time, lacking the ability to send them only when the user initiates the deployment.
We modified the method to send notifications exclusively when deployments are initiated by the User, by incorporating a check for DeploymentStatus.NONE which represents user-initiated deployments.
Unit tests.
> control-service: user-initiated deployment notifications

- projects/vdk-plugins/vdk-jupyter/.plugin-ci.yml
We had problems with the build: 
>      Building wheels for collected packages: y-py
>         Building wheel for y-py (pyproject.toml): started
>         Building wheel for y-py (pyproject.toml): finished with status 'error'
>         error: subprocess-exited-with-error
>       
>         × Building wheel for y-py (pyproject.toml) did not run successfully.
>         │ exit code: 1
>         ╰─> [9 lines of output]
>             Running `maturin pep517 build-wheel -i /usr/local/bin/python --compatibility off`
>             🔗 Found pyo3 bindings
>             🐍 Found CPython 3.8 at /usr/local/bin/python
>             error: package `y-py v0.6.2 (/tmp/pip-install-f40jsas6/y-py_d9865fc7363a49f684156a1cc9619ea2)` cannot be built because it requires rustc 1.72 or newer, while the currently …
> vdk-jupyter: fix ci/cd 

- projects/vdk-core/src/vdk/internal/builtin_plugins/job_properties/datajobs_service_properties.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_properties/exception.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/datajobs_service_secrets.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/exception.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/job_properties/test_properties_router.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/job_secrets/test_secrets_router.py
The only one in properties and secrest that make sense is about the write preprocessing sequence. The other are configuraiton errors for which we (at least for now) keep using VdkConfigurationException
> vdk-core: domain specific properties/secrets exceptions

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DataJobsSynchronizer.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DataJobsSynchronizerTest.java
Currently, we don't have the ability to schedule the deployment synchronization process.
We have scheduled the process. Only one CS instance at a time can run this process.
Unit tests.
> control-service: enable scheduled execution for data jobs' synchronizer

- projects/vdk-control-cli/.gitlab-ci.yml
What: The generated tests.xml XML report can not be found in the current working directory. This change fixes the directory where the XML report would be outputted to.
Why: Fix the CI/CD.
Testing Done: The pipeline is green. The tests.xml file is found.
> vdk-control-cli: fix CI/CD tests

- projects/vdk-plugins/vdk-test-utils/src/vdk/plugin/test_utils/util_plugins.py
IngestIntoMemoryPlugin is used in tests to mock ingestion targets.
It would be useful the method name to be configruable so it can be used as different methods
> vdk-test-utils: make IngestIntoMemoryPlugin method configurable

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DeploymentMonitor.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/repository/DesiredJobDeploymentRepository.java
We observed the following post-deployment test failure: https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/5192553226. 
This change is the culprit https://github.com/vmware/versatile-data-kit/pull/2714
It’s the first pipeline that started having this issue https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/5210024385
The previous change for the control service that triggered the same tests passed fine. There weren’t any changes to heartbeat or control-cli in between, as far as I can tell. You can see from the logs that the schedule is written to the data job table for the previous control service change that triggered the same tests.
https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/1020826286 …
> control-service: fix control service post deployment test

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/cli_run.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/data_job.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
Before - User error logged twice: https://pastebin.com/raw/7dgqRpnN
After - User error logged once: https://pastebin.com/raw/unqBCK59
We'd like to remove repeating log statements from data jobs, e.g. the same exception getting logged in steps, step processing and job result
Pass exceptions from job steps to the execution result. Check the execution result for exceptions and raise the exception if it's not related to skipping steps.
This provides a single exit point for logging exceptions.
Tested locally by running some broken data jobs
CI
> vdk-core: pass exceptions from data job steps in results

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobDeploymentCrudIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DataJobsDeploymentController.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/exception/ValidationException.java
Why:
Unlike the old deployment approach, the new one propagates job resources to the job deployment process.
What:
Added validation of job resources during job deployment. If any job resources, such as CPU or memory, are provided, the job deployment will fail.
Testing done:
Integration tests.
> control-service: job resources validation on job deployment

- projects/vdk-plugins/vdk-audit/src/vdk/plugin/audit/audit_config.py
The list of forbidden events that the vdk-audit plugin looks for, is unreasonably restricted by default. Most of the operations would not affect the security of a cluster or other client operations.
This change removes some events.
Testing Done: N/A, configuration change
> vdk-audit: Clean up some audit events

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/service/deploy/DataJobDeploymentCrudITV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DataJobsDeploymentController.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/exception/ValidationException.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobsService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DataJobsSynchronizer.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentServiceV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployerV2.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/db/migration/V20231013120000__drop_constraint_fk_data_job_name_ref_data_job_from_actual_data_job_deployment_table.sql
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DataJobsSynchronizerTest.java
Why:
As part of VEP-2272, we need to introduce a process for synchronizing data jobs from the database to Kubernetes. Currently, the process lacks the ability to delete deployments asynchronously.
What:
We have introduced an asynchronous method for deployment deletion. It is based on the logic that if the desired deployment is null and the actual deployment is not null, the process performs deployment deletion.
Testing done:
Integration tests.
> control-service: asynchronous deployment deletion

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobDeploymentCrudAsyncIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DataJobsDeploymentController.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DataJobDeploymentControllerReadTest.java
what: When calling the deploymentList method of the DataJobsDeploymentController class and a job without deployments exists, the API will now return an empty list instead of 404.
why: Recent changes in https://github.com/vmware/versatile-data-kit/pull/2800 refactored the method to return 404 instead of empty list in this situation, however this breaks the post deployment test.
testing: added unit test.
> control-service: fix post deployment test

- projects/vdk-core/tests/functional/ingestion/jobs/ingest-multiple-threads-job/ingest_multi_threads.py
- projects/vdk-core/tests/functional/ingestion/test_run_ingest.py
The IIngester methods (send_xxx_for_ingestion) should allow being called from multiple threads. But it's never explicitly tested. This test is far from perfect. Testing something is thread safe is not very easy. 
But it's good to have it because
A) it's an indication of this thread-safe contract for future developers  
B) If there is some serious regression this should catch it even if it doesn't catch some more subtle regressions.
> vdk-core: test ingestion with multiple threads

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/data_job.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
- projects/vdk-core/src/vdk/internal/core/errors.py
Stacked on top of https://github.com/vmware/versatile-data-kit/pull/2774
Different exception message formats are required for different use cases, e.g. CLI vs. Jupyter vs. Cloud
Add a flag to vdk-core configuration that lets the user pick the formatter. Initial choices are "pretty" and "plain". The plain
format should be good enough for Jupyter and Cloud deployments. The pretty formatter is enabled by default, because CLI needs to work out of the box.
Formatters have been exported to fuctions in errors.py, which makes it easy to write a new formatter if necessary. Exceptions are logged only at the exit point in the `run` method, which is also where formatting takes place.
Caused some config and user errors in local runs and looked at the output
CI tests
Signed-off-by: …
> vdk-core: add error formatter configuration

- projects/vdk-plugins/vdk-structlog/.plugin-ci.yml
- projects/vdk-plugins/vdk-structlog/README.md
- projects/vdk-plugins/vdk-structlog/requirements.txt
- projects/vdk-plugins/vdk-structlog/setup.py
- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/constants.py
- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/filters.py
- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/formatters.py
- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/structlog_plugin.py
- projects/vdk-plugins/vdk-structlog/tests/jobs/job-using-a-plugin/10_dummy.py
- projects/vdk-plugins/vdk-structlog/tests/test_plugin.py
As part of VEP-2448, we'd like to make structured logging pluggable
Create a vdk-structlog plugin. The plugin allows users to configure logging metadata and logging format. It also works with bound loggers.
Installed the plugin and ran a data job locally with different configurations
feature/non-breaking
- https://github.com/vmware/versatile-data-kit/issues/2802
- https://github.com/vmware/versatile-data-kit/issues/2803
- https://github.com/vmware/versatile-data-kit/issues/2810
- https://github.com/vmware/versatile-data-kit/issues/2811
- https://github.com/vmware/versatile-data-kit/issues/2812
- https://github.com/vmware/versatile-data-kit/issues/2813
- https://github.com/vmware/versatile-data-kit/issues/2814
> vdk-structlog: create structured logging plugin

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentServiceV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployerV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DeploymentMonitor.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/repository/ActualJobDeploymentRepository.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/repository/DesiredJobDeploymentRepository.java
The data job synchronizer was stuck in an infinite redeployment loop for all data jobs, occurring every minute. This issue was caused by the random generation of job resources in the cron job definition, where SHA-512 hashing is performed. When we had two instances of the control service running, they generated different SHA codes due to differences in resources order.
```
resources: class V1ResourceRequirements {
limits: {cpu=Quantity{number=0.500, format=DECIMAL_SI}, memory=Quantity{number=1000000000, format=DECIMAL_SI}}
requests: {cpu=Quantity{number=0.500, format=DECIMAL_SI}, memory=Quantity{number=1000000000, format=DECIMAL_SI}}
}
```
```
resources: class V1ResourceRequirements {
limits: {memory=Quantity{number=1000000000, format=DECIMAL_SI}, cpu=Quantity{number=0.500, …
```
> control-service: fix infinite redeployment

- projects/vdk-core/tests/functional/run/jobs/job-using-risky-templates/01_read_csv.py
- projects/vdk-core/tests/functional/run/jobs/template-csv-risky/01_read_empty_csv.py
- projects/vdk-core/tests/functional/run/test_run_templates.py
As part of our run logs initiative, we stopped wrapping non-vdk errors in vdk errors. This should result in errors coming from libraries, templates, etc. being propagated to user code. Users should then be able to handle those errors. This behaviour has not been tested, however.
Add a functional test that creates a template and runs it. The templates tries to read an empty csv using pandas, which results in a pandas-specific exception. The exception is then handled in a data job that executes the template.
Ran the test locally
> vdk-core: test exception propagation to user code

- projects/vdk-plugins/vdk-greenplum/tests/test_ingest_to_greenplum.py
- projects/vdk-plugins/vdk-postgres/tests/test_ingest.py
What: Due to the introduction of some vdk-core log changes, similar unit test for vdk-postgres and vdk-greenplum started failing and are breaking the CI/CD.
Why: To fix the CI/CD.
Testing Done: locally.
> vdk-core: fix postgres and greenplum tests

- .pre-commit-config.yaml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentServiceV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployerV2.java
Why
Reducing unnecessary logging caused by the frequent async data jobs deployment scheduled every minute.
What
Adjusted the logging levels for specific log statements. 
> control-service: improve async deployment logging

- projects/vdk-heartbeat/src/vdk/internal/heartbeat/job_controller.py
With the introduction of the deployment synchronizer, the behaviour of the Control Service, when a data job is deployed, has changed slightly. Now, there is a slight delay between a job status changing from Enabled to Disabled, and the status being reflected in the output of the `vdk deploy --show` command. This causes the vdk heartbeat to fail, as it expects the changes to be applied immediately.
This change adds a new check when the `check_deployments()` method is called, whose purpose is to verify that the job status has changed from enabled to disabled, and sleep for a bit if this is not the case.
Testing Done: Executed the heartbeat locally with the command
```bash
vdk-heartbeat -f test_basic_config.ini
```
> vdk-heartbeat: Introduce additional sleep when checking deployments

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentServiceV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceV2TestIT.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java
Why
Changing Python versions without updating gitCommitSha doesn't trigger the build, causing data job issues due to different VDK images.
What
We improved the logic to check whether the Python version has changed, and if it has, the image building is triggered.
Testing done:
Unit tests.
> control-service: fix data job image building

- projects/control-service/projects/base/src/main/java/com/vmware/taurus/service/diag/methodintercept/MetricsHelper.java
- projects/control-service/projects/base/src/main/java/com/vmware/taurus/service/diag/telemetry/Telemetry.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentServiceV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/DataJobsKubernetesService.java
Why
Reducing unnecessary logging caused by the frequent async data jobs deployment scheduled every minute.
```
2023-10-25 11:46:29,056 DEBUG [OpId:] ecutor-200 c.v.t.s.diag.telemetry.Telemetry Sending streaming telemetry to https://vcsa.vmware.com/ph-stg/api/hyper/send?_c=taurus.v0&_i=supecollider-control-service
2023-10-25 11:46:29,063 DEBUG [OpId:] ecutor-199 .t.s.k.DataJobsKubernetesService Datajob template file location is not set. Using internal datajob template.
2023-10-25 11:46:29,065 DEBUG [OpId:] ecutor-199 c.v.t.s.d.m.MetricsHelper        Failed to convert object to json: class java.util.LinkedHashMap: failed to lazily initialize a collection of role: com.vmware.taurus.service.model.DataJob.executions, could not initialize proxy - no Session (through reference chain: …
```
> control-service: reduce logging

- projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/cell.py
Currently, when the cells of an IPython notebook are loaded, it is assumed that each cell has an `id` field. However, this is true only for vdk specific notebooks, not regular ones that users may use to execute vdk commands like create, deploy, etc. In cases, where the notebook is a regular one, the job execution fails abruptly at the plugin loading stage without any meaningful message, because only json-specific errors are being handled.
Example job termination logs:
```bash
2023-09-28 19:55:51,215 [VDK] test-job [ERROR] vdk.internal.builtin_plugins.r   cli_run.py:172
create_and_run_d[id:510b0034-2249-4840-8589-1c9a3f58bc59-1695920149-24c96]- Failed executing job.
'id'
The provided Data Job will not be executed. Terminating application.
See contents of the exception and fix the problem …
```
> vdk-notebook: [bug fix] ignore missing id field in cell

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DeploymentModelConverter.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/GraphQLDataFetchers.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/GraphQLDataFetchersTest.java
Currently, when using the GraphQL API, the data job deployment data is read from the kubernetes
cronjobs. This works fine in general, but it also means that the kubernetes resources become the
single point of truth, which is not ideal.
As part of VEP-2272, the deployment information is moved to the DB, which improves speed and
reliability. This means that we need a way to read data from the DB, instead of the kubernetes.
This change adds support for reading deployment data from the database when using the GrapgQL
API. The option to read from the k8s remains.
Testing Done: Added test.
> control-service: Add GraphQL read from DB

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input_error_classifier.py
- projects/vdk-core/src/vdk/internal/core/error_classifiers.py
- projects/vdk-core/tests/functional/run/jobs/pandas-key-error-job/10_pandas_step.py
- projects/vdk-core/tests/functional/run/test_run_errors.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/termination_message/test_writer.py
- projects/vdk-plugins/vdk-csv/tests/functional/test_csv_plugin.py
- projects/vdk-plugins/vdk-impala/tests/functional/template_regression_test.py
Errors coming from libraries imported in user code are getting classified as platform errors in the execution result This is caused by the job_input_error_classifier checking for an incorrect attribute of the error object.
Export the _vdk_resolvable_by and _vdk_resolvable_actual attributes to constants and replace wherever they're used in code
Bugfix
> vdk-core: fix bug in error classification

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DataJobsSynchronizer.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/monitoring/DataJobSynchronizerMonitor.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/monitoring/DataJobSynchronizerMonitorTest.java
what: added telemetry counters for the DataJobsSynchronizer
why: The counters can be used to monitor if the synchronizeDataJobs method is executing as expected.
testing: added unit test
> control-service: add MeterRegistry counters for DataJobsSynchronizer

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
- projects/vdk-core/src/vdk/internal/cli_entry.py
When vdk command is started logs do not really show up until click command start getting executed. All logs before that (from plugin hooks) seemed ignored.
I couldn't figure out for sure while click_log does that.
But this changes it so that early logs can be seen on console . The log level of the early logs is controlled by LOG_LEVEL_VDK option (which control the log level of VDK logs , since early logs are really vdk logs it make sense)
By default LOG_LEVEL_VDK is WARNING, so if more verbose logs are set it should be changed to INFO.
Testing Done:
```
export LOG_LEVEL_VDK=INFO
vdk run example
```
logs look like
https://gist.github.com/antoniivanov/bdd935927c1149b74944c58e96b50ee3
```
unset LOG_LEVEL_VDK
vdk run example
```
logs look like …
> vdk-core: ensure early logs are available

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
User reasearch indicates that the execution result is too verbose for local runs. Users don't expect a lot of output for successful jobs and expect error output for failing jobs.
Introduce the LOG_EXECUTION_RESULT config option that enables/disables displaying the end result. Enabling and disabling the end result will be implemented in a separate PR. 
https://github.com/vmware/versatile-data-kit/pull/2831
CI
> vdk-core: create config option for logging execution result

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/ingress.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Why
Currently, there is no way to exclude the user interface (UI) from the Ingress configuration.
What
To address this issue, we introduced a new check within the Ingress configuration. This check allows for determining whether the UI is enabled or not
Testing done:
helm template
> control-service: update ingress

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/impl/router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_connection_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_cursor.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_properties/properties_router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/job_secrets/secrets_router.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/cli_run.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/data_job.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/templates/template_impl.py
- projects/vdk-core/src/vdk/internal/core/errors.py
- projects/vdk-core/src/vdk/internal/plugin/plugin.py
As part of the run logs initiative, we should audit all log statements and error messages in vdk-core and make sure there aren't any redundancies, e.g. overly verbose messages or messages that don't add value.
Remove usage of the below constants wherever possible
```
MSG_CONSEQUENCE_DELEGATING_TO_CALLER__LIKELY_EXECUTION_FAILURE
MSG_COUNTERMEASURE_FIX_PARENT_EXCEPTION 
MSG_CONSEQUENCE_TERMINATING_APP
```
Re-word log statements and exception messages that are too verbose
CI
> vdk-core: remove redundant logs

- projects/vdk-plugins/vdk-data-sources/README.md
- projects/vdk-plugins/vdk-data-sources/setup.py
- projects/vdk-plugins/vdk-data-sources/src/vdk/plugin/data_sources/ingester.py
- projects/vdk-plugins/vdk-data-sources/src/vdk/plugin/data_sources/mapping/data_flow.py
- projects/vdk-plugins/vdk-data-sources/src/vdk/plugin/data_sources/mapping/definitions.py
- projects/vdk-plugins/vdk-data-sources/src/vdk/plugin/data_sources/mapping/toml_parser.py
- projects/vdk-plugins/vdk-data-sources/src/vdk/plugin/data_sources/plugin_entry.py
- projects/vdk-plugins/vdk-data-sources/tests/functional/jobs/ingest-data-flow-job/step.py
- projects/vdk-plugins/vdk-data-sources/tests/functional/jobs/ingest-data-flow-map-func-job/step.py
- projects/vdk-plugins/vdk-data-sources/tests/functional/jobs/ingest-data-flow-toml-job/ingest.toml
- projects/vdk-plugins/vdk-data-sources/tests/functional/jobs/ingest-data-flow-toml-job/step.py
- projects/vdk-plugins/vdk-data-sources/tests/functional/test_run_ingest_sources.py
- projects/vdk-plugins/vdk-data-sources/tests/mapping/test_toml_parser.py
Data source can be used in this way:
```python
def run(job_input: IJobInput):
source = SourceDefinition(id="auto", name="auto-generated-data", config={})
destination = DestinationDefinition(id="auto-dest", method="memory")
with DataFlowInput(job_input) as flow_input:
flow_input.start(source, destination)
```
or in config.toml file
```toml
[sources.auto]
name="auto-generated-data"
config={}
[destinations.auto-dest]
method="memory"
[[flows]]
from="auto"
to="auto-dest"
```
```python
def run(job_input: IJobInput):
with DataFlowInput(job_input) as flow_input:
flow_input.start_flow(toml_parser.load_config("config.toml"))
```
> vdk-data-sources: add DataFlowInput API

- projects/vdk-plugins/vdk-huggingface/.plugin-ci.yml
- projects/vdk-plugins/vdk-huggingface/README.md
- projects/vdk-plugins/vdk-huggingface/requirements.txt
- projects/vdk-plugins/vdk-huggingface/setup.py
- projects/vdk-plugins/vdk-huggingface/src/vdk/plugin/huggingface/ingest.py
- projects/vdk-plugins/vdk-huggingface/src/vdk/plugin/huggingface/plugin_entry.py
- projects/vdk-plugins/vdk-huggingface/tests/jobs/huggingface-job/10_upload.py
- projects/vdk-plugins/vdk-huggingface/tests/test_huggingface_plugin.py
Versatile Data Kit (VDK) plugin for integrating with Huggingface as both a data source and a target.
This plugin allows you to ingest data payloads into a Huggingface repository and makes it easier to work with datasets stored in Huggingface.
> vdk-huggingface: add new ingest plugin

- projects/vdk-plugins/vdk-singer/.plugin-ci.yml
- projects/vdk-plugins/vdk-singer/README.md
- projects/vdk-plugins/vdk-singer/requirements.txt
- projects/vdk-plugins/vdk-singer/setup.py
- projects/vdk-plugins/vdk-singer/src/vdk/plugin/singer/adapter.py
- projects/vdk-plugins/vdk-singer/src/vdk/plugin/singer/message_utils.py
- projects/vdk-plugins/vdk-singer/src/vdk/plugin/singer/plugin_entry.py
- projects/vdk-plugins/vdk-singer/src/vdk/plugin/singer/singer_command.py
- projects/vdk-plugins/vdk-singer/src/vdk/plugin/singer/singer_data_source.py
- projects/vdk-plugins/vdk-singer/src/vdk/plugin/singer/tap_command.py
- projects/vdk-plugins/vdk-singer/tests/jobs/ingest-singer-tap-api-job/ingest_api_step.py
- projects/vdk-plugins/vdk-singer/tests/jobs/ingest-singer-tap-api-job/requirements.txt
- projects/vdk-plugins/vdk-singer/tests/jobs/ingest-singer-tap-job/ingest_singer_tap_step.py
- projects/vdk-plugins/vdk-singer/tests/jobs/ingest-singer-tap-job/requirements.txt
- projects/vdk-plugins/vdk-singer/tests/test_run_ingest_singer.py
- projects/vdk-plugins/vdk-singer/tests/test_singer_command.py
This is adding a data source plugin for singer.io.
So now users can specify singer taps as data sources
They can also list all singer taps that can be found with `vdk singer --list-taps`
The change depends on https://github.com/vmware/versatile-data-kit/pull/2805
> vdk-singer: Singer.io plugin for data sources

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/pyproject.toml
Upgrade dependencies so a build will will always create a runnnable jupyter lab. 
Tested the build locally and everything works good.
> vdk-jupyterlab-extensions: update dependencies

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/AWSCredentialsService.java
what: Forced the AWS credentials service to refresh credentials before passing them to the data job builder task.
why: Users of the control-service noticed that the job builder task would occasionally fail with 401 unauthorized when attempting to push images to aws ecr repository. Since some builders take longer to build the images, it is possible that a passed valid credential expired during build. As per the aws documentation: "This credentials provider uses a background thread to refresh credentials." though it is unclear when credentials are rotated. Note this behaviour of the provider was changed in a aws update, previously the credentials were generated before every request.
testing: existing tests should cover this.
> control-service: force aws cred provider refresh

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/poddisruptionbudget.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
All for higher Control Service availability while permitting the cluster administrator to manage the clusters nodes.
Add optional configuration for pod disruption budget.
> control-service: add pod disruption budget

- projects/vdk-plugins/vdk-smarter/requirements.txt
What: OpenAI introduced v1.0.0 of their Python API library. This new major SDK version comes with some breaking changes. The idea of this change is to pin openai version to 0.28 in order to have green CI/CD pipelines until we migrate.
Why: To fix the pipeline.
Testing Done: locally.
Reference for future migration: https://github.com/openai/openai-python/discussions/742
> vdk-smarter: pin openai version to 0.28

- .gitlab-ci.yml
VDK team recently started tracking CI failures and resolutions
Add the resolutions page link to the CI failure Slack notification for convenience
Dry run in CI https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/1070030579
> support: update the ci notification

- projects/vdk-plugins/vdk-logging-format/README.md
- projects/vdk-plugins/vdk-logging-format/src/vdk/plugin/logging_format/logging_format.py
This PR deprecates the vdk-logging-format plugin in favour of vdk-structlog.
> vdk-logging-format: Deprecate plugin

- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_router.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_router.py
The logs were not replacing the method name because the f-string was missing the `f"` so this is fixed.
Slightly simplified the error message to make it easier to understand I hope
> vdk-core: ingest logging formatting bug

- projects/vdk-plugins/vdk-structlog/README.md
- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/constants.py
- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/filters.py
- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/formatters.py
- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/structlog_plugin.py
- projects/vdk-plugins/vdk-structlog/tests/test_structlog.py
Filtering by timestamp, level and vdk_job_name does not work for json formatting
- Introduce logic that inserts the correct fields in the json formatter log record
- Move the metadata filters after the filters that add the job name
- Fix bug in ConsoleMetadataFilters
- Add timestamp to tests
- Enable json tests
Ran functional tests locally
Bugfix
https://github.com/vmware/versatile-data-kit/issues/2875
> vdk-structlog: fix filtering of metadata fields for json

- projects/vdk-plugins/vdk-notebook/README.md
- projects/vdk-plugins/vdk-notebook/requirements.txt
- projects/vdk-plugins/vdk-notebook/setup.py
- projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/cell.py
- projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/notebook.py
- projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/notebook_based_step.py
- projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/notebook_plugin.py
- projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/vdk_ingest.py
- projects/vdk-plugins/vdk-notebook/tests/jobs/ingest-data-flow-job/steps.ipynb
- projects/vdk-plugins/vdk-notebook/tests/test_vdkingest.py
This commit introduces the ability to recognize and execute cells with the `%%vdkingest` magic function in notebook-based data jobs. Previously, notebook steps only supported Python and SQL cell types (`%%vdksql`).
This addition enriches the functionality of notebook-based steps by providing users the capability to define ingestion tasks directly within a Jupyter notebook, enhancing flexibility and usability.
> vdk-notebook: Support for "%%vdkingest" cell type in Notebook Steps

- projects/vdk-plugins/vdk-ipython/README.md
- projects/vdk-plugins/vdk-ipython/requirements.txt
- projects/vdk-plugins/vdk-ipython/setup.py
- projects/vdk-plugins/vdk-ipython/src/vdk/plugin/ipython/__init__.py
- projects/vdk-plugins/vdk-ipython/src/vdk/plugin/ipython/ingest.py
- projects/vdk-plugins/vdk-ipython/tests/conftest.py
- projects/vdk-plugins/vdk-ipython/tests/test_ingest.py
- projects/vdk-plugins/vdk-ipython/tests/test_job_control.py
The commit introduces a new IPython magic function, `vdkingest`, which
enables data ingestion through TOML configuration within a Jupyter
notebook. This enhancement aims to simplify and streamline the data
ingestion process by allowing users to declare their data flows in a
structured format (TOML), thereby making it more accessible and
maintainable.
This is an optional feature of the plugin. If `vdk-data-sources` is not
installed, an ImportError is raised with an informative message.
(the commits will be merged as separate commits with rebase)
> vdk-ipython: add support for %%vdkingest

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/ingress.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
Why:
Our Helm chart currently lacks the functionality to specify multiple Ingress hosts.
What:
Enhance the Ingress template to support multiple hosts.
Testing done:
helm template
before:
```yaml
kind: Ingress
metadata:
name: release-name-pipelines-control-service
labels:
app.kubernetes.io/name: pipelines-control-service
helm.sh/chart: pipelines-control-service-0.0.1-SNAPSHOT
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Helm
annotations:
{}
apiVersion: networking.k8s.io/v1
spec:
ingressClassName: class
rules:
- host: "vdk.com"
http:
paths:
- path: data-jobs
pathType: "ImplementationSpecific"
backend:
service:
name: release-name-ui
port:
number: 8091
- path: data-jobs
pathType: "ImplementationSpecific"
backend:
service:
name: release-name-svc
port:
number: 8092 …
```
> control-service: ingress allow for multiple hosts

- projects/control-service/projects/helm_charts/pipelines-control-service/templates/limitrange_datajobs.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/resourcequota_datajobs.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
**Why:**
Add resource quota and range limits for the data jobs namespace for better resource control.
see:
https://kubernetes.io/docs/concepts/policy/resource-quotas/
https://kubernetes.io/docs/concepts/policy/limit-range
**What:**
Add Limit Range and Resource Quota templates.
**Testing done:**
helm template
> control-service: add resource constraints

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/resquests.spec.ts
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/serverRequests.ts
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/handlers.py
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/task_runner.py
- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/vdk_jupyterlab_extension/tests/test_task_runner.py
What: Bug fix. Since the Task Runner change got in, if you tried to deploy a job without keytab, you would not have been informed about the error in any way and the Task Runner state wouldn't have been cleaned, therefore, not being able to handle any other request. Only a restart of the session would have solved this which is not good. 
To address this I:
* Modified the Task Runner start_task() method to proceed after 'failed' last request.
* Improved the error handling - show the error of failing request which was not shown and made the backend handlers able to detect any errors.
Why: To make it work in a better way and not to have to restart the session on each bad request.
Testing Done: Introduced relevant tests. The rest of the tests are passing.
> vdk-jupyter: fix bug for failed requests and improve error handling

- projects/vdk-plugins/.plugin-common.yml
- projects/vdk-plugins/vdk-kerberos-auth/.plugin-ci.yml
- projects/vdk-plugins/vdk-kerberos-auth/tests/test_kerberos.py
Test was failing 
change logging config
CICD
> vdk-kerberos-auth: fix unit test failing from bad logging config 

- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/ingestion/ingester_utils.py
- projects/vdk-core/tests/functional/ingestion/jobs/test-ingest-bad-payload-job/1_ingest_step.py
- projects/vdk-core/tests/functional/ingestion/test_payload_verification.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_utils.py
As part of the work for vdk-oracle, we need to be able to pass datetime objects for ingestion. This is not possible with the current verification.
Add datetime to the decimal json encoder
Make the encoder return timestamp for the datetime object Rename DecimalJsonEncoder to IngesterJsonEncoder
Ran locally with vdk-oracle
CI tests
> vdk-core: add datetime and bytes to decimal json encoder

- projects/vdk-plugins/vdk-oracle/.plugin-ci.yml
- projects/vdk-plugins/vdk-oracle/README.md
- projects/vdk-plugins/vdk-oracle/requirements.txt
- projects/vdk-plugins/vdk-oracle/setup.py
- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/ingest_to_oracle.py
- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/oracle_configuration.py
- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/oracle_connection.py
- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/oracle_plugin.py
- projects/vdk-plugins/vdk-oracle/tests/conftest.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-connect-execute-job/00_drop_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-connect-execute-job/10_create_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-connect-execute-job/20_populate_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-blob/00_drop_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-blob/10_create_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-blob/20_ingest.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-different-payloads-no-table/00_drop_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-different-payloads-no-table/10_ingest.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-different-payloads/00_drop_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-different-payloads/10_create_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-different-payloads/20_ingest.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-no-table/00_drop_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-no-table/10_ingest.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job/00_drop_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job/10_create_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job/20_ingest.py
- projects/vdk-plugins/vdk-oracle/tests/test_plugin.py
In order to support more use cases, vdk should support connecting and ingesting to an oracle database
Add oracle plugin. Plugin supports simple queries, cli queries and ingestion.
Local functional tests, CI tests are part of a separate task
[Set up testcontainers for CI](https://github.com/vmware/versatile-data-kit/issues/2928)
[Support type inference when ingesting](https://github.com/vmware/versatile-data-kit/issues/2929)
[Support passing math.nAn and None for ingestion](https://github.com/vmware/versatile-data-kit/issues/2930)
[Optimize batching of payload rows with different keysets](https://github.com/vmware/versatile-data-kit/issues/2931)
[ORA-01002: fetch out of sequence error in _cache_tables when some rows fail to …
> vdk-oracle: create oracle plugin

- projects/vdk-core/src/vdk/internal/core/errors.py
report_and_throw swallows the actual exception cause if we don't pass a cause
Remove the cause parameter (it's not used)
CI
Bugfix
> vdk-core: fix exception cause swallowing

- projects/control-service/projects/job-builder-rootless/Dockerfile.python.vdk
- projects/control-service/projects/job-builder/Dockerfile.python.vdk
Between each step in a docker build it needs to save a snapshot of the system. 
Some operations actually require unpacking layers created before it. 
This python -V is a really expensive operation. 
Because it needs to unpack all the layers that came before it to run that command. 
from the logs we can see 
```
INFO[0001] Unpacking rootfs as cmd RUN python -V requires it.
```
I removed the operation because it actually has no impact. 
I will deploy in CICD env and test when I get approvals. 
I want it removed incase there is some context I am missing.
> control-plane: remove needless step in docker build.

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
I am deploying a job which takes a longtime to build. 
I want the system to poll for longer
Make the length of time we poll for configurable. 
Tests are checking that the current impl works. 
Tonight I will be using the new config to build my new job. 
> control-service: make timeout configurable

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/BaseDataJobDeploymentCrudIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/service/deploy/DataJobDeploymentCrudITV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentServiceV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/DataJobsKubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceV2TestIT.java
Why:
The deployment cannot be suspended in the case of a previously failed one.
What:
Added additional logic to the DeploymentServiceV2 to handle this particular case.
Testing done:
IT and unit tests.
> control-service: deployment cannot be suspended

- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/ingest_to_oracle.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-type-inference/00_drop_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-type-inference/10_create_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-type-inference/20_ingest.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job/20_ingest.py
- projects/vdk-plugins/vdk-oracle/tests/test_plugin.py
Inferring the type in case a string is passed in the payload instead of the corresponding data type improves the user experience. Type conversion can be relegated to vdk instead of doing pre-processing of large payloads inside data jobs
Add column data types to column cache
In case a string is passed, infer the python data type based on the Oracle column data type.
In case math.nan is passed, write NULL to the Oracle table
Ran functional tests locally
CI/CD
> vdk-oracle: support type inference

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/DeploymentModelConverter.java
Why:
Currently, the redeployment of a data job resets previously changed resources, such as CPU and memory.
What:
I have improved the method for merging deployment resources.
> control-service: fix deployment resources

- projects/vdk-plugins/vdk-oracle/README.md
- projects/vdk-plugins/vdk-oracle/requirements.txt
- projects/vdk-plugins/vdk-oracle/setup.py
- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/oracle_configuration.py
- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/oracle_plugin.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-connect-execute-job/config.ini
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job-type-inference/20_ingest.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-job/config.ini
- projects/vdk-plugins/vdk-oracle/tests/test_secrets_config.py
Secrets should be supported to avoid storing credentials in plaintext for cloud deployments
Add support for secrets
Update README.md
Change development status to beta
Ran funcational tests locally
CI/CD
> vdk-oracle: support secrets to connect to database

- projects/vdk-plugins/vdk-kerberos-auth/requirements.txt
The latest release of docker doesn't work with our version of pytest-docker. 
I am fixing the docker version.
> vdk-kerberos-auth: fix dependency issue

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobDeploymentCrudAsyncIT.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DataJobDefaultConfigurations.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployerV2.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/K8SMemoryConversionUtils.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DataJobDefaultConfigurationsTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/TestDataJobDefaultConfigurations.java
what: If no resources specified when deploying data jobs with the DataJobsSynchronizer we will now write the default resources values to the DB.
why: Previously these values would only be present in K8S.
testing: added unit test, modified integration test.
> control-service: write resources to db

- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/formatters.py
- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/structlog_plugin.py
- projects/vdk-plugins/vdk-structlog/tests/test_structlog.py
vdk_step_name and vdk_step_type were not filtered correctly when using json format
Make sure the metadata filter alwats executes last, even when vdk_step_name and vdk_step_type are involved
Add separate functional test for vdk_step_name and vdk_step_type to avoid conflict with file_name in other tests
> vdk-structlog: filter vdk_step_name and vdk_step_type correctly

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_plugin.py
Due to logic in vdk-core, the managed cursor tries to execute all implementations of the db_connection_decoreate_operation hook. This happens even if it's not the correct cursor, e.g. an oracle cursor might try to execute impala queries. This case is handled in other plugins by wrapping the decorator in a try/catch block. However, the job should fail if the default db type is impala and the actual error is an impala error and not coming from some other cursor.
Check the db_default_type config if an exception occurs in the decorator. If the db_default type is not impala, output an error log. If the db_default type is impala, re-throw the error
Tested locally
CI
Bugfix
https://github.com/vmware/versatile-data-kit/issues/2973
> vdk-impala: handle decorate operation errors

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/GraphQLDataFetchers.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/FindAllDataJobsTest.java
what: The control-service now uses LinkedHashMap when populating the graphQL filter and search criteria strategies.
Which ensures consistent filtering and sorting.
why: The previous usage of a HashMap would not guarantee any ordering of the key set which would lead to user issues when querying data from the API such as differently sorted lists of data jobs for the same query. This would cause more problems when we include pagination on a larger query - such as vdk list -a - users would see duplicated data, or missing data. Example of the same query with different ordering results can be seen below:
This was run on a local instance of the control-service with dummy data.
testing: Added unit test.
> control-service: getting all jobs should now be consistent

- projects/vdk-control-cli/src/vdk/internal/control/job/job_config.py
- projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_create.py
Currently, the `_set_value()` logic in **JobConfig** uses `fileinput.input()` to traverse the contents of the job config file, and update the keys passed. This works as expected on python versions up to 3.11. It, however breaks on python3.11 on some platforms. For example, it works fine on Ubuntu, but the config file gets truncated on photonOS (the operating system used for the secure base images), which causes job creation failures.
This change modifies the `_set_value()` logic to directly read and write the config file's contents, and drops the use of *fileinput*.
Testing Done: Added test, and did some local testing using docker containers with different host OSs.
> vdk-control-cli: Modify how data is written to job config.ini

- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/pages/executions/data-job-executions-grid/data-job-executions-grid.component.ts
Why
Data Job Executions list (in Data Job Executions page) pagination behaviour is unpredictable whenever the job is running.
What
Save and reuse executions grid state
How was this tested
Ran e2e tests locally
What type of change is this
Bug fix
> frontend: [SC-2632] Save Executions grid state

- projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/constants.py
- projects/vdk-plugins/vdk-structlog/tests/test_structlog.py
Structlog config options have the same name as some vdk-core config options. This causes a conflict when running jobs with minimal config.
Rename the structlog config options
Ran a hello-world example locally
CI
Bugfix
> vdk-structlog: rename structlog configs

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
What: Replace deprecated imp module with importlib.
Why: To fix an error with the VDK command faced by a user.
Testing Done: existing tests pass
Signed-off-by: Yoan Salambashev <yoan.salambashev@broadcom.com>
> vdk-core: replace deprecated imp module with importlib

- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/oracle_configuration.py
The tick mode = true is more frequently used for now
So it makes more sense to be default
> vdk-oracle: set thik mode default to true

- projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package-lock.json
vdk-jupyter build is failing
(https://gitlab.com/vmware-analytics/versatile-data-kit/-/pipelines/1146103715)
It seems there are a lot of outdated packages . As a first step upating them.
> vdk-jupyter: update npm packages

- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_helper.py
- projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/template_arguments_validator.py
- projects/vdk-plugins/vdk-ingest-http/src/vdk/plugin/ingest_http/ingest_over_http.py
- projects/vdk-plugins/vdk-kerberos-auth/src/vdk/plugin/kerberos/minikerberos_authenticator.py
- projects/vdk-plugins/vdk-postgres/src/vdk/plugin/postgres/ingest_to_postgres.py
- projects/vdk-plugins/vdk-snowflake/src/vdk/plugin/snowflake/snowflake_connection.py
- projects/vdk-plugins/vdk-sqlite/src/vdk/plugin/sqlite/ingest_to_sqlite.py
- projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/ingest_to_trino.py
Calling report_and_rethrow causes confusing stack traces, because of adding an extra frame from the extra function call
Replace report_and_rethrow with just calling report and raising the exception after
CI
> vdk-plugins: replace report_and_rethrow

- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_connection_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_cursor.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/cli_run.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
- projects/vdk-core/src/vdk/internal/core/errors.py
- projects/vdk-core/tests/vdk/internal/core/test_errors.py
Calling report_and_rethrow causes confusing stack traces, because of adding an extra frame from the extra function call
Replace report_and_rethrow with just calling report and raising the exception after
CI
> vdk-core: replace report_and_rethrow

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
Structlog should not override the initial logging config. It applies to logging before vdk is initialized and before any plugins are loaded. If an error happens in vdk_main, the logging config will apply. It should remain in core.
It's also not a problem for structlog, because it ejects all logging config just in case.
Remove the structlog override in core
Locally
CI
Bugfix
> vdk-core: remove structlog logging override

- projects/vdk-core/src/vdk/internal/builtin_plugins/run/cli_run.py
- projects/vdk-core/tests/functional/run/test_run_errors.py
Sometimes the exact errors in user code are hard to find in the stack trace
Print relevant information from stack trace in step results
Example:
On error in step 20_python_step.py, the short result summary looks like this
```
2024-01-29 15:14:14,736 [VDK] hello-world [INFO ] vdk.internal.builtin_plugins.r           cli_run.py:166  __log_short_exec[id:3a22ec2e-d6e6-4f94-96c0-122955930cbb-1706534052-abffd]- Job execution result: ERROR
Step results:
10_sql_step.sql - SUCCESS
20_python_step.py - ERROR
File "/Users/mdilyan/Projects/vdk-playground/hello-world/20_python_step.py", line 27, in run
raise ValueError("No value in this")
ValueError: No value in this
```
Ran locally
> vdk-core: relevant info in step result

- projects/vdk-core/src/vdk/api/plugin/plugin_input.py
This change adds a `method` argument to the pre_ingest_process() and post_ingest_process()
APIs, in order to allow plugin developers to add logic specific only to certain ingestion
methods.
> vdk-core: Add 'method' to pre_ingest_process API

- examples/embed-ingest-job-example/20_clean_and_embed_json_data.py
- examples/embed-ingest-job-example/30_create_schema.sql
- examples/embed-ingest-job-example/40_ingest_embeddings.py
- examples/embed-ingest-job-example/README.md
- examples/embed-ingest-job-example/config.ini
- examples/embed-ingest-job-example/config.py
- examples/embed-ingest-job-example/documents_example.json
- examples/embed-ingest-job-example/requirements.txt
What: As part of the Vector Database Ingestion initiative, we want to be able to fetch, embed Confluence JSON data and ingest it into Postgres (with pgvector). This example achieves the embedding and ingestion part.
Testing Done: Successfully ingested the documents in Postgres.
Signed-off by: Yoan Salambashev <yoan.salambashev@broadcom.com>
> examples: add Embed and Ingest Confluence JSON data example data job

- examples/confluence-reader/confluence_document.py
- projects/vdk-core/src/vdk/internal/core/config.py
- projects/vdk-core/tests/vdk/internal/core/test_config.py
There are cases where we want to know we're using the default value for a config option. One such case is configuration presets
https://github.com/vmware/versatile-data-kit/pull/3055
Add is_default() to the config object.
Unit tests
> vdk-core: add is_default() function to config

- projects/vdk-core/src/vdk/internal/builtin_plugins/job_properties/properties_router.py
Property type "memory" comes with vdk-core. If another one like fs-client proeprty comes it will call ambiguity order but that's unecesary since memory is only useful for unit testing. Otherwise it's not and we should defualt to the other one if only two are available.
> vdk-core: do not count memory properties toward the count

- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/remote_data_job.py
If you have locally configured authorizaton settings (e.g client id, refresh token and so on) which might be expired or wrong, VDK dag still tries to authenticate and generate access token even if no authentication may be required by the Control Service API. This casues the DAG jobs to fail with authentication error which is unnecssary if the API didn't require auth.
Instead we now just post a warning about the failure to get acess token. We fail later if and only if the API requires authentication . If not everything suceeeds.
Testing Done: local tests pass (they failed before for above reason)
> vdk-dag: fix unnecessary authorization failure

- projects/vdk-plugins/vdk-dag/README.md
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/cached_data_job_executor.py
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/dag.py
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/dag_plugin_configuration.py
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/dags.py
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/local_executor.py
- projects/vdk-plugins/vdk-dag/tests/jobs/fail-job/1_step.py
- projects/vdk-plugins/vdk-dag/tests/jobs/local-dag/config.ini
- projects/vdk-plugins/vdk-dag/tests/jobs/local-dag/dag.py
- projects/vdk-plugins/vdk-dag/tests/jobs/read-file-job/1_step.py
- projects/vdk-plugins/vdk-dag/tests/jobs/write-file-job/1_step.py
- projects/vdk-plugins/vdk-dag/tests/test_dag_object.py
- projects/vdk-plugins/vdk-dag/tests/test_local_executor.py
In order to be able to test locally a full dag, we need a local executor which will run the data jobs locally.
The way it works user sets `DAGS_JOB_EXECUTOR_TYPE=local` and must ensure all jobs are at the same level as the DAG job or the current working directory in order to find them
> vdk-dag: add local executor

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
vdk-structlog has a default config flag set to True when installed. It relegates all logging configuration to the plugin and is checked in core, i.e. if structlog is installed, vdk will use structlog. If it's not installed, it will use the configuration available in core. The flag is currently checked using an env variable, which makes it not work.
Check the flag using the config object
Manually
Bugfix
> vdk-core: enable/disable structlog based on config

- projects/vdk-plugins/vdk-postgres/src/vdk/plugin/postgres/ingest_to_postgres.py
- projects/vdk-plugins/vdk-postgres/tests/conftest.py
Insert data is painfully slow even small amounts making even testing and pocs hard. So this is a quick and slight optimization Before insert 300 rows took 15 minutes. Now it's about 1 minute
Testing Done: made sure existing test pass. Tested with a job sending 300 rows in 2 tables.
> vdk-postgres: batch inserts during ingestion

- projects/vdk-plugins/vdk-kerberos-auth/setup.py
revert recent dependency changes as they prohibit pipy publishing.
> vdk-kerberos-auth: revert recent changes

- projects/control-service/projects/job-builder-rootless/Dockerfile.python.vdk
- projects/control-service/projects/job-builder-secure/Dockerfile.python.vdk
- projects/control-service/projects/job-builder/Dockerfile.python.vdk
Pip caching is never useful for Docker builds, and it makes the image bigger and cause the process to consume more memory which can lead to OOM errors.
> control-service: optimize job builder pip install

- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/cached_data_job_executor.py
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/dag_validator.py
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/exception.py
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/local_executor.py
- projects/vdk-plugins/vdk-dag/tests/test_dag.py
- projects/vdk-plugins/vdk-dag/tests/test_local_executor.py
To make it easier to debug VDK DAG jobs some improvements in error handling are done.
- Stop using deprecated UserCodeError in favour of domain oriented exceptoin class
- Improve the formatting of the error message in case of failure.
- Renamed DAG_LOCAL_RUN_JOB_PATH to DAGS_LOCAL_RUN_JOB_PATH to bring it inline with other configuration options [like here](https://github.com/vmware/versatile-data-kit/blob/main/projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/dag_plugin_configuration.py#L6). Eventually we should expose it the same way but not in this PR.
Testing Done: existing tests for regression.
Here is a comparison before and now in the formatting: https://gist.githubusercontent.com/antoniivanov/8f87cdef1c610fcd24361197bcba45dc/raw/c31b990de2c0b1f49ac5989419cfc6ab12aac934/gistfile1.txt
> vdk-dag: improve error handling and error messages

- projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/explore/data-jobs/data-jobs.spec.js
- projects/frontend/data-pipelines/gui/e2e/integration/frontend-tests/manage/data-jobs/data-jobs.spec.js
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/base-grid/data-jobs-base-grid.component.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/data-job-page.component.spec.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/pages/details/data-job-details-page.component.html
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/pages/details/data-job-details-page.component.spec.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/pages/details/data-job-details-page.component.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/pages/executions/data-job-deployment-details-modal/data-job-deployment-details-modal.component.html
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-explore/components/grid/data-jobs-explore-grid.component.html
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-explore/components/grid/data-jobs-explore-grid.component.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-jobs-manage/components/grid/data-jobs-manage-grid.component.html
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/model/data-job-base.model.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/model/data-job-details.model.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/model/grid-config.model.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/services/data-jobs.api.service.spec.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/services/data-jobs.api.service.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/shared/pipes/extract-job-status.pipe.spec.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/shared/utils/data-job.util.spec.ts
- projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/shared/utils/data-job.util.ts
- Manage Data Jobs page - Python version column
- make column to be able to be hide, shown by default
- disable filter and sort on the column
- Explore Data Jobs page - Python version column
- render column, hidden by default
- make column to be able to be shown, hidden by default
- disable filter and sort on the column
- Manage Data Job page - Python version section
- render readonly section on the left details part of the page
- Explore Data Job page - Python version section
- render readonly section on the left details part of the page
Local tests passed
Feature/ Non-breaking
> vdk-frontend: Show Python Version of the Data Jobs Deployment

- projects/vdk-core/requirements.txt
- projects/vdk-core/tests/functional/run/jobs/different-db-conn-and-ingest-target/1_step.py
- projects/vdk-core/tests/functional/run/jobs/different-source-and-ingest-target/1_step.py
- projects/vdk-core/tests/functional/run/test_run_different_source_and_destination.py
What: added a test that shows we can have different db connection and ingest target in a data job 
Linked to: https://github.com/vmware/versatile-data-kit/issues/3128
Follows the scenario: 
- write and read data from sqlite
- change the data a little
- send changed data to another database (duckdb)
> vdk-core: add test for different db connection and ingest target 

- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/oracle_plugin.py
- projects/vdk-plugins/vdk-oracle/tests/test_plugin.py
Solves: https://github.com/vmware/versatile-data-kit/issues/2940
The tests has been changed since sql-query adds logs to the output of the command.
Example: 
> vdk-oracle: replace oracle-query with sql-query

- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/AWSCredentialsService.java
When running on AWS and we need to access the private amazon container registry we make use of IAM roles to give us permission to access this resource.
When using an IAM role you can only get an access token that lasts a couple of hours and then you need to refresh it. 
The class `AWSCredentialsService` is responsible for doing this refresh. 
But this leads to a chicken end egg situation. 
the question how can you make a request for an IAM access token? 
Surely that requires authenticating yourself too. 
Yes, it does. 
So within our existing code you need to pass in the access token and secret key of a user who has permission to take on this IAM role. 
However when a job is running on an EKS cluster it doesn't need to do that. 
We mark all pods on this eks cluster as being able to use …
> Control-service: load iam role eks service account

- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/database_managed_connection.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_connection_base.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_cursor.py
- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/connection/test_managed_cursor.py
- projects/vdk-plugins/vdk-test-utils/src/vdk/plugin/test_utils/util_funcs.py
Resolves: https://github.com/vmware/versatile-data-kit/issues/3161
Instead of abstract methods, we are using an Interface to identify where the methods come from base or from plugin (checks whether method comes from a class that inherits the base). 
If the class has been inherited and the methods been overriden then we use those methods if not we use the hook spec. 
This is done for backwards compatibility with the current plugin implementations.
> vdk-core: db managed connections

- projects/vdk-plugins/vdk-server/src/vdk/plugin/server/installer.py
We have always used an old version of k8s in the installer because internally VDK was running on an old version and we would use it to catch regressions. 
They are now using a newer version so we can upgrade the version here accordingly
Deployed it locally, created and ran a job.
> vdk-server: Upgrade k8s version

- projects/vdk-core/README.md
- projects/vdk-core/src/vdk/internal/builtin_plugins/builtin_hook_impl.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/config/secrets_config.py
- projects/vdk-core/src/vdk/internal/core/config.py
- projects/vdk-core/tests/functional/run/test_run_configuration.py
- projects/vdk-plugins/vdk-plugin-control-cli/tests/test_secrets_plugin.py
VDK doesn't provide a way to set sensitive configuration like passwords, such as trino_password. The only way to currently do this is by adding config keys and fetching the values from secrets.
Add a plugin that reconfigures the Configuration object in CoreContext based on secrets. Do this in the initialize_job hook. In this setup, secrets override options set by regular configs. For example if you set trino_password to "password" in config.ini, but also have a secret called trino_passowrd="another password", the value of trino_password will be "another_passowrd".
**Note:** The Configuration class and the CoreContext class are annotated with `@dataclass(frozen=True)`. This enforces encapsulation, so in order to mutate the Configuration object after it's created, we have to add more public …
> vdk-core: support overriding configs with secrets

- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/projects/helm_charts/pipelines-control-service/README.md
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobDeploymentCrudAsyncIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobDeploymentCrudIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/TestJobDeployTempCredsIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/TestJobImageBuilderDynamicVdkImageIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/service/deploy/DataJobDeploymentCrudITV2.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-test.properties
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/data_job_templates/backoff_limit_exceeded_cron_job.yaml
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/data_job_templates/fast_failing_cron_job.yaml
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/fast_failing_cron_job.yaml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesServiceConfiguration.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/ControlKubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/DataJobsKubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/main/resources/k8s-data-job-template.yaml
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceCancelRunningCronJobTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceIsRunningJobTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceStartJobWithArgumentsIT.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceStartNewCronJobExecutionTest.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
- projects/control-service/projects/pipelines_control_service/src/test/resources/k8s-data-job-template.yaml
External customers are looking to run on newer versions of k8s than we support. 
We are using a very old batch/V1Beta1 api. 
We need to remove all references to this.
I deleted all code which was referencing it. This looks like a massive PR but it should actually be fairly simple to review because it is just deleting code. 
Existing unit and integration tests. 
I will also be deploying it to newer versions of k8s this week.
> control-service: remove support for old k8s

- projects/control-service/cicd/.gitlab-ci.yml
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/kubernetes/DataJobsKubernetesService.java
Now that batch v1 is the default we must assume batch v1 when version is null. 
In the old code we were actually mis classifying some v1Batch1 jobs as V1Batch1Beta1
Also clean up variables with wrong naming
There was actually a test failing today because of this issue that didn't fail in my original PR. 
I will investigate why they only failed now shortly. 
> control-service: remove support for old k8s 

- projects/control-service/cicd/deploy-testing-pipelines-service.sh
In a previous merge I forgot to remove this.
> control-service: use correct tag

- projects/control-service/projects/helm_charts/pipelines-control-service/README.md
Customers we were onboarding were confused about where to use the helm charts in our repo
Add not to the helm charts that they're only intended for production use
n/a
Docs
> vdk-control-service: update helm chart documentation

- projects/vdk-core/src/vdk/api/plugin/connection_hook_spec.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_cursor.py
- projects/vdk-core/tests/functional/run/test_run_restricted_hooks.py
The hooks that expose cursors end up in pluggy's LIFO buffer and execute every time. This is ok for things like lineague or metrics, but it breaks database plugins if they try to execute queries with the wrong cursor.
Create more restrictive hooks to eventually replace the hooks that expose the DecorationCursor and Recovery cursor
> vdk-core: add more restrictive hooks to hookspec

- projects/vdk-plugins/vdk-oracle/requirements.txt
- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/ingest_to_oracle.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-data-frame-schema-inference/00_drop_table.sql
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-data-frame-schema-inference/10_ingest.py
- projects/vdk-plugins/vdk-oracle/tests/test_plugin.py
After https://github.com/vmware/versatile-data-kit/pull/3181 we have to make sure schema inference works with data frames
Add data frame schema inference functional test
Non-breaking
> vdk-oracle: test data frames with schema inference

- projects/vdk-plugins/vdk-dag/README.md
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/api/dag.py
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/dag.py
- projects/vdk-plugins/vdk-dag/src/vdk/plugin/dag/dag_runner.py
- projects/vdk-plugins/vdk-dag/tests/jobs/dag-all-status-check/config.ini
- projects/vdk-plugins/vdk-dag/tests/jobs/dag-all-status-check/dag.py
- projects/vdk-plugins/vdk-dag/tests/jobs/dag-specified-status-checks/config.ini
- projects/vdk-plugins/vdk-dag/tests/jobs/dag-specified-status-checks/dag.py
- projects/vdk-plugins/vdk-dag/tests/test_dag.py
Solving: https://github.com/vmware/versatile-data-kit/issues/3236
Note: this implementation assumes that the user wants to check the statuses of the DAG jobs after the DAG run not during the run 
Tested: functional tests
> vdk-dag: add status checks functionalities

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/secrets_config.py
- projects/vdk-core/tests/functional/run/jobs/simple-job-config-ini/1_step.py
- projects/vdk-core/tests/functional/run/jobs/simple-job-config-ini/config.ini
- projects/vdk-core/tests/functional/run/test_run_configuration.py
Secrets override config options. Secrets are per-job. If the cloud deployment sets secrets for a job, there's no quick way to override them for local testing.
Make env variables take precedence over secrets
> vdk-core: env var precedence over secrets config

- projects/vdk-plugins/vdk-oracle/README.md
- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/ingest_to_oracle.py
- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/oracle_configuration.py
- projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/oracle_plugin.py
- projects/vdk-plugins/vdk-oracle/tests/jobs/oracle-ingest-data-frame-schema-inference/10_ingest.py
- projects/vdk-plugins/vdk-oracle/tests/test_plugin.py
The current ingestion implementation batches payload rows by column keyset. Payloads with the same keyset are batched together and passed to an executemany() call. This is not ideal becauase it can result in a large number of executemany() calls
Make each payload row uniform by identifying missing columns and filling them out with null values.
Pass data rows to executemany() in uniform batches.
> vdk-oracle: Pass ingestion payload rows in uniform batches

- projects/vdk-plugins/vdk-smarter/src/vdk/plugin/smarter/openai_plugin_entry.py
The decorate_operation hook exposes a cursor, which is too permissive. We'll eventually remove it in favor of the before_operation hook.
Move the decorate_operation logic to before_operation
> vdk-smarter: migrate decorate_operation to before_operation

- projects/vdk-plugins/vdk-lineage/src/vdk/plugin/lineage/plugin_lineage.py
The decorate_operation hook exposes a cursor, which is too permissive. We'll eventually remove it in favor of the before_operation hook.
Move the decorate_operation logic to before_operation
> vdk-lineage: migrate decorate_operation to before_operation

- projects/vdk-core/src/vdk/api/plugin/connection_hook_spec.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_cursor.py
- projects/vdk-core/tests/functional/run/test_run_restricted_hooks.py
Hook implementations for the failure hook also require that we expose the exception as an argument
Add the exception as an argument to the on-failure hook
> vdk-core: on-failure hook exception argument

- projects/vdk-plugins/vdk-server/src/vdk/plugin/server/installer.py
- projects/vdk-plugins/vdk-server/src/vdk/plugin/server/server_plugin.py
This PR wraps both the `installer.install` and `installer.uninstall` in a wrapper function to ensure any uncaught exceptions can still alert the user.
This is a somewhat hacky solution and I'm not 100% clear on why this behavior appears here.
Testing done: raised exception inside installer code manually and checked output
> vdk-server: Wrap installation/uninstallation to catch any uncaught errors

- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
CICD pipeline is failing because cockroach doesn't have enough mem
> control-service: increase cockroach mem

- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
The previous code is not written assuming assuming the object in a mock when infact it is a spy. 
The difference between a mock and a spy is that with a spy the real functions are called. 
That is why we can remove the line with `.callRealMethod`.
I have also rewritten how we return mocked functions response objects. 
They way they were written was resulting in the actual function being called when we are first mocking it. 
However now it never calls it. 
I didn't rename it from mock to spy. because this is everywhere in the code and can be done in a different PR if ppl think it is important. 
Tested on CICD
> control-service: rewrite correctly for spies

- projects/vdk-plugins/vdk-test-utils/src/vdk/plugin/test_utils/util_funcs.py
Later it will be used to replace the other mock util function "populate_mock_managed_cursor"
> vdk-test-utils: add new util function

- projects/vdk-plugins/vdk-impala/tests/impala_error_handler_test.py
- projects/vdk-plugins/vdk-impala/tests/impala_handle_hdfs_error_test.py
- projects/vdk-plugins/vdk-impala/tests/impala_handle_metadata_exception_with_backoff.py
- projects/vdk-plugins/vdk-impala/tests/impala_handle_metadata_exception_with_invalidate_and_backoff.py
- projects/vdk-plugins/vdk-impala/tests/impala_handle_metadata_exception_with_invalidate_and_retry_test.py
- projects/vdk-plugins/vdk-impala/tests/impala_handle_network_error_test.py
- projects/vdk-plugins/vdk-impala/tests/impala_handle_pool_error_test.py
- projects/vdk-plugins/vdk-impala/tests/impala_handle_should_not_retry_error_test.py
The old util funcition will be deprecated and removed with the changes in https://github.com/vmware/versatile-data-kit/pull/3283
We cannot change vdk-core and vdk-plugins in one pr, so we need to have the new funcition for impala beforehand since its tests run on vdk-core release, which fail in https://github.com/vmware/versatile-data-kit/pull/3283 because of core changes
> vdk-impala: use new util function in impala

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
The method was only calling another public method in the same class. 
It is left over mess from supporting multiple versions of k8s.
> control-service: remove useless method

- projects/vdk-core/src/vdk/api/plugin/connection_hook_spec.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/connection_plugin.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/database_managed_connection.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_cursor.py
- projects/vdk-core/tests/functional/run/test_run_restricted_hooks.py
- projects/vdk-core/tests/functional/run/test_run_sql_queries.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/connection/test_managed_cursor.py
- projects/vdk-plugins/vdk-test-utils/src/vdk/plugin/test_utils/util_funcs.py
All hooks that expose a cursor are now methods in ManagedConnectionBase We can stop checking for hook overrides
Remove unused hooks
Remove the hook overrides checks
Introduce default for db_connection_recover_operation
Fix tests
Potentially breaking
We should first merge https://gitlab.eng.vmware.com/product-analytics/data-pipelines/supercollider-vdk/-/merge_requests/271
Integration/functional tests
> vdk-core: remove hook checks

- projects/vdk-plugins/vdk-greenplum/requirements.txt
- projects/vdk-plugins/vdk-impala/requirements.txt
- projects/vdk-plugins/vdk-oracle/requirements.txt
- projects/vdk-plugins/vdk-postgres/requirements.txt
- projects/vdk-plugins/vdk-trino/requirements.txt
A new version of testcontainers was release yesterday that needs typing extensions but doesn't include it as a dependency. 
Tested on CICD
> vdk-plugins: fix build pipeline

- projects/control-service/cicd/deploy-testing-pipelines-service.sh
What: Adapt the CICD chart deploy script to use postgres.
Why: The "control_service_deploy_testing_data_pipelines" job fails because the DB is not able to run properly.
Signed-off by: Yoan Salambashev <yoan.salambashev@broadcom.com>
> control-service: adapt the CICD chart deploy script to use postgres

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/config_help.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
- projects/vdk-core/src/vdk/internal/core/config.py
- projects/vdk-core/tests/functional/run/test_run_notifications.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_config_help.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_base.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/ingestion/test_ingester_router.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/job_properties/test_properties_router.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/job_secrets/test_secrets_router.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/run/test_substitute_query_params.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/termination_message/test_writer.py
- projects/vdk-core/tests/vdk/internal/core/test_config.py
Solving: https://github.com/vmware/versatile-data-kit/issues/3305
The main change is that now we have sections list in Configuration and ConfigurationBuilder instead of having only key-value lists
> vdk-core: introduce sections to configurations

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DataJobsSynchronizer.java
Why
Currently, we are experiencing an issue with the Synchronizer task; it is overflowing the task queue.
```
org.springframework.core.task.TaskRejectedException: Executor [java.util.concurrent.ThreadPoolExecutor@55435baf[Running, pool size = 10, active threads = 10, queued tasks = 1999, completed tasks = 1174429]] did not accept task: com.vmware.taurus.service.deploy.DataJobsSynchronizer$$Lambda$2193/0x00007fe844d1c6d0@774553e9
```
What
Added logging and increased the Scheduler Lock lockAtMostFor to 24h since the default is 10m which could lead to timeout of the task in some cases.
Signed-off by: Miroslav Ivanov [miroslav.ivanov@broadcom.com](mailto:miroslav.ivanov@broadcom.com)
> control-service: add additional logging to synchronizer task

- projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLExecutionsLogsUrlIT.java
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-test.properties
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionLogsUrlBuilder.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/execution/JobExecutionLogsUrlBuilderIT.java
Change the prefix of the log builder from {{ and }} to { and } to avoid kyverno templating issues.
> control-service: change log builder template

- projects/vdk-core/src/vdk/internal/builtin_plugins/config/job_config.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/config/secrets_config.py
- projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
- projects/vdk-core/src/vdk/internal/core/config.py
- projects/vdk-core/tests/functional/cli/test_query_command_plugin.py
- projects/vdk-core/tests/functional/run/jobs/simple-job-config-ini-sections/1_step.py
- projects/vdk-core/tests/functional/run/jobs/simple-job-config-ini-sections/config.ini
- projects/vdk-core/tests/functional/run/test_run_configuration.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_job_config.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_vdk_config.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/job_properties/test_properties_router.py
- projects/vdk-core/tests/vdk/internal/builtin_plugins/job_secrets/test_secrets_router.py
- projects/vdk-core/tests/vdk/internal/core/test_config.py
ENV variables with format
```
VDK_{SECTION}_{CONFIG_NAME}
{SECTION}_{CONFIG_NAME}
```
and secrets with format
```
{SECTION}_{CONFIG_NAME}
```
override config options from `config.ini` and default config values
Environment variables take precedence over secrets when overriding
Per-section configs should behave the same way as the main section config
Unit tests, functional tests
> vdk-core: override configs per section

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/DeploymentServiceV2.java
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/DeploymentServiceV2TestIT.java
Fix the deployment logic, so that a job would be
built, even if it is disabled.
Remove redundant test.
> control-service: fix disabled jobs not building

- projects/control-service/projects/base/src/main/java/com/vmware/taurus/security/SecurityConfiguration.java
- projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
- projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
- projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-test.properties
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/authorization/AuthorizationInterceptor.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/authorization/provider/AuthorizationProvider.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/JobsService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/JobCredentialsService.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/webhook/CreateOAuthAppBody.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/webhook/CreateOAuthAppResponse.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/webhook/CreateOAuthAppWebHookProvider.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/webhook/CreateOAuthAppWebHookResult.java
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/webhook/WebHookResult.java
- projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
- projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/credentials/JobCredentialsServiceTest.java
- when creating a data job - deploy the team's oauth credentials as a k8s secret
- if the credentials are missing - create, store and deploy them
- add security exception for oAuth client ID get methods
> control-service: set Team oAuth Creds as secrets

- projects/control-service/projects/pipelines_control_service/build.gradle
- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/JobCredentialsService.java
- projects/control-service/projects/versions-of-external-dependencies.gradle
> control-service: fix oauth secret name

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployerV2.java
fix a bug where team ouath secret name will be
configured with "teamname" instead of actual
team name
> control-service: fix teamname bug

- projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/dimension/scd1_upsert/02-requisite-sql-scripts/02-create-table-and-insert-data.sql
- projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/dimension/scd1_upsert/03-handle-quality-checks_and_move_data.py
- projects/vdk-plugins/vdk-trino/tests/test_vdk_templates.py
What:
Optimize template by splitting staging table population in two step to reduce memory footprint.
Why:
For bigger tables the template struggles to create the staging table with unions between the view data and current table data.
Signed-off-by: Stefan Buldeev sbuldeev@vmware.com
> vdk-trino: Optimize SCD1 Upsert template

- projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
Change the way the success of a data job build is
evaluated since newer version of K8s notify
earlier with different job conditions.
> control-service: fix data jobs builds
