projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py

Make a bit more clear what some configuration options are
Also inlined them with definitions in
https://github.com/vmware/versatile-data-kit/wiki/dictionary

vdk-core: improve help

---

projects/control-service/projects/model/apidefs/datajob-api/api.yaml

Change example mails to non existing mails so that someone does not
accidentally send.

control-serivice: clean up api documentation

---

projects/vdk-heartbeat/.gitlab-ci.yml
projects/vdk-heartbeat/setup.cfg

This change enables support for Python 3.10.
Signed-off-by: gageorgiev <gageorgiev@vmware.com>

vdk-heartbeat: Support 3.10

---

CONTRIBUTING.md
README.md
projects/control-service/CONTRIBUTING.md

We did self-evaluation of https://bestpractices.coreinfrastructure.org/
And this is addressing some very minor issues and recommendations noted
in above link which I fixed while I was filling the evaluation.
You can see link of all current issues that we still need to fix here:
https://bestpractices.coreinfrastructure.org/en/projects/5363
This is also adding a few badges and details on how to subscribe to
youtube channel

vdk: improve badges, address some minor things from CII evaluaotin

---

CONTRIBUTING.md

The html have accidentally corrupted while pushing last time so this
fixes them

vdk: fix contributing.md badges

---

projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli.py
projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/deploy_cli_impl.py
projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_deploy.py

vdk deploy --update should be able to set more than one option at once -
e.g you may want to enable and vdk version at same time in single atomic
operation. For example this is necessary in vdk version to ensure next
run uses the specified version.
We also want to keep `vdk deploy --enable` as well as `vdk deploy --update --enable --vdk-version` 
Signed-off-by: Antoni Ivanov <aivanov@vmware.com>`

vdk-control-cli: enable setting many options at once with vdk deploy

---

projects/vdk-plugins/vdk-server/requirements.txt
projects/vdk-plugins/vdk-server/src/vdk/plugin/server/installer.py

write_default_authentication_disable is no longer necessary as
authentication is automatically detected as part of https://github.com/vmware/versatile-data-kit/pull/305. 

vdk-server: remove write_default_authentication_disable

---

projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLExecutionsIT.java
projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLExecutionsLogsUrlIT.java
projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLExecutionsNextRunIT.java
projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLJobExecutionsSortByEndTimeIT.java
projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLJobExecutionsStatusCountIT.java
projects/control-service/projects/pipelines_control_service/src/integration-test/resources/application-test.properties
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/datajobs/ToApiModelConverter.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionService.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/graphql/ExecutionDataFetcher.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/webhook/ToApiModelConverterJobExecutionTest.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/ExecutionDataFetcherStatusCountTest.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/graphql/ExecutionDataFetcherTest.java

Integrated JobExecutionLogsUrlBuilder with DataJobExecution model.
Testing Done: unit and integration tests

control-service: add logsUrl to DataJobExecution model

---

projects/vdk-plugins/README.md

vdk-plugins: Update README.md

---

projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/graphql/it/GraphQLJobExecutionsStatusCountIT.java

Removed not necessary annotations in
GraphQLJobExecutionsSortByEndTimeIT.
Testing Done: integration tests

control-service: removed not necessary annotations

---

projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_config.py
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_plugin.py
projects/vdk-plugins/vdk-trino/tests/conftest.py

Change trino configuration to use the established pattern for
configuration

vdk-trino: extract TrinoConfiguration in separate module

---

projects/vdk-core/src/vdk/api/plugin/plugin_input.py

Currently, the IIngesterPlugin defines two new data types, IngestionResult
and IngestionMetadata, that are to be used when doing ingestion tasks. These
two types are essentially overlapping in terms of their purpose, as both are
meant to contain data about the ingestion process itself.
This change removes the IngestionResult type, and leaves only the IngestionMetadata
one, in order to make the interface logic more consistent.
Testing Done: Documentation change, no testing needed.

vdk-core: Revise parts of the IIngesterPlugin Interface

---

projects/control-service/projects/base/src/main/java/com/vmware/taurus/security/SecurityConfiguration.java
projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/datajobs/it/DataJobCrudIT.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/doc/SwaggerConfig.java

swagger ui was inaccessible after latest changes.
reverting swagger path changes until resolved.
Testing Done: tests run

control-service: revert swagger path changes

---

CONTRIBUTING.md

Small clarification on the release process of VDK . 

versatile-data-kit: update contirbuting.md

---

projects/control-service/CHANGELOG.md

This change updates CHANGELOG.md of control service to cover the latest changes.
Testing Done: Documentation change, no testing needed.

control-service: Update CHANGELOG.md

---

projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/dimension/scd1/README.md
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/dimension/scd2/README.md
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/fact/periodic_snapshot/README.md

Add link to detailed examples of usage in template descriptions

vdk-trino: add link to template examples

---

projects/vdk-core/src/vdk/api/data_job.py

It was using internal (unknown to most people) terms. 

versatile-data-kit: fix description

---

README.md

Add VDK ingestion, transformation, and full example blog post to the readme file

Add How To section to the readme

---

projects/vdk-core/src/vdk/internal/builtin_plugins/run/cli_run.py

At the end of a data job execution, we log execution summary, which describes the
python and sql steps that have been executed, their status, etc. Sometimes,
when a job has a large number of steps, the execution summary will be logged as a
single large string message.
This is not an issue in most cases. However, on some operating systems, there are
limits as to how large a logging message can be when printed to terminal, or send
through a socket, and in such situations jobs fail with `OSError: [Errno 40] Message too long`
errors triggered by the logging module.
This change checks if the message is too long, and if that is the case, splits it into
chunks. The chunks are then logged as separate messages to avoid OS-specific errors
related to logging.
Testing Done: Locally ran a data job …

vdk-core: Split execution summary into chunks

---

examples/ingest-csv-file-example/README.md

versatile-data-kit: add link to csv example doc

---

examples/ingest-from-rest-api-example/README.md

versatile-data-kit: update link in examples

---

projects/vdk-plugins/airflow-provider-vdk/README.md

Add more meaningful readme that links to important resources related to the airflow provider and shows examples/demo. 

vdk-airflow: populate readme

---

specs/vep-994-jupyter-notebook-integration/README.md

This VEP outlines the architectural changes required to provide VDK users with new UI, which will be introduced by integrating VDK with Jupiter Notebook.

VEP-994: Jupiter Notebook Integration

---

projects/vdk-plugins/vdk-ingest-http/src/vdk/plugin/ingest_http/ingest_http_plugin.py
projects/vdk-plugins/vdk-ingest-http/tests/functional/test_http_ingest.py

vdk-ingest-http: fix default value for backoff factor, add retry test

---

projects/control-service/cicd/.gitlab-ci.yml

Same change as in https://github.com/vmware/versatile-data-kit/pull/1211

control-service: fix cicd deployment

---

projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml

vdk-pipelines-control-service: Make new release of helm chart

---

projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/templates/load/fact/insert/README.md

Explain what is the template fully doing (parts were missing) 

vdk-impala: improve explanation in readme

---

events/dsc/README.md

Adding link to presenation slides from Practical Kimball Data Patterns session

vdk-events: add presentation slides of DSC event

---

projects/vdk-plugins/vdk-kerberos-auth/.plugin-ci.yml
projects/vdk-plugins/vdk-kerberos-auth/setup.py
projects/vdk-plugins/vdk-sqlite/.plugin-ci.yml
projects/vdk-plugins/vdk-sqlite/src/vdk/plugin/sqlite/sqlite_connection.py

vdk-sqlite: support for Python 3.11

---

projects/vdk-plugins/vdk-trino/.plugin-ci.yml
projects/vdk-plugins/vdk-trino/setup.py

vdk-trino: support for Python 3.11

---

projects/vdk-plugins/vdk-jobs-troubleshooting/.plugin-ci.yml

vdk-jobs-troubleshooting: release the plugin

---

specs/vep-1507-vdk-operations-ui/README.md

Add template file for operations UI VEP
This will make it easy to see what changes ppl are making in the next commits
No changes are actually in this file but it will make it easier to identify iterative changes for next commits.

VEP-1507: Add template file for operations UI VEP

---

projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/KerberosCredentialsRepository.java

What?
Fix a possible NPE which was introduced recently.
Signed-off-by: Dako Dakov ddakov@vmware.com

vdk-control-service: fix possible NPE

---

specs/vep-1507-vdk-operations-ui/README.md

I want to merge summary glossary and motivation first and tackle the next sections later. 

vdk-spec: summary, glossary, motivation

---

specs/vep-1507-vdk-operations-ui/README.md

vdk-spec: remove api section because the frontend will have no impact on the api

---

specs/vep-1507-vdk-operations-ui/README.md

provide transparency to repo users on design of frontend

vdk-spec: describe package publishing

---

projects/control-service/projects/gradle/wrapper/gradle-wrapper.properties
projects/control-service/projects/model/gradle/wrapper/gradle-wrapper.properties

Beneficial to be on the latest version of projects. 

control-service: upgrade gradle.

---

README.md

The URL was updated as I merged the branch, here's the fix for it.

Hotfix: Update the URL for gif

---

specs/vep-1416-vdk-troubleshooting-tools/README.md

This change modifies the status of vep-1416 to implemented, as the vdk-troubleshooting-tools plugin has been implemented.

[specs] vep-1416: Change status of vep

---

specs/vep-1507-vdk-operations-ui/README.md

- added appropriate title for the document that was missing
- replaced all references to "front end" with "VDK Operations UI"
- passed all texts through hemingway.app to check for readability
- passed all texts through grammarly to check for grammar and spelling errors
- re-phrased some sections to make them more coherent

specs: edit vep-1507 for style and grammar

---

projects/control-service/CONTRIBUTING.md

Contributor doc for control-service is inaccurate and hard to use
Restructure document so how-to-run sections are at the beginning Update running locally section with correct instructions
Ran the service locally using updated instructions
Documentation change, non-breaking
https://github.com/vmware/versatile-data-kit/issues/1780

docs/control-service: update contributor documentation

---

specs/vep-1739-multiple-python-versions/README.md

This PR aims to address the following comment: https://github.com/vmware/versatile-data-kit/pull/1878#discussion_r1163707139

specs: VEP-1739 updated API section

---

specs/vep-1507-vdk-operations-ui/README.md

https://github.com/vmware/versatile-data-kit/issues/1643
Part of the wider effort to improve frontend documentation
Add build and test config description to VEP-1507
n/a
Documentation

frontend: Update docs with build/test configuration

---

specs/vep-1493-vault-integration/README.md

vdk-VEP-1493: update vep status

---

CONTRIBUTING.md

Add a link to VDK Design Principles to Contributing guide

versatile-data-kit: Update CONTRIBUTING.md

---

projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/data-job-page.component.html
projects/frontend/data-pipelines/gui/projects/data-pipelines/src/lib/components/data-job/data-job-page.component.scss

Upgrade lineage to a 'beta' version
Testing done: locally

frontend: Upgrade lineage to beta version

---

projects/vdk-plugins/vdk-plugin-control-cli/src/vdk/plugin/control_cli_plugin/vdk_plugin_control_cli.py
projects/vdk-plugins/vdk-plugin-control-cli/tests/test_execution_skip.py

Add vdk info command to list of cli commands

vdk-control-cli: add vdk info command to list of cli commands

---

projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/properties/DataJobsPropertiesControllerTest.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/properties/PropertiesServiceTest.java

vdk-control-service: properties service unit tests
add unit tests for the properties service.

add properties service unit tests

---

projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java

they aren't needed
remove them
Locally

control-service: remove unused properties

---

projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/exception/DataJobSecretsSizeLimitException.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/exception/SecretStorageNotConfiguredException.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/controller/DataJobsSecretsController.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/controller/NoOpDataJobsSecretsController.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/vault/VaultJobSecretsService.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/secrets/DataJobsSecretsControllerTest.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/secrets/vault/VaultJobSecretsServiceTest.java

Add unit tests for the secrets service.
Minor code changes to address redundancies, feedback from previous review.

control-service: secrets service unit tests

---

projects/control-service/cicd/.gitlab-ci.yml
projects/control-service/cicd/deploy-testing-pipelines-service.sh

There is a regression in the build pipelines. we need to merge this so the builds can pass again.
On a previous commit I ran all the failing steps on this branch and it passed.

control-service: fix failing pipelines

---

projects/vdk-plugins/vdk-jupyter/.plugin-ci.yml
projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package-lock.json
projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/package.json

What:
Pinned all the dependencies to a specific version and add package-lock.json file. The purpose is to lock the installed dependencies to a specific version number so that subsequent installations can replicate the exact same dependency tree in the future, regardless of any new package releases.
Why: the package has really unstable build
Tested: cicd script is added for installing and building the package

vdk-jupyter: installation and build

---

projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/properties.py
projects/vdk-control-cli/src/vdk/internal/control/command_groups/job/secrets.py

vdk-control-cli: add vdk secrets command

---

projects/frontend/cicd/.gitlab-ci.yml
projects/frontend/cicd/install_data_pipelines.sh

The data pipelines build script does not work correctly. This is because of an incorrect path in the ci config and typo in the install_data_pipelines script.
Fix path and typo
- Tested the script locally to make sure the correct execution path is hit depending on what's passed as shared components rc version
- CI
Bugfix

frontend: fix data-pipelines build scripts

---

projects/control-service/CONTRIBUTING.md

Changing Java minimal version to 17 since the project can not build with Java 11

control-service: Update contributing.md with correct java requirements

---

projects/control-service/projects/job-base-image-secure/Dockerfile-data-job-base

This change aims to fix the following CI/CD job - https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/4799311858

control-service: fix secure base image

---

specs/NNNN-template/README.md
specs/vep-1243-vdk-dag/README.md
specs/vep-1416-vdk-troubleshooting-tools/README.md
specs/vep-1493-vault-integration/README.md
specs/vep-1507-vdk-operations-ui/README.md
specs/vep-1739-multiple-python-versions/README.md
specs/vep-994-jupyter-notebook-integration/README.md

Making sure authors and status of existing VEPs are correct.

specs: update VEPs metadata

---

projects/vdk-plugins/vdk-notebook/README.md
projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/cell.py
projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/notebook.py
projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/notebook_based_step.py
projects/vdk-plugins/vdk-notebook/tests/jobs/ingest-job-sql-magic-cells-broken/config.ini
projects/vdk-plugins/vdk-notebook/tests/jobs/ingest-job-sql-magic-cells-broken/steps.ipynb
projects/vdk-plugins/vdk-notebook/tests/jobs/ingest-job-sql-magic-cells/config.ini
projects/vdk-plugins/vdk-notebook/tests/jobs/ingest-job-sql-magic-cells/steps.ipynb
projects/vdk-plugins/vdk-notebook/tests/test_plugin.py

vdk run now would recognize %%vdksql cell as steps and execute them and SQL steps.
This is a continuation of https://github.com/vmware/versatile-data-kit/pull/2619

vdk-notebook: add support for execute %%vdksql cells

---

projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/deploy-job-component.spec.ts
projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/show-dialog-deploy.spec.tsx
projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/__tests__/show-dialog.spec.tsx
projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/CreateJob.tsx
projects/vdk-plugins/vdk-jupyter/vdk-jupyterlab-extension/src/components/DeployJob.tsx

Currently it was not shown on Deploy or Create but those could take some time espeically deploy which can be rather slow.  This is causing quite a confusion to users

vdk-jupyterlab: show status dialog on deploy and create

---

projects/vdk-plugins/vdk-duckdb/README.md

Update README of vdk-duckdb plugin

vdk-duckdb: update readme

---

projects/vdk-core/src/vdk/internal/core/errors.py

Box doesn't look well in cloud deployments and log tracking tools
Remove box and delimit exception message lines with a space instead of newline
User experience after change https://pastebin.com/raw/NwmpWiay
Caused configuration error locally and ran example data job to check format
Bugfix
https://github.com/vmware/versatile-data-kit/issues/2678

vdk-core: remove box around exception when printed

---

projects/vdk-plugins/vdk-csv/tests/functional/test_csv_plugin.py

Addressing: https://github.com/vmware/versatile-data-kit/issues/2677

vdk-csv:  uncomment test

---

projects/vdk-plugins/vdk-jupyter/getting-started.ipynb

Add link to https://github.com/vmware/versatile-data-kit/wiki/Deploy-Data-Job-through-the-Jupyter-UI in getting started (left as TODO)

vdk-jupyter: add Tutorial link in getting-started.ipynb

---

projects/vdk-plugins/vdk-notebook/src/vdk/plugin/notebook/notebook_plugin.py

This is no longer used superseded by vdk-core change in https://github.com/vmware/versatile-data-kit/pull/2709

vdk-notebook: remove obsolete code

---

events/workshops/ingest-anonymize/IngestAndAnonymizeWorkshop.ipynb
events/workshops/ingest-anonymize/README.md

We are planning a workshop that would guide people through the process of ingesting data and creating a configurable plugin to anonymize data before ingesting it into a database.
This is its home page and materials

vdk-events: Add ingest and anonymize workshop

---

projects/vdk-plugins/vdk-csv/tests/functional/test_csv_plugin.py
projects/vdk-plugins/vdk-impala/tests/functional/template_regression_test.py

Uncomment tests after https://github.com/vmware/versatile-data-kit/pull/2840

vdk-impala: uncomment tests that were not passing due to core change

---

projects/vdk-plugins/vdk-data-sources/setup.py
projects/vdk-plugins/vdk-data-sources/src/vdk/plugin/data_sources/plugin_entry.py
projects/vdk-plugins/vdk-data-sources/src/vdk/plugin/data_sources/sources_command.py
projects/vdk-plugins/vdk-data-sources/tests/test_sources_command.py

Add `vdk data-sources --list` to list all registered data sources
and `vdk data-sources --config source-name` to lsit configuraiton options for the given source

vdk-data-sources: add sources command

---

projects/control-service/projects/helm_charts/pipelines-control-service/templates/poddisruptionbudget.yaml

fix automatically formatted template

control-service: fix pod disruption budget template

---

projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_memory_error_handler.py

Add another exception type to be handled by the Impala Memory Handler.

vdk-impala: enhance memory error handling

---

projects/vdk-plugins/vdk-jupyter/.plugin-ci.yml

Add retries for a task in the CICD pipeline
it seems to randomly fail.

vdk-jupyter: add retries

---

projects/vdk-plugins/vdk-structlog/README.md

This change adds a description of log_level_module to the readme file of vdk-structlog.

vdk-structlog: Document log level module config var

---

projects/vdk-plugins/vdk-lineage/requirements.txt
projects/vdk-plugins/vdk-lineage/setup.py

What: pinned sqllineage to specific version
Why: tests fail with the newest version

vdk-lineage: pin sqllineage version

---

specs/vep-milestone-25-vector-database-ingestion/README.md

Update with some clarification on the API. 
This is just the first update on this section . One or 2 more will come.

specs: update Vector DB Ingestion VEP

---

projects/vdk-plugins/vdk-structlog/src/vdk/plugin/structlog/constants.py
specs/vep-2448-vdk-run-logs-simplified-and-readable/README.md

- Update document to reflect current state of development
- Simplify language
Note: I ended up re-writing the whole document. Please use the [rich diff](https://github.com/vmware/versatile-data-kit/pull/3035/files?short_path=35d6e16#diff-35d6e168db90c7217bd1a5abb0e406f223b5f1e33e46edd8775a5289efd9ad46) to review

vdk-structlog: update VEP-2448 to reflect current state of development

---

projects/vdk-plugins/vdk-structlog/README.md

Add info about bound loggers and syslog support

vdk-structlog: update README.md

---

projects/vdk-plugins/quickstart-vdk/.plugin-ci.yml
projects/vdk-plugins/quickstart-vdk/setup.py

Solves: [vdk-structlog: include in quickstart-vdk#2814](https://github.com/vmware/versatile-data-kit/issues/2814)

vdk-quickstart: add vdk-structlog 

---

projects/vdk-plugins/vdk-plugin-control-cli/tests/test_secrets_plugin.py

Uncomment test after https://github.com/vmware/versatile-data-kit/pull/3125

vdk-control-cli: uncomment secrets test

---

projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_connection.py
projects/vdk-plugins/vdk-impala/src/vdk/plugin/impala/impala_plugin.py

Solving: https://github.com/vmware/versatile-data-kit/issues/3215

vdk-impala: replace old hooks with db connection methods from ManagedConnectionBase

---

projects/vdk-plugins/vdk-oracle/src/vdk/plugin/oracle/oracle_plugin.py

Solving: https://github.com/vmware/versatile-data-kit/issues/3156 
Tested: locally with job runs

vdk-oracle: remove secrets override

---

projects/control-service/projects/gradle/wrapper/gradle-wrapper.properties
projects/control-service/projects/model/gradle/wrapper/gradle-wrapper.properties

This doesn't happen automatically from the dependabot.

control-service: upgrade gradle version

---

projects/control-service/projects/helm_charts/pipelines-control-service/Chart.yaml

I was seeing an issue where cockroach was not creating properly in cicd. 
Using the latest verison fixes the issue.
tested on CICD

control-service: use newer cockroach version

---

projects/control-service/projects/model/build.gradle
projects/control-service/projects/settings.gradle

control-service: upgrade spring

---

projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/execution/JobExecutionService.java

What: Release control service with no change.
Why: Fix the broken pipeline.
Signed-off by: Yoan Salambashev <yoan.salambashev@broadcom.com>

control-service: nothing change to release the control service

---

projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
projects/control-service/projects/helm_charts/pipelines-control-service/templates/secret_pull_img.yaml

control-service: add support for jfrog docker repo

---

projects/vdk-core/src/vdk/internal/core/config.py
projects/vdk-core/tests/vdk/internal/core/test_config.py

is_default should check if set_value was called

vdk-core: fix is_default implementation

---

projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JfrogRegistryInterface.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java

control-service: fix jfrog image check

---

projects/control-service/cicd/.gitlab-ci.yml
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JfrogRegistryInterface.java

Commented post-deployment test due to the vdk issue - https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/6726697187.

control-service: commented post deployment test

---

projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java

control-service: jfrog registry fix

---

projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/ingest_to_trino.py
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_config.py
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_plugin.py
projects/vdk-plugins/vdk-trino/tests/test_vdk_trino_lineage.py

What: introduced a plugin class to vdk-trino similar to vdk-impala and vdk-oracle
Also re the old style of error handling with the new one
Tests: all the functional tests are rerun and green

vdk-trino: introduce plugin class

---

projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_connection_base.py
projects/vdk-core/src/vdk/internal/builtin_plugins/run/file_based_step.py
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-python-job/10_step.sql
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-python-job/11_step.sql
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-python-job/12_step.sql
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-python-job/20_python_step.py
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-python-job/config.ini
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-python-job/requirements.txt
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-sql-job/10_step.sql
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-sql-job/11_step.sql
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-sql-job/12_step.sql
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-sql-job/20_step.sql
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-sql-job/21_step.sql
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-sql-job/22_step.sql
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-sql-job/config.ini
projects/vdk-core/tests/functional/run/jobs/multiple-dbs-from-same-type-sql-job/requirements.txt
projects/vdk-core/tests/functional/run/test_run_decorate_job_input.py
projects/vdk-core/tests/functional/run/test_run_with_multiple_databases.py

Stacked on top of https://github.com/vmware/versatile-data-kit/pull/3344

vdk-core: support specifying database in sql files

---

projects/vdk-plugins/vdk-postgres/README.md
projects/vdk-plugins/vdk-postgres/src/vdk/plugin/postgres/postgres_plugin.py
projects/vdk-plugins/vdk-trino/README.md
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_plugin.py

What: provide better README details for multiple db usage and better error handling

vdk-plugins: trino postgres fix

---

projects/vdk-plugins/vdk-trino/MANIFEST.in
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_plugin.py

Updated manifest file to include sql files

VDK-plugin: update trino plugin manifest file

---

projects/vdk-plugins/vdk-trino/.plugin-ci.yml
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_connection.py
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_error_classifier.py
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_error_handler.py

Added error classifier and error handler

VDK-Plugin: Added error handler to trino plugin

---

projects/vdk-core/cicd/simple-functional-test.sh
projects/vdk-core/src/vdk/api/job_input.py
projects/vdk-core/src/vdk/api/plugin/plugin_input.py
projects/vdk-core/src/vdk/internal/builtin_plugins/run/job_input.py
projects/vdk-core/src/vdk/internal/builtin_plugins/templates/template_impl.py
projects/vdk-core/tests/vdk/internal/builtin_plugins/templates/test_template_impl.py
projects/vdk-plugins/vdk-impala/.plugin-ci.yml
projects/vdk-plugins/vdk-oracle/.plugin-ci.yml
projects/vdk-plugins/vdk-trino/.plugin-ci.yml
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/dimension/scd1/README.md
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/fact/insert/README.md
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/fact/snapshot/README.md
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/versioned/README.md
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_plugin.py

1. added database param to add_template and execute_template method
2. Added changes into trino plugin
Testing:
- tested impala job working fine
- tested trino template job working fine
- tested trino template job with setting default db as imapala

VDK-Plugin: Update template register process for multiple plugin

---

projects/vdk-plugins/.plugin-common.yml

vdk-core: fix image publishing

---

projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/secrets/service/vault/TestVaultJobSecretsServiceIT.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/exception/DataJobSecretsException.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/exception/DataJobTeamSecretsException.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/controller/DataJobsSecretsController.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/JobSecretsService.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/vault/VaultJobSecretsService.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/vault/VaultTeamCredentials.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/secrets/DataJobsSecretsControllerTest.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/secrets/vault/VaultJobSecretsServiceTest.java

Add support for setting Team Ouath Credentials in
the VaultJobSecretsService

control-service: OAuth Creds in Secrets Service

---

projects/control-service/projects/model/apidefs/datajob-api/api.yaml
projects/control-service/projects/pipelines_control_service/src/integration-test/java/com/vmware/taurus/secrets/service/vault/TestVaultJobSecretsServiceIT.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/controller/DataJobsSecretsController.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/JobSecretsService.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/vault/VaultJobSecretsService.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/secrets/DataJobsSecretsControllerTest.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/secrets/vault/VaultJobSecretsServiceTest.java

Add Control Service api implementation for Oauth Credentials

control-service: api implementation for Oauth Credentials

---

projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/authorization/AuthorizationInterceptor.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/authorization/AuthorizationInterceptorTest.java

control-service: add OAuth authN & authZ for data jobs

---

projects/control-service/projects/model/apidefs/datajob-api/config-python.json

Publish a new version of the control service python client library with the latest Oauth related changes

control-service: publish latest python client

---

projects/vdk-control-cli/requirements.txt
projects/vdk-control-cli/setup.cfg

vdk-control-cli: adopt latest cs api

---

projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/credentials/JobCredentialsService.java

control-service: remove rundant encoding

---

projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/KubernetesService.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageBuilder.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployer.java
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/service/deploy/JobImageDeployerV2.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/datajobs/MockKubernetes.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/KubernetesServiceTest.java
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/service/deploy/JobImageBuilderTest.java

Add the team oauth secrets to the cronjob
definition

control-service: add team oauth secrets to cronjob

---

projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py

Add configuration options for team oauth
configuration

vdk-core: add team oauth configuration

---

projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/dimension/scd1/02-requisite-sql-scripts/02-insert-overwrite.sql
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/dimension/scd1/02-requisite-sql-scripts/02-truncate-table.sql
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/dimension/scd1/03-handle-quality-checks_and_move_data.py

various small fixes to  the scd1 template

vdk-trino: fix scd1 template

---

projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_config.py
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_connection.py
projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_plugin.py
projects/vdk-plugins/vdk-trino/tests/test_trino_multiple_db.py

Add the ability to authenticate to trino using oAuth

vdk-trino: add oauth connection

---

projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/templates/load/dimension/scd1/03-handle-quality-checks_and_move_data.py

scd1 template - stop temp table deletion

vdk-trino: scd1 template - stop temp table deletio

---

projects/control-service/projects/helm_charts/pipelines-control-service/templates/_helpers.tpl
projects/control-service/projects/helm_charts/pipelines-control-service/templates/deployment.yaml
projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
projects/control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/secrets/service/vault/VaultJobSecretsService.java
projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
projects/control-service/projects/pipelines_control_service/src/test/java/com/vmware/taurus/secrets/vault/VaultJobSecretsServiceTest.java

Allow the configuration of the KV store name for Vault

control-service: make kv store configurable

---

projects/vdk-core/cicd/simple-functional-test.sh
projects/vdk-core/setup.cfg

Add dependency to setuptools to fix python 3.12
dependency issue

vdk-core: add setuptools dependency

---

projects/vdk-plugins/vdk-trino/src/vdk/plugin/trino/trino_connection.py

control-service: Extending Trino lineage
Add lineage for "CREATE AS SELECT"
---------
Signed-off-by: Tonka Zheleva <tonka.zheleva@broadcom.com>

control-service: Extending Trino lineage

---

projects/vdk-control-cli/.gitlab-ci.yml
projects/vdk-control-cli/requirements.txt
projects/vdk-control-cli/tests/vdk/internal/control/command_groups/job/test_list.py

vdk-control-cli: bump werkzeug version
